package com.google.android.finsky.config;

import com.google.android.finsky.config.GservicesValue;

public class G {

   public static final GservicesValue<String> adPrefsLearnMoreUrl;
   public static GservicesValue<String> analyticsAccountId;
   public static GservicesValue<Boolean> analyticsEnabled;
   public static GservicesValue<Long> androidId;
   public static GservicesValue<String> appsHelpUrl;
   public static GservicesValue<String> appsRefundPolicyUrl;
   public static GservicesValue<String> authTokenType;
   public static GservicesValue<String> billingPrivacyPolicyUrl;
   public static GservicesValue<String> booksHelpUrl;
   public static GservicesValue<String> booksRefundPolicyUrl;
   public static GservicesValue<String> checkoutAuthTokenType;
   public static final GservicesValue<String> checkoutEscrowUrl;
   public static final GservicesValue<String> checkoutSupportCvcHelpUrl;
   public static GservicesValue<String> clientId;
   public static GservicesValue<String> contentFilterInfoUrl;
   public static GservicesValue<Boolean> contentRatingEnabled;
   public static GservicesValue<Boolean> dcbDebugOptionsEnabled;
   public static GservicesValue<Boolean> debugOptionsEnabled = GservicesValue.value("finsky.debug_options_enabled", (boolean)0);
   public static GservicesValue<Integer> defaultContentFilterLevel;
   public static GservicesValue<String> defaultHelpUrl;
   public static GservicesValue<Boolean> enableSensitiveLogging;
   public static GservicesValue<String> gamesBrowseUrl;
   public static final GservicesValue<Integer> initializeBillingDelayMs;
   public static final GservicesValue<String> ipCountryOverride;
   public static GservicesValue<String> loggingId;
   public static GservicesValue<Integer> logsDispatchIntervalSeconds;
   public static GservicesValue<Integer> maxLogQueueSizeBeforeFlush;
   public static GservicesValue<String> moviesHelpUrl;
   public static GservicesValue<String> moviesRefundPolicyUrl;
   public static GservicesValue<String> myEBooksUrl;
   public static GservicesValue<String> myMoviesUrl;
   public static GservicesValue<String> phoneBooksContactUsUrl;
   public static GservicesValue<String> phoneDefaultContactUsUrl;
   public static GservicesValue<String> phoneMoviesContactUsUrl;
   public static GservicesValue<String> protoLogUrlRegexp;
   public static GservicesValue<String> purchaseHistoryUrl;
   public static final GservicesValue<Integer> purchaseStatusTimeoutMs;
   public static GservicesValue<String> readBookUrl;
   public static GservicesValue<String> tabletBooksContactUsUrl;
   public static GservicesValue<String> tabletDefaultContactUsUrl;
   public static GservicesValue<String> tabletMoviesContactUsUrl;
   public static final GservicesValue<String> vendingAddressServerUrl;
   public static final GservicesValue<Long> vendingAlarmExpirationTimeoutMs;
   public static final GservicesValue<Long> vendingAlarmMaxTimeoutMs;
   public static final GservicesValue<Long> vendingAlarmMinTimeoutMs;
   public static final GservicesValue<Boolean> vendingAlwaysSendConfig;
   public static GservicesValue<String> vendingAuthTokenType;
   public static final GservicesValue<Long> vendingBillingCountriesRefreshMs;
   public static final GservicesValue<Long> vendingCarrierCredentialsBufferMs;
   public static final GservicesValue<Long> vendingCarrierProvisioningRefreshFrequencyMs;
   public static final GservicesValue<Long> vendingCarrierProvisioningRetryMs;
   public static final GservicesValue<Boolean> vendingCarrierProvisioningUseTosVersion;
   public static final GservicesValue<Integer> vendingContentRating;
   public static final GservicesValue<String> vendingDcbConnectionType;
   public static final GservicesValue<Boolean> vendingDcbMmsFallback;
   public static final GservicesValue<Integer> vendingDcbPollTimeoutMs;
   public static final GservicesValue<String> vendingDcbProxyHost;
   public static final GservicesValue<Integer> vendingDcbProxyPort;
   public static final GservicesValue<Boolean> vendingHideContentRating;
   public static final GservicesValue<Boolean> vendingHideWarningMessage;
   public static GservicesValue<String> vendingSecureAuthTokenType;
   public static final GservicesValue<String> vendingSupportUrl;
   public static final GservicesValue<Long> vendingSyncFrequencyMs;
   public static final GservicesValue<Long> vendingUpdateCheckFrequencyMs;
   public static final GservicesValue<Long> vendingWarningMessageFrequencyMs;
   public static GservicesValue<String> webViewUserAgent;
   public static GservicesValue<String> widgetUrl;


   static {
      Long var0 = Long.valueOf(0L);
      androidId = GservicesValue.value("android_id", var0);
      authTokenType = GservicesValue.value("finsky.auth_token_type", "androidmarket");
      gamesBrowseUrl = GservicesValue.value("finsky.games_browse_url", "browse?c=3&cat=GAME");
      Integer var1 = Integer.valueOf(15);
      logsDispatchIntervalSeconds = GservicesValue.value("finsky.logs_dispatch_interval_seconds", var1);
      Integer var2 = Integer.valueOf(40);
      maxLogQueueSizeBeforeFlush = GservicesValue.value("finsky.maximum_log_queue_size", var2);
      vendingAuthTokenType = GservicesValue.value("vending.auth_token_type", "android");
      vendingSecureAuthTokenType = GservicesValue.value("vending.secure_auth_token_type", "androidsecure");
      checkoutAuthTokenType = GservicesValue.value("finsky.checkout_auth_token_type", "sierra");
      webViewUserAgent = GservicesValue.value("finsky.web_view_user_agent", "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_7; en-us) AppleWebKit/530.17 (KHTML, like Gecko) Version/4.0 Safari/530.17");
      appsRefundPolicyUrl = GservicesValue.value("finsky.apps_refund_policy_url", "http://market.android.com/support/bin/answer.py?answer=134336&hl=en");
      booksRefundPolicyUrl = GservicesValue.value("finsky.books_refund_policy_url", "http://books.google.com/support/bin/answer.py?hl=en&answer=1062968");
      moviesRefundPolicyUrl = GservicesValue.value("finsky.movies_refund_policy_url", "http://www.google.com/support/youtube/bin/answer.py?hl=en&answer=166672");
      billingPrivacyPolicyUrl = GservicesValue.value("finsky.billing_privacy_policy_url", "https://checkout.google.com/files/privacy.html");
      widgetUrl = GservicesValue.value("finsky.widget_url", "promo?c=3");
      phoneDefaultContactUsUrl = GservicesValue.value("finsky.phone_default_contact_us_url", "http://www.google.com/support/androidmarket/bin/request.py?contact_type=xoom_apps");
      phoneBooksContactUsUrl = GservicesValue.value("finsky.phone_books_contact_us_url", "http://books.google.com/support/bin/request.py?contact_type=eb_device_xoom");
      phoneMoviesContactUsUrl = GservicesValue.value("finsky.phone_movies_contact_us_url", "http://www.google.com/support/youtube/bin/request.py?contact_type=yt_device_xoom");
      tabletDefaultContactUsUrl = GservicesValue.value("finsky.tablet_default_contact_us_url", "http://www.google.com/support/androidmarket/bin/request.py?contact_type=xoom_apps");
      tabletBooksContactUsUrl = GservicesValue.value("finsky.tablet_books_contact_us_url", "http://books.google.com/support/bin/request.py?contact_type=eb_device_xoom");
      tabletMoviesContactUsUrl = GservicesValue.value("finsky.tablet_movies_contact_us_url", "http://www.google.com/support/youtube/bin/request.py?contact_type=yt_device_xoom");
      defaultHelpUrl = GservicesValue.value("finsky.default_help_url", "http://market.android.com/support");
      appsHelpUrl = GservicesValue.value("finsky.apps_help_url", "http://www.google.com/support/androidmarket/bin/answer.py?answer=136634");
      booksHelpUrl = GservicesValue.value("finsky.books_help_url", "http://books.google.com/support/bin/topic.py?topic=28528");
      moviesHelpUrl = GservicesValue.value("finsky.movies_help_url", "http://www.google.com/support/youtube/bin/answer.py?answer=1221183");
      purchaseHistoryUrl = GservicesValue.value("finsky.purchase_history_url", "http://market.android.com/account");
      myEBooksUrl = GservicesValue.value("finsky.my_ebooks_url", "http://books.google.com/ebooks");
      readBookUrl = GservicesValue.value("finsky.read_book_url", "http://books.google.com/ebooks/reader");
      myMoviesUrl = GservicesValue.value("finsky.my_movies_url", "http://www.youtube.com/my_purchases");
      Integer var3 = Integer.valueOf(3);
      defaultContentFilterLevel = GservicesValue.value("finsky.default_content_filter_level", var3);
      contentFilterInfoUrl = GservicesValue.value("finsky.content_filter_info_url", "http://www.google.com/support/androidmarket/bin/answer.py?answer=1075738");
      analyticsEnabled = GservicesValue.value("finsky.analytics_enabled", (boolean)1);
      analyticsAccountId = GservicesValue.value("finsky.google_analytics_account_id", "UA-19761900-1");
      contentRatingEnabled = GservicesValue.value("finsky.content_rating_enabled", (boolean)0);
      checkoutEscrowUrl = GservicesValue.value("finsky.checkout_escrow_url", "https://checkout.google.com/dehEfe");
      Integer var4 = Integer.valueOf(10000);
      initializeBillingDelayMs = GservicesValue.value("finsky.initialize_billing_delay_ms", var4);
      String var5 = (String)false;
      ipCountryOverride = GservicesValue.value("finsky.ip_country_override", var5);
      enableSensitiveLogging = GservicesValue.value("finsky.enable_sensitive_logging", (boolean)0);
      protoLogUrlRegexp = GservicesValue.value("finsky.proto_log_url_regexp", ".*");
      Integer var6 = Integer.valueOf('\u88b8');
      purchaseStatusTimeoutMs = GservicesValue.value("finsky.purchase_status_timeout_ms", var6);
      loggingId = GservicesValue.partnerSetting("logging_id2", "");
      clientId = GservicesValue.partnerSetting("market_client_id", "am-google");
      vendingAlwaysSendConfig = GservicesValue.value("vending_always_send_config", (boolean)0);
      Long var7 = Long.valueOf(86400000L);
      vendingSyncFrequencyMs = GservicesValue.value("vending_sync_frequency_ms", var7);
      Long var8 = Long.valueOf(86400000L);
      vendingUpdateCheckFrequencyMs = GservicesValue.value("vending_update_check_frequency_ms", var8);
      vendingAddressServerUrl = GservicesValue.value("vending_address_server_url", "http://i18napis.appspot.com/address");
      Long var9 = Long.valueOf(604800000L);
      vendingCarrierProvisioningRefreshFrequencyMs = GservicesValue.value("vending_carrier_ref_freq_ms", var9);
      Long var10 = Long.valueOf(120000L);
      vendingCarrierProvisioningRetryMs = GservicesValue.value("vending_carrier_prov_retry_ms", var10);
      vendingCarrierProvisioningUseTosVersion = GservicesValue.value("vending_carrier_prov_use_tos_version", (boolean)0);
      vendingDcbConnectionType = GservicesValue.value("vending_dcb_connection_type", "HIPRI");
      String var11 = (String)false;
      vendingDcbProxyHost = GservicesValue.value("vending_dcb_proxy_host", var11);
      Integer var12 = Integer.valueOf(-1);
      vendingDcbProxyPort = GservicesValue.value("vending_dcb_proxy_port", var12);
      Integer var13 = Integer.valueOf(5000);
      vendingDcbPollTimeoutMs = GservicesValue.value("vending_dcb_poll_timeout_ms", var13);
      vendingDcbMmsFallback = GservicesValue.value("vending_dcb_mms_fallback", (boolean)1);
      Long var14 = Long.valueOf(7200000L);
      vendingBillingCountriesRefreshMs = GservicesValue.value("vending_billingcountries_refresh_ms", var14);
      Long var15 = Long.valueOf(300000L);
      vendingCarrierCredentialsBufferMs = GservicesValue.value("vending_carrier_cred_buf_ms", var15);
      Integer var16 = Integer.valueOf(4);
      vendingContentRating = GservicesValue.value("vending_content_rating", var16);
      vendingHideContentRating = GservicesValue.value("vending_hide_content_rating", (boolean)0);
      adPrefsLearnMoreUrl = GservicesValue.value("vending_ad_prefs_more_url", "http://www.google.com/ads/preferences/html/mobile-about.html");
      dcbDebugOptionsEnabled = GservicesValue.value("finsky.dcb_debug_options_enabled", (boolean)0);
      vendingSupportUrl = GservicesValue.value("vending_support_url", "http://market.android.com/%locale%/support");
      checkoutSupportCvcHelpUrl = GservicesValue.value("finsky.checkout_cvc_help_url", "http://checkout.google.com/support/bin/answer.py?answer=43073&hl=%lang%");
      Long var17 = Long.valueOf(86400000L);
      vendingAlarmMaxTimeoutMs = GservicesValue.value("vending_alarm_max_timeout_ms", var17);
      Long var18 = Long.valueOf(604800000L);
      vendingAlarmExpirationTimeoutMs = GservicesValue.value("vending_alarm_expiration_timeout_ms", var18);
      Long var19 = Long.valueOf(10000L);
      vendingAlarmMinTimeoutMs = GservicesValue.value("vending_alarm_min_timeout_ms", var19);
      vendingHideWarningMessage = GservicesValue.value("vending_hide_warning_message", (boolean)0);
      Long var20 = Long.valueOf(900000L);
      vendingWarningMessageFrequencyMs = GservicesValue.value("vending_warning_message_frequency_ms", var20);
   }

   public G() {}
}
