package com.htc.android.mail.eassvc.common;

import java.io.Serializable;
import java.security.cert.X509Certificate;
import java.util.HashMap;

public final class EASCommon {

   public static final int ACNT_CONFIGURED = 1;
   public static final int ACNT_NOT_CONFIGURED = 0;
   public static final boolean ALLOW_PROTOCOL_14_0 = false;
   public static final int CAL_FILTERTYPE_1_DAY = 1;
   public static final int CAL_FILTERTYPE_1_MON = 5;
   public static final int CAL_FILTERTYPE_1_WK = 3;
   public static final int CAL_FILTERTYPE_2_WK = 4;
   public static final int CAL_FILTERTYPE_3_DAY = 2;
   public static final int CAL_FILTERTYPE_3_MON = 6;
   public static final int CAL_FILTERTYPE_6_MON = 7;
   public static final int CAL_FILTERTYPE_ALL = 0;
   public static final int CANCEL_MAIL_OPTIION_DOWNLOAD_MAIL = 100;
   public static final int CANCEL_MAIL_OPTION_FETCH_ITEM = 101;
   public static final String COMPOSE_MEETING_INVITATION = "6";
   public static final int CONFLICT_CLIENT_WIN = 0;
   public static final int CONFLICT_SERVER_WIN = 1;
   public static final int DEF_CAL_SYNC_DAYS = 4;
   public static final int DEF_CONFLICT_RESOLVE = 1;
   public static final boolean DEF_CONNECT_WHILE_ROAMING = false;
   public static final int DEF_MAIL_DL_ATTACH_SIZE = 0;
   public static final int DEF_MAIL_DL_DAYS = 2;
   public static final int DEF_MAIL_DL_SIZE = 4;
   public static final int DEF_MAIL_FORMAT = 2;
   public static final int DEF_MAIL_FORMAT_2_5 = 1;
   public static final int DEF_PEAK_DAYS = 31;
   public static final int DEF_SCHD_OPTION = 4;
   public static final int DEF_SCHD_OPTION_OFFPEAK = 6;
   public static final int EAS_CONFIG_VERSION = 2;
   public static final int EAS_ERROR_CERTIFICATE_EXPIRED = 246;
   public static final int EAS_ERROR_CERTIFICATE_MISMATCH = 245;
   public static final int EAS_ERROR_CERTIFICATE_NOT_VALID_YET = 244;
   public static final String EAS_ERROR_CERTIFICATE_PATH = "/data/data/com.htc.android.mail/CerError";
   public static final int EAS_ERROR_CERTIFICATE_UNTRUST = 243;
   public static final String EMAIL_ATTACH_DEFAULT_SDCARD_PATH = "/sdcard/.easc/Attachment/";
   public static final String EMAIL_DEFAULT_EASC_SDCARD_ATTACH = "/sdcard/.easc/Attachment";
   public static final String EMAIL_DEFAULT_SDCARD_EASC = "/sdcard/.easc";
   public static final int EMAIL_DELETE_FROM_SERVER = 1;
   public static final String EMAIL_EXCHANGE_DESC = "Exchange Server";
   public static final String EMAIL_PROVIDER_NAME = "Exchange";
   public static final int EXCEPTION = 300;
   public static final int EXCEPTION_CERTIFICATE = 305;
   public static final int EXCEPTION_DOWNLOAD_ATTACH = 306;
   public static final int EXCEPTION_FILE_TOO_LARGE = 309;
   public static final int EXCEPTION_IO = 301;
   public static final int EXCEPTION_MAILBOX_NOT_FOUND = 308;
   public static final int EXCEPTION_MAIL_NOT_FOUND = 307;
   public static final int EXCEPTION_OUT_OF_MEMORY = 302;
   public static final int EXCEPTION_SOCKET_TIME_OUT = 303;
   public static final int EXCEPTION_UNKNOW_HOST = 304;
   public static final int EXTRA_ACCOUNT_ALREADY_EXIST = 236;
   public static final int EXTRA_ACCOUNT_NAME_ALREADY_EXIST = 233;
   public static final int EXTRA_ACCOUNT_SIZE_LIMIT = 235;
   public static final String EXTRA_DELAY_TIME = "com.htc.eas.extra.delayTime";
   public static final String EXTRA_EAS_PROGRESS_MESSAGE = "extra.eas.progress.message";
   public static final String EXTRA_FROM_EASC = "extra.eas.from.easc";
   public static final String EXTRA_FROM_MAIL = "extra.eas.from.mail";
   public static final int EXTRA_INVALID_ACCOUNT_PASSWORD = 234;
   public static final String EXTRA_MAIL_SEND_ERRORCODE = "extra.eas.mail.sendmailErrorcode";
   public static final String EXTRA_PHONE_STATUS = "extra.phone_status";
   public static final int EXTRA_PHONE_STATUS_AIRPLANEMODE = 1;
   public static final int EXTRA_PHONE_STATUS_NORMAL = 0;
   public static final int EXTRA_PHONE_STATUS_ROAMING = 2;
   public static final int EXTRA_POLICY_ADMIN_NOT_EXIST = 243;
   public static final int EXTRA_PROVISION_NOT_APPILED = 246;
   public static final int EXTRA_PROVISION_NOT_FULLY_SUPPORT = 244;
   public static final int EXTRA_PROVISION_PASSWORD_REQUIRED = 245;
   public static final int EXTRA_SENDMAIL_ACCOUNT_FAIL = 1;
   public static final int EXTRA_SENDMAIL_OTHER_FAIL = 2;
   public static final int EXTRA_STORAGE_FULL = 249;
   public static final String EXTRA_SYNCSRC_TYPE = "extra.syncsrc_type";
   public static final String EXTRA_SYNC_ERROR_CODE = "extra.sync_error_code";
   public static final String EXTRA_SYNC_RESULT = "extra.sync_result";
   public static final String EXTRA_SYNC_STATUS = "extra.sync_status";
   public static final int EXTRA_SYNC_STATUS_ADD_MAIL = 14;
   public static final int EXTRA_SYNC_STATUS_CHECK_NEW_MAIL = 11;
   public static final int EXTRA_SYNC_STATUS_CONNECT_TO_SERVER = 10;
   public static final int EXTRA_SYNC_STATUS_Del_MAIL = 15;
   public static final int EXTRA_SYNC_STATUS_FETCH_ATTACH = 17;
   public static final int EXTRA_SYNC_STATUS_FETCH_MAIL = 16;
   public static final int EXTRA_SYNC_STATUS_FETCH_NEW_MAIL = 12;
   public static final String EXTRA_SYNC_STATUS_PARAM = "extra.sync_status_param";
   public static final int EXTRA_SYNC_STATUS_SYNC_MAIL = 13;
   public static final int EXTRA_SYNC_STATUS_UPD_MAIL = 14;
   public static final int EXTRA_SYNC_STATUS_UPD_MAIL_BOXS = 12;
   public static final int EXTRA_SYNC_UPDATE_LAST_SYNC_TIME = 18;
   public static final String EXTRA_TAG = "com.htc.eas.extra.tag";
   public static final String EXTRA_TEST_SERVER_HTTP_SC = "extra.test_server_http_sc";
   public static final String EXTRA_TEST_SERVER_STATUS = "extra.test_server_status";
   public static final int EXTRA_TEST_STATUS_ABORT = 252;
   public static final int EXTRA_TEST_STATUS_CERTIFICATE_NOT_TRUST = 250;
   public static final int EXTRA_TEST_STATUS_FORBIDDEN = 251;
   public static final int EXTRA_TEST_STATUS_INVALID_ACCOUNT = 254;
   public static final int EXTRA_TEST_STATUS_NOSERVER = 255;
   public static final int EXTRA_TEST_STATUS_OK = 0;
   public static final int EXTRA_TEST_STATUS_UNKNOWFAIL = 253;
   public static final int EXTRA_VERIFY_ACCOUNT_ERROR = 1;
   public static final int EXTRA_VERIFY_ACCOUNT_OK = 0;
   public static final int EXTRA_VERIFY_AUTHENTICATION_ERROR = 3;
   public static final int EXTRA_VERIFY_SERVER_ERROR = 2;
   public static final String EXTRA_VERIFY_STATUS_STATUS = "extra.verify_account_status";
   public static final String INTENT_ALL_SYNC_FINISH = "com.htc.eas.intent.all_sync_finish";
   public static final String INTENT_ALL_SYNC_START = "com.htc.eas.intent.all_sync_start";
   public static final String INTENT_CANCEL_SYNC_SOURCE_DONE = "com.htc.eas.intent.cancel_sync_source_done";
   public static final String INTENT_CHK_SVRCAP_FAILED = "com.htc.eas.intent.chk_svrcap_failed";
   public static final String INTENT_DELETE_EXCHG_ACCOUNT = "com.htc.mail.eas.intent.delete_exchg_account";
   public static final String INTENT_DELETE_MAIL_FINISH = "com.htc.eas.intent.delete_mail_finish";
   public static final String INTENT_EAS_PROGRESS_MESSAGE = "intent.eas.progress.message";
   public static final String INTENT_FAILED_SYNC = "com.htc.eas.intent.failed_sync";
   public static final String INTENT_FORCE_RESUME = "intent.eas.mail.priority.high";
   public static final String INTENT_FROM_WHERE = "intent.eas.from_where";
   public static final String INTENT_MAIL_SEND_ERROR = "intent.eas.mail.sendmailError";
   public static final String INTENT_MEETING_INVITATION = "intent.eas.meeting_invitation";
   public static final String INTENT_MODE_WIZARD = "intent.eas.mode.wizard";
   public static final String INTENT_PAUSE_SYNC = "com.htc.eas.intent.pauseSync";
   public static final String INTENT_PHONE_STATUS_CHANGE = "com.htc.eas.intent.phone_status_change";
   public static final String INTENT_RESUME_SYNC = "com.htc.eas.intent.resumeSync";
   public static final String INTENT_START_SYNC = "com.htc.eas.intent.start_sync";
   public static final String INTENT_STOP_SYNC = "com.htc.eas.intent.stop_sync";
   public static final String INTENT_SYNC_CALENDAR = "com.htc.android.eas.syncCalendar";
   public static final String INTENT_SYNC_CHANGE = "com.htc.eas.intent.sync_change";
   public static final String INTENT_SYNC_CONTACTS = "com.htc.android.eas.syncContacts";
   public static final String INTENT_SYNC_STATUS_CHANGED = "com.htc.eas.intent.sync_status_change";
   public static final int MAIL_ATTACH_OPT_100K = 2;
   public static final int MAIL_ATTACH_OPT_1M = 4;
   public static final int MAIL_ATTACH_OPT_25K = 1;
   public static final int MAIL_ATTACH_OPT_2M = 5;
   public static final int MAIL_ATTACH_OPT_500K = 3;
   public static final int MAIL_ATTACH_OPT_ALWAYS = 6;
   public static final int MAIL_ATTACH_OPT_NEVER = 0;
   public static final int MAIL_BODY_TYPE_HTML = 2;
   public static final int MAIL_BODY_TYPE_MIME = 4;
   public static final int MAIL_BODY_TYPE_RTF = 3;
   public static final int MAIL_BODY_TYPE_TEXT = 1;
   public static final int MAIL_DLSIZE_100_KB = 8;
   public static final int MAIL_DLSIZE_10_KB = 5;
   public static final int MAIL_DLSIZE_1_KB = 2;
   public static final int MAIL_DLSIZE_20_KB = 6;
   public static final int MAIL_DLSIZE_2_KB = 3;
   public static final int MAIL_DLSIZE_50_KB = 7;
   public static final int MAIL_DLSIZE_512_CHARS = 1;
   public static final int MAIL_DLSIZE_5_KB = 4;
   public static final int MAIL_DLSIZE_MIME_102400_CHARS = 7;
   public static final int MAIL_DLSIZE_MIME_10240_CHARS = 4;
   public static final int MAIL_DLSIZE_MIME_20480_CHARS = 5;
   public static final int MAIL_DLSIZE_MIME_4096_CHARS = 1;
   public static final int MAIL_DLSIZE_MIME_51200_CHARS = 6;
   public static final int MAIL_DLSIZE_MIME_5120_CHARS = 2;
   public static final int MAIL_DLSIZE_MIME_7168_CHARS = 3;
   public static final int MAIL_DLSIZE_MIME_NEVER_TURNCATE = 8;
   public static final int MAIL_DLSIZE_MIME_ONLY_TITLE = 0;
   public static final int MAIL_DLSIZE_NEVER_TRUNCATE = 9;
   public static final int MAIL_DLSIZE_ONLY_TITLE = 0;
   public static final int MAIL_DLSIZE_TEXT = 10;
   public static final int MAIL_FILTERTYPE_1_DAY = 1;
   public static final int MAIL_FILTERTYPE_1_MON = 5;
   public static final int MAIL_FILTERTYPE_1_WK = 3;
   public static final int MAIL_FILTERTYPE_2_WK = 4;
   public static final int MAIL_FILTERTYPE_3_DAY = 2;
   public static final int MAIL_FILTERTYPE_ALL = 0;
   public static final String MAIL_MEETING_FORWARD = "IPM.Schedule.Meeting.MeetingRespForward";
   public static final String MAIL_MEETING_PROPOSE_NEW_TIME = "IPM.Schedule.Meeting.proposeNewTime";
   public static final String MAIL_MESSAGE_CLASS_ACCEPT = "IPM.Schedule.Meeting.Resp.Pos";
   public static final String MAIL_MESSAGE_CLASS_CANCEL = "IPM.Schedule.Meeting.Canceled";
   public static final String MAIL_MESSAGE_CLASS_DECLINE = "IPM.Schedule.Meeting.Resp.Neg";
   public static final String MAIL_MESSAGE_CLASS_NOTIFICATION = "IPM.Notification.Meeting";
   public static final String MAIL_MESSAGE_CLASS_REQUEST = "IPM.Schedule.Meeting.Request";
   public static final String MAIL_MESSAGE_CLASS_TENTATIVE = "IPM.Schedule.Meeting.Resp.Tent";
   public static final int MAX_ACCOUNT_SIZE = 15;
   public static final String MEETING_RESP_ACCEPTED = "1";
   public static final String MEETING_RESP_DECLINED = "3";
   public static final String MEETING_RESP_FORWARD = "4";
   public static final String MEETING_RESP_PROPOSE_NEW_TIME = "5";
   public static final String MEETING_RESP_TENTATIVE_ACCEPTED = "2";
   public static final String PROTOCOL_12_0 = "12.0";
   public static final String PROTOCOL_12_1 = "12.1";
   public static final String PROTOCOL_2_0 = "2.0";
   public static final String PROTOCOL_2_5 = "2.5";
   public static final String PROTOCOL_UNKNOWN = "Unknown";
   public static final int SYNCSRC_ALL = 0;
   public static final int SYNCSRC_CALENDAR = 2;
   public static final int SYNCSRC_CONTACTS = 1;
   public static final int SYNCSRC_EMAIL = 3;
   public static final int SYNCSRC_NONE = 254;
   public static final int SYNCSRC_TASK = 4;
   public static final int SYNCSRC_UNKNOWN = 255;
   public static final int SYNC_CANCEL = 255;
   public static final int SYNC_FALED = 1;
   public static final int SYNC_OK = 0;
   public static final int SYNC_SCHEDULE_10_MIN = 3;
   public static final int SYNC_SCHEDULE_120_MIN = 7;
   public static final int SYNC_SCHEDULE_15_MIN = 4;
   public static final int SYNC_SCHEDULE_1_DAY = 9;
   public static final int SYNC_SCHEDULE_240_MIN = 8;
   public static final int SYNC_SCHEDULE_30_MIN = 5;
   public static final int SYNC_SCHEDULE_5_MIN = 2;
   public static final int SYNC_SCHEDULE_60_MIN = 6;
   public static final int SYNC_SCHEDULE_MANUALLY = 0;
   public static final int SYNC_SCHEDULE_PING = 1;
   public static final int USER_CANCEL = 245;
   public static final int attachmentHashId = "com.htc.eas.easservice.SDfull".hashCode();
   public static HashMap<Integer, Integer> colorMap = new HashMap();
   public static final int hashId = "com.htc.eas.easservice".hashCode();


   static {
      HashMap var0 = colorMap;
      Integer var1 = Integer.valueOf(34078792);
      Integer var2 = Integer.valueOf(-3198430);
      var0.put(var1, var2);
      HashMap var4 = colorMap;
      Integer var5 = Integer.valueOf(34078793);
      Integer var6 = Integer.valueOf(-2205827);
      var4.put(var5, var6);
      HashMap var8 = colorMap;
      Integer var9 = Integer.valueOf(34078794);
      Integer var10 = Integer.valueOf(-6469461);
      var8.put(var9, var10);
      HashMap var12 = colorMap;
      Integer var13 = Integer.valueOf(34078795);
      Integer var14 = Integer.valueOf(-9419857);
      var12.put(var13, var14);
      HashMap var16 = colorMap;
      Integer var17 = Integer.valueOf(34078796);
      Integer var18 = Integer.valueOf(-16687993);
      var16.put(var17, var18);
      HashMap var20 = colorMap;
      Integer var21 = Integer.valueOf(34078797);
      Integer var22 = Integer.valueOf(-14777720);
      var20.put(var21, var22);
      HashMap var24 = colorMap;
      Integer var25 = Integer.valueOf(34078798);
      Integer var26 = Integer.valueOf(-14572677);
      var24.put(var25, var26);
      HashMap var28 = colorMap;
      Integer var29 = Integer.valueOf(34078799);
      Integer var30 = Integer.valueOf(-14247124);
      var28.put(var29, var30);
      HashMap var32 = colorMap;
      Integer var33 = Integer.valueOf(34078800);
      Integer var34 = Integer.valueOf(-12022556);
      var32.put(var33, var34);
      HashMap var36 = colorMap;
      Integer var37 = Integer.valueOf(34078801);
      Integer var38 = Integer.valueOf(-8869641);
      var36.put(var37, var38);
      HashMap var40 = colorMap;
      Integer var41 = Integer.valueOf(34078802);
      Integer var42 = Integer.valueOf(-4748821);
      var40.put(var41, var42);
      HashMap var44 = colorMap;
      Integer var45 = Integer.valueOf(34078803);
      Integer var46 = Integer.valueOf(-935678);
      var44.put(var45, var46);
      HashMap var48 = colorMap;
      Integer var49 = Integer.valueOf(34078804);
      Integer var50 = Integer.valueOf(-159732);
      var48.put(var49, var50);
      HashMap var52 = colorMap;
      Integer var53 = Integer.valueOf(34078805);
      Integer var54 = Integer.valueOf(-1677556);
      var52.put(var53, var54);
      HashMap var56 = colorMap;
      Integer var57 = Integer.valueOf(34078806);
      Integer var58 = Integer.valueOf(-3971504);
      var56.put(var57, var58);
      HashMap var60 = colorMap;
      Integer var61 = Integer.valueOf(34078807);
      Integer var62 = Integer.valueOf(-9417893);
      var60.put(var61, var62);
      HashMap var64 = colorMap;
      Integer var65 = Integer.valueOf(34078808);
      Integer var66 = Integer.valueOf(-13416077);
      var64.put(var65, var66);
      HashMap var68 = colorMap;
      Integer var69 = Integer.valueOf(34078809);
      Integer var70 = Integer.valueOf(-10200183);
      var68.put(var69, var70);
      HashMap var72 = colorMap;
      Integer var73 = Integer.valueOf(34078810);
      Integer var74 = Integer.valueOf(-16215719);
      var72.put(var73, var74);
      HashMap var76 = colorMap;
      Integer var77 = Integer.valueOf(34078811);
      Integer var78 = Integer.valueOf(-8097011);
      var76.put(var77, var78);
      HashMap var80 = colorMap;
      Integer var81 = Integer.valueOf(34078812);
      Integer var82 = Integer.valueOf(-3828424);
      var80.put(var81, var82);
   }

   public EASCommon() {}

   public static class DeviceInformation implements Serializable {

      public String IMEI;
      public String OS;
      public String OSLanguage;
      public String PhoneNumber;
      public String friendlyName;
      public String model;


      public DeviceInformation() {}
   }

   public static class CertificateError implements Serializable {

      public X509Certificate certificate;
      public int errorCode;


      public CertificateError() {}
   }
}
