package myorg.bouncycastle.asn1.sec;

import myorg.bouncycastle.asn1.DERObjectIdentifier;
import myorg.bouncycastle.asn1.x9.X9ObjectIdentifiers;

public interface SECObjectIdentifiers {

   DERObjectIdentifier ellipticCurve = new DERObjectIdentifier("1.3.132.0");
   DERObjectIdentifier secp112r1;
   DERObjectIdentifier secp112r2;
   DERObjectIdentifier secp128r1;
   DERObjectIdentifier secp128r2;
   DERObjectIdentifier secp160k1;
   DERObjectIdentifier secp160r1;
   DERObjectIdentifier secp160r2;
   DERObjectIdentifier secp192k1;
   DERObjectIdentifier secp192r1;
   DERObjectIdentifier secp224k1;
   DERObjectIdentifier secp224r1;
   DERObjectIdentifier secp256k1;
   DERObjectIdentifier secp256r1;
   DERObjectIdentifier secp384r1;
   DERObjectIdentifier secp521r1;
   DERObjectIdentifier sect113r1;
   DERObjectIdentifier sect113r2;
   DERObjectIdentifier sect131r1;
   DERObjectIdentifier sect131r2;
   DERObjectIdentifier sect163k1;
   DERObjectIdentifier sect163r1;
   DERObjectIdentifier sect163r2;
   DERObjectIdentifier sect193r1;
   DERObjectIdentifier sect193r2;
   DERObjectIdentifier sect233k1;
   DERObjectIdentifier sect233r1;
   DERObjectIdentifier sect239k1;
   DERObjectIdentifier sect283k1;
   DERObjectIdentifier sect283r1;
   DERObjectIdentifier sect409k1;
   DERObjectIdentifier sect409r1;
   DERObjectIdentifier sect571k1;
   DERObjectIdentifier sect571r1;


   static {
      StringBuilder var0 = new StringBuilder();
      DERObjectIdentifier var1 = ellipticCurve;
      String var2 = var0.append(var1).append(".1").toString();
      sect163k1 = new DERObjectIdentifier(var2);
      StringBuilder var3 = new StringBuilder();
      DERObjectIdentifier var4 = ellipticCurve;
      String var5 = var3.append(var4).append(".2").toString();
      sect163r1 = new DERObjectIdentifier(var5);
      StringBuilder var6 = new StringBuilder();
      DERObjectIdentifier var7 = ellipticCurve;
      String var8 = var6.append(var7).append(".3").toString();
      sect239k1 = new DERObjectIdentifier(var8);
      StringBuilder var9 = new StringBuilder();
      DERObjectIdentifier var10 = ellipticCurve;
      String var11 = var9.append(var10).append(".4").toString();
      sect113r1 = new DERObjectIdentifier(var11);
      StringBuilder var12 = new StringBuilder();
      DERObjectIdentifier var13 = ellipticCurve;
      String var14 = var12.append(var13).append(".5").toString();
      sect113r2 = new DERObjectIdentifier(var14);
      StringBuilder var15 = new StringBuilder();
      DERObjectIdentifier var16 = ellipticCurve;
      String var17 = var15.append(var16).append(".6").toString();
      secp112r1 = new DERObjectIdentifier(var17);
      StringBuilder var18 = new StringBuilder();
      DERObjectIdentifier var19 = ellipticCurve;
      String var20 = var18.append(var19).append(".7").toString();
      secp112r2 = new DERObjectIdentifier(var20);
      StringBuilder var21 = new StringBuilder();
      DERObjectIdentifier var22 = ellipticCurve;
      String var23 = var21.append(var22).append(".8").toString();
      secp160r1 = new DERObjectIdentifier(var23);
      StringBuilder var24 = new StringBuilder();
      DERObjectIdentifier var25 = ellipticCurve;
      String var26 = var24.append(var25).append(".9").toString();
      secp160k1 = new DERObjectIdentifier(var26);
      StringBuilder var27 = new StringBuilder();
      DERObjectIdentifier var28 = ellipticCurve;
      String var29 = var27.append(var28).append(".10").toString();
      secp256k1 = new DERObjectIdentifier(var29);
      StringBuilder var30 = new StringBuilder();
      DERObjectIdentifier var31 = ellipticCurve;
      String var32 = var30.append(var31).append(".15").toString();
      sect163r2 = new DERObjectIdentifier(var32);
      StringBuilder var33 = new StringBuilder();
      DERObjectIdentifier var34 = ellipticCurve;
      String var35 = var33.append(var34).append(".16").toString();
      sect283k1 = new DERObjectIdentifier(var35);
      StringBuilder var36 = new StringBuilder();
      DERObjectIdentifier var37 = ellipticCurve;
      String var38 = var36.append(var37).append(".17").toString();
      sect283r1 = new DERObjectIdentifier(var38);
      StringBuilder var39 = new StringBuilder();
      DERObjectIdentifier var40 = ellipticCurve;
      String var41 = var39.append(var40).append(".22").toString();
      sect131r1 = new DERObjectIdentifier(var41);
      StringBuilder var42 = new StringBuilder();
      DERObjectIdentifier var43 = ellipticCurve;
      String var44 = var42.append(var43).append(".23").toString();
      sect131r2 = new DERObjectIdentifier(var44);
      StringBuilder var45 = new StringBuilder();
      DERObjectIdentifier var46 = ellipticCurve;
      String var47 = var45.append(var46).append(".24").toString();
      sect193r1 = new DERObjectIdentifier(var47);
      StringBuilder var48 = new StringBuilder();
      DERObjectIdentifier var49 = ellipticCurve;
      String var50 = var48.append(var49).append(".25").toString();
      sect193r2 = new DERObjectIdentifier(var50);
      StringBuilder var51 = new StringBuilder();
      DERObjectIdentifier var52 = ellipticCurve;
      String var53 = var51.append(var52).append(".26").toString();
      sect233k1 = new DERObjectIdentifier(var53);
      StringBuilder var54 = new StringBuilder();
      DERObjectIdentifier var55 = ellipticCurve;
      String var56 = var54.append(var55).append(".27").toString();
      sect233r1 = new DERObjectIdentifier(var56);
      StringBuilder var57 = new StringBuilder();
      DERObjectIdentifier var58 = ellipticCurve;
      String var59 = var57.append(var58).append(".28").toString();
      secp128r1 = new DERObjectIdentifier(var59);
      StringBuilder var60 = new StringBuilder();
      DERObjectIdentifier var61 = ellipticCurve;
      String var62 = var60.append(var61).append(".29").toString();
      secp128r2 = new DERObjectIdentifier(var62);
      StringBuilder var63 = new StringBuilder();
      DERObjectIdentifier var64 = ellipticCurve;
      String var65 = var63.append(var64).append(".30").toString();
      secp160r2 = new DERObjectIdentifier(var65);
      StringBuilder var66 = new StringBuilder();
      DERObjectIdentifier var67 = ellipticCurve;
      String var68 = var66.append(var67).append(".31").toString();
      secp192k1 = new DERObjectIdentifier(var68);
      StringBuilder var69 = new StringBuilder();
      DERObjectIdentifier var70 = ellipticCurve;
      String var71 = var69.append(var70).append(".32").toString();
      secp224k1 = new DERObjectIdentifier(var71);
      StringBuilder var72 = new StringBuilder();
      DERObjectIdentifier var73 = ellipticCurve;
      String var74 = var72.append(var73).append(".33").toString();
      secp224r1 = new DERObjectIdentifier(var74);
      StringBuilder var75 = new StringBuilder();
      DERObjectIdentifier var76 = ellipticCurve;
      String var77 = var75.append(var76).append(".34").toString();
      secp384r1 = new DERObjectIdentifier(var77);
      StringBuilder var78 = new StringBuilder();
      DERObjectIdentifier var79 = ellipticCurve;
      String var80 = var78.append(var79).append(".35").toString();
      secp521r1 = new DERObjectIdentifier(var80);
      StringBuilder var81 = new StringBuilder();
      DERObjectIdentifier var82 = ellipticCurve;
      String var83 = var81.append(var82).append(".36").toString();
      sect409k1 = new DERObjectIdentifier(var83);
      StringBuilder var84 = new StringBuilder();
      DERObjectIdentifier var85 = ellipticCurve;
      String var86 = var84.append(var85).append(".37").toString();
      sect409r1 = new DERObjectIdentifier(var86);
      StringBuilder var87 = new StringBuilder();
      DERObjectIdentifier var88 = ellipticCurve;
      String var89 = var87.append(var88).append(".38").toString();
      sect571k1 = new DERObjectIdentifier(var89);
      StringBuilder var90 = new StringBuilder();
      DERObjectIdentifier var91 = ellipticCurve;
      String var92 = var90.append(var91).append(".39").toString();
      sect571r1 = new DERObjectIdentifier(var92);
      secp192r1 = X9ObjectIdentifiers.prime192v1;
      secp256r1 = X9ObjectIdentifiers.prime256v1;
   }
}
