package com.android.email.service;


public interface EmailServiceStatus {

   int ACCOUNT_MOVE_SUCCESS = 2;
   int ACCOUNT_UNINITIALIZED = 24;
   int ATTACHMENT_NOT_FOUND = 17;
   int CONNECTION_ERROR = 32;
   int CONNECTION_ERROR_PROGRESS = 224;
   int CREDENTIALS_REQUIRED = 25;
   int CUSTOM_ERROR_BASE = 255;
   int DEVICE_BLOCKED = 3;
   int DEVICE_QUARANTINED = 4;
   int ERROR_EMPTYTRASH_FAILURE = 131072;
   int ERROR_EMPTYTRASH_RESPONSE_PARSE = 65536;
   int ERROR_EMPTYTRASH_TIMEOUT = 393216;
   int ERROR_FETCH_FAILURE = 262144;
   int ERROR_FETCH_NULLMSG = 458752;
   int ERROR_FETCH_OUTOFMEMORY = 327680;
   int ERROR_FETCH_RESPONSE_PARSE = 196608;
   int ERROR_FOLDER_EXISTS = 37;
   int ERROR_FOLDER_NOT_EXIST = 36;
   int ERROR_FOLDER_PARENT_NOT_FOUND = 38;
   int ERROR_GAL_INVALID_RANGE = 250;
   int ERROR_GAL_NULL_STRING = 252;
   int ERROR_GAL_RESPONSE_PARSE = 251;
   int ERROR_IRM_REMOVE = 39;
   int ERROR_ITEM = 33;
   int ERROR_ITEMOPERATION_RESPONSE_PARSER = 524288;
   int ERROR_LOAD_ATTACHMENT_FILE_TOO_LARGE = 1179648;
   int ERROR_MOVE_OUTOFMEMORY = 589824;
   int ERROR_NO_PROTOCOL_SUPPORT = 254;
   int ERROR_OOO_GET_ERROR = 248;
   int ERROR_OOO_RESPONSE_PARSE = 247;
   int ERROR_OOO_SET_ERROR = 249;
   int ERROR_SERVER_CONNECT = 253;
   int ERROR_SERVER_ERROR = 34;
   int ERROR_SYSTEM_FOLDER = 35;
   int FOLDER_NOT_CREATED = 20;
   int FOLDER_NOT_DELETED = 18;
   int FOLDER_NOT_RENAMED = 19;
   int IN_PROGRESS = 1;
   int IRM_DEFAULT_CODE = 255;
   int IRM_FEATURE_DISABLED_STATUS = 168;
   int IRM_INVALID_TEPLATEID_STATUS = 171;
   int IRM_OPERATION_NOT_PERMITTED_STATUS = 172;
   int IRM_PERMANENT_ERROR_STATUS = 170;
   int IRM_TRANSIENT_ERROR_STATUS = 169;
   int LOADMORE_CANCEL = 1048576;
   int LOGIN_FAILED = 22;
   int MESSAGE_NOT_FOUND = 16;
   int REMOTE_EXCEPTION = 21;
   int SECURITY_FAILURE = 23;
   int SUCCESS;

}
