package myorg.bouncycastle.jce.provider;

import java.security.AccessController;
import java.security.PrivilegedAction;
import java.security.Provider;
import java.util.Iterator;
import java.util.Map;
import myorg.bouncycastle.asn1.DERObjectIdentifier;
import myorg.bouncycastle.asn1.bc.BCObjectIdentifiers;
import myorg.bouncycastle.asn1.cryptopro.CryptoProObjectIdentifiers;
import myorg.bouncycastle.asn1.iana.IANAObjectIdentifiers;
import myorg.bouncycastle.asn1.nist.NISTObjectIdentifiers;
import myorg.bouncycastle.asn1.oiw.OIWObjectIdentifiers;
import myorg.bouncycastle.asn1.pkcs.PKCSObjectIdentifiers;
import myorg.bouncycastle.asn1.teletrust.TeleTrusTObjectIdentifiers;
import myorg.bouncycastle.jce.interfaces.ConfigurableProvider;
import myorg.bouncycastle.jce.provider.ProviderUtil;

public final class BouncyCastleProvider extends Provider implements ConfigurableProvider {

   private static final String[] ASYMMETRIC_CIPHERS;
   private static final String ASYMMETRIC_CIPHER_PACKAGE = "myorg.bouncycastle.jce.provider.asymmetric.";
   public static String PROVIDER_NAME = "myBC";
   private static final String[] SYMMETRIC_CIPHERS;
   private static final String SYMMETRIC_CIPHER_PACKAGE = "myorg.bouncycastle.jce.provider.symmetric.";
   private static String info = "BouncyCastle Security Provider v1.45";


   static {
      String[] var0 = new String[]{"AES", "Camellia", "CAST5", "Grainv1", "Grain128", "IDEA", "Noekeon", "SEED"};
      SYMMETRIC_CIPHERS = var0;
      String[] var1 = new String[]{"EC"};
      ASYMMETRIC_CIPHERS = var1;
   }

   public BouncyCastleProvider() {
      String var1 = PROVIDER_NAME;
      String var2 = info;
      super(var1, 1.45D, var2);
      Object var3 = AccessController.doPrivileged(new BouncyCastleProvider.1());
   }

   private void addHMACAlgorithm(String var1, String var2, String var3) {
      String var4 = "HMAC" + var1;
      String var5 = "Mac." + var4;
      this.put(var5, var2);
      String var7 = "Alg.Alias.Mac.HMAC-" + var1;
      this.put(var7, var4);
      String var9 = "Alg.Alias.Mac.HMAC/" + var1;
      this.put(var9, var4);
      String var11 = "KeyGenerator." + var4;
      this.put(var11, var3);
      String var13 = "Alg.Alias.KeyGenerator.HMAC-" + var1;
      this.put(var13, var4);
      String var15 = "Alg.Alias.KeyGenerator.HMAC/" + var1;
      this.put(var15, var4);
   }

   private void addHMACAlias(String var1, DERObjectIdentifier var2) {
      String var3 = "HMAC" + var1;
      String var4 = "Alg.Alias.Mac." + var2;
      this.put(var4, var3);
      String var6 = "Alg.Alias.KeyGenerator." + var2;
      this.put(var6, var3);
   }

   private void addMacAlgorithms() {
      Object var1 = this.put("Mac.DESMAC", "myorg.bouncycastle.jce.provider.JCEMac$DES");
      Object var2 = this.put("Alg.Alias.Mac.DES", "DESMAC");
      Object var3 = this.put("Mac.DESMAC/CFB8", "myorg.bouncycastle.jce.provider.JCEMac$DESCFB8");
      Object var4 = this.put("Alg.Alias.Mac.DES/CFB8", "DESMAC/CFB8");
      Object var5 = this.put("Mac.DESEDEMAC", "myorg.bouncycastle.jce.provider.JCEMac$DESede");
      Object var6 = this.put("Alg.Alias.Mac.DESEDE", "DESEDEMAC");
      Object var7 = this.put("Mac.DESEDEMAC/CFB8", "myorg.bouncycastle.jce.provider.JCEMac$DESedeCFB8");
      Object var8 = this.put("Alg.Alias.Mac.DESEDE/CFB8", "DESEDEMAC/CFB8");
      Object var9 = this.put("Mac.DESWITHISO9797", "myorg.bouncycastle.jce.provider.JCEMac$DES9797Alg3");
      Object var10 = this.put("Alg.Alias.Mac.DESISO9797MAC", "DESWITHISO9797");
      Object var11 = this.put("Mac.DESEDEMAC64", "myorg.bouncycastle.jce.provider.JCEMac$DESede64");
      Object var12 = this.put("Alg.Alias.Mac.DESEDE64", "DESEDEMAC64");
      Object var13 = this.put("Mac.DESEDEMAC64WITHISO7816-4PADDING", "myorg.bouncycastle.jce.provider.JCEMac$DESede64with7816d4");
      Object var14 = this.put("Alg.Alias.Mac.DESEDE64WITHISO7816-4PADDING", "DESEDEMAC64WITHISO7816-4PADDING");
      Object var15 = this.put("Alg.Alias.Mac.DESEDEISO9797ALG1MACWITHISO7816-4PADDING", "DESEDEMAC64WITHISO7816-4PADDING");
      Object var16 = this.put("Alg.Alias.Mac.DESEDEISO9797ALG1WITHISO7816-4PADDING", "DESEDEMAC64WITHISO7816-4PADDING");
      Object var17 = this.put("Mac.ISO9797ALG3MAC", "myorg.bouncycastle.jce.provider.JCEMac$DES9797Alg3");
      Object var18 = this.put("Alg.Alias.Mac.ISO9797ALG3", "ISO9797ALG3MAC");
      Object var19 = this.put("Mac.ISO9797ALG3WITHISO7816-4PADDING", "myorg.bouncycastle.jce.provider.JCEMac$DES9797Alg3with7816d4");
      Object var20 = this.put("Alg.Alias.Mac.ISO9797ALG3MACWITHISO7816-4PADDING", "ISO9797ALG3WITHISO7816-4PADDING");
      Object var21 = this.put("Mac.SKIPJACKMAC", "myorg.bouncycastle.jce.provider.JCEMac$Skipjack");
      Object var22 = this.put("Alg.Alias.Mac.SKIPJACK", "SKIPJACKMAC");
      Object var23 = this.put("Mac.SKIPJACKMAC/CFB8", "myorg.bouncycastle.jce.provider.JCEMac$SkipjackCFB8");
      Object var24 = this.put("Alg.Alias.Mac.SKIPJACK/CFB8", "SKIPJACKMAC/CFB8");
      Object var25 = this.put("Mac.RC2MAC", "myorg.bouncycastle.jce.provider.JCEMac$RC2");
      Object var26 = this.put("Alg.Alias.Mac.RC2", "RC2MAC");
      Object var27 = this.put("Mac.RC2MAC/CFB8", "myorg.bouncycastle.jce.provider.JCEMac$RC2CFB8");
      Object var28 = this.put("Alg.Alias.Mac.RC2/CFB8", "RC2MAC/CFB8");
      Object var29 = this.put("Mac.RC5MAC", "myorg.bouncycastle.jce.provider.JCEMac$RC5");
      Object var30 = this.put("Alg.Alias.Mac.RC5", "RC5MAC");
      Object var31 = this.put("Mac.RC5MAC/CFB8", "myorg.bouncycastle.jce.provider.JCEMac$RC5CFB8");
      Object var32 = this.put("Alg.Alias.Mac.RC5/CFB8", "RC5MAC/CFB8");
      Object var33 = this.put("Mac.GOST28147MAC", "myorg.bouncycastle.jce.provider.JCEMac$GOST28147");
      Object var34 = this.put("Alg.Alias.Mac.GOST28147", "GOST28147MAC");
      Object var35 = this.put("Mac.VMPCMAC", "myorg.bouncycastle.jce.provider.JCEMac$VMPC");
      Object var36 = this.put("Alg.Alias.Mac.VMPC", "VMPCMAC");
      Object var37 = this.put("Alg.Alias.Mac.VMPC-MAC", "VMPCMAC");
      Object var38 = this.put("Mac.OLDHMACSHA384", "myorg.bouncycastle.jce.provider.JCEMac$OldSHA384");
      Object var39 = this.put("Mac.OLDHMACSHA512", "myorg.bouncycastle.jce.provider.JCEMac$OldSHA512");
      this.addHMACAlgorithm("MD2", "myorg.bouncycastle.jce.provider.JCEMac$MD2", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$MD2HMAC");
      this.addHMACAlgorithm("MD4", "myorg.bouncycastle.jce.provider.JCEMac$MD4", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$MD4HMAC");
      this.addHMACAlgorithm("MD5", "myorg.bouncycastle.jce.provider.JCEMac$MD5", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$MD5HMAC");
      DERObjectIdentifier var40 = IANAObjectIdentifiers.hmacMD5;
      this.addHMACAlias("MD5", var40);
      this.addHMACAlgorithm("SHA1", "myorg.bouncycastle.jce.provider.JCEMac$SHA1", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$HMACSHA1");
      DERObjectIdentifier var41 = PKCSObjectIdentifiers.id_hmacWithSHA1;
      this.addHMACAlias("SHA1", var41);
      DERObjectIdentifier var42 = IANAObjectIdentifiers.hmacSHA1;
      this.addHMACAlias("SHA1", var42);
      this.addHMACAlgorithm("SHA224", "myorg.bouncycastle.jce.provider.JCEMac$SHA224", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$HMACSHA224");
      DERObjectIdentifier var43 = PKCSObjectIdentifiers.id_hmacWithSHA224;
      this.addHMACAlias("SHA224", var43);
      this.addHMACAlgorithm("SHA256", "myorg.bouncycastle.jce.provider.JCEMac$SHA256", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$HMACSHA256");
      DERObjectIdentifier var44 = PKCSObjectIdentifiers.id_hmacWithSHA256;
      this.addHMACAlias("SHA256", var44);
      this.addHMACAlgorithm("SHA384", "myorg.bouncycastle.jce.provider.JCEMac$SHA384", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$HMACSHA384");
      DERObjectIdentifier var45 = PKCSObjectIdentifiers.id_hmacWithSHA384;
      this.addHMACAlias("SHA384", var45);
      this.addHMACAlgorithm("SHA512", "myorg.bouncycastle.jce.provider.JCEMac$SHA512", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$HMACSHA512");
      DERObjectIdentifier var46 = PKCSObjectIdentifiers.id_hmacWithSHA512;
      this.addHMACAlias("SHA512", var46);
      this.addHMACAlgorithm("RIPEMD128", "myorg.bouncycastle.jce.provider.JCEMac$RIPEMD128", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$RIPEMD128HMAC");
      this.addHMACAlgorithm("RIPEMD160", "myorg.bouncycastle.jce.provider.JCEMac$RIPEMD160", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$RIPEMD160HMAC");
      DERObjectIdentifier var47 = IANAObjectIdentifiers.hmacRIPEMD160;
      this.addHMACAlias("RIPEMD160", var47);
      this.addHMACAlgorithm("TIGER", "myorg.bouncycastle.jce.provider.JCEMac$Tiger", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$HMACTIGER");
      DERObjectIdentifier var48 = IANAObjectIdentifiers.hmacTIGER;
      this.addHMACAlias("TIGER", var48);
      Object var49 = this.put("Mac.PBEWITHHMACSHA", "myorg.bouncycastle.jce.provider.JCEMac$PBEWithSHA");
      Object var50 = this.put("Mac.PBEWITHHMACSHA1", "myorg.bouncycastle.jce.provider.JCEMac$PBEWithSHA");
      Object var51 = this.put("Mac.PBEWITHHMACRIPEMD160", "myorg.bouncycastle.jce.provider.JCEMac$PBEWithRIPEMD160");
      Object var52 = this.put("Alg.Alias.Mac.1.3.14.3.2.26", "PBEWITHHMACSHA");
   }

   private void addMappings(Map var1) {
      Iterator var2 = var1.keySet().iterator();

      while(var2.hasNext()) {
         Object var3 = var2.next();
         if(this.containsKey(var3)) {
            StringBuilder var4 = (new StringBuilder()).append("duplicate provider key (").append(var3).append(") found in ");
            String var5 = var1.getClass().getName();
            String var6 = var4.append(var5).toString();
            throw new IllegalStateException(var6);
         }

         Object var7 = var1.get(var3);
         this.put(var3, var7);
      }

   }

   private void addMessageDigestAlgorithms() {
      Object var1 = this.put("MessageDigest.SHA-1", "myorg.bouncycastle.jce.provider.JDKMessageDigest$SHA1");
      Object var2 = this.put("Alg.Alias.MessageDigest.SHA1", "SHA-1");
      Object var3 = this.put("Alg.Alias.MessageDigest.SHA", "SHA-1");
      StringBuilder var4 = (new StringBuilder()).append("Alg.Alias.MessageDigest.");
      DERObjectIdentifier var5 = OIWObjectIdentifiers.idSHA1;
      String var6 = var4.append(var5).toString();
      this.put(var6, "SHA-1");
      Object var8 = this.put("MessageDigest.SHA-224", "myorg.bouncycastle.jce.provider.JDKMessageDigest$SHA224");
      Object var9 = this.put("Alg.Alias.MessageDigest.SHA224", "SHA-224");
      StringBuilder var10 = (new StringBuilder()).append("Alg.Alias.MessageDigest.");
      DERObjectIdentifier var11 = NISTObjectIdentifiers.id_sha224;
      String var12 = var10.append(var11).toString();
      this.put(var12, "SHA-224");
      Object var14 = this.put("MessageDigest.SHA-256", "myorg.bouncycastle.jce.provider.JDKMessageDigest$SHA256");
      Object var15 = this.put("Alg.Alias.MessageDigest.SHA256", "SHA-256");
      StringBuilder var16 = (new StringBuilder()).append("Alg.Alias.MessageDigest.");
      DERObjectIdentifier var17 = NISTObjectIdentifiers.id_sha256;
      String var18 = var16.append(var17).toString();
      this.put(var18, "SHA-256");
      Object var20 = this.put("MessageDigest.SHA-384", "myorg.bouncycastle.jce.provider.JDKMessageDigest$SHA384");
      Object var21 = this.put("Alg.Alias.MessageDigest.SHA384", "SHA-384");
      StringBuilder var22 = (new StringBuilder()).append("Alg.Alias.MessageDigest.");
      DERObjectIdentifier var23 = NISTObjectIdentifiers.id_sha384;
      String var24 = var22.append(var23).toString();
      this.put(var24, "SHA-384");
      Object var26 = this.put("MessageDigest.SHA-512", "myorg.bouncycastle.jce.provider.JDKMessageDigest$SHA512");
      Object var27 = this.put("Alg.Alias.MessageDigest.SHA512", "SHA-512");
      StringBuilder var28 = (new StringBuilder()).append("Alg.Alias.MessageDigest.");
      DERObjectIdentifier var29 = NISTObjectIdentifiers.id_sha512;
      String var30 = var28.append(var29).toString();
      this.put(var30, "SHA-512");
      Object var32 = this.put("MessageDigest.MD2", "myorg.bouncycastle.jce.provider.JDKMessageDigest$MD2");
      StringBuilder var33 = (new StringBuilder()).append("Alg.Alias.MessageDigest.");
      DERObjectIdentifier var34 = PKCSObjectIdentifiers.md2;
      String var35 = var33.append(var34).toString();
      this.put(var35, "MD2");
      Object var37 = this.put("MessageDigest.MD4", "myorg.bouncycastle.jce.provider.JDKMessageDigest$MD4");
      StringBuilder var38 = (new StringBuilder()).append("Alg.Alias.MessageDigest.");
      DERObjectIdentifier var39 = PKCSObjectIdentifiers.md4;
      String var40 = var38.append(var39).toString();
      this.put(var40, "MD4");
      Object var42 = this.put("MessageDigest.MD5", "myorg.bouncycastle.jce.provider.JDKMessageDigest$MD5");
      StringBuilder var43 = (new StringBuilder()).append("Alg.Alias.MessageDigest.");
      DERObjectIdentifier var44 = PKCSObjectIdentifiers.md5;
      String var45 = var43.append(var44).toString();
      this.put(var45, "MD5");
      Object var47 = this.put("MessageDigest.RIPEMD128", "myorg.bouncycastle.jce.provider.JDKMessageDigest$RIPEMD128");
      StringBuilder var48 = (new StringBuilder()).append("Alg.Alias.MessageDigest.");
      DERObjectIdentifier var49 = TeleTrusTObjectIdentifiers.ripemd128;
      String var50 = var48.append(var49).toString();
      this.put(var50, "RIPEMD128");
      Object var52 = this.put("MessageDigest.RIPEMD160", "myorg.bouncycastle.jce.provider.JDKMessageDigest$RIPEMD160");
      StringBuilder var53 = (new StringBuilder()).append("Alg.Alias.MessageDigest.");
      DERObjectIdentifier var54 = TeleTrusTObjectIdentifiers.ripemd160;
      String var55 = var53.append(var54).toString();
      this.put(var55, "RIPEMD160");
      Object var57 = this.put("MessageDigest.RIPEMD256", "myorg.bouncycastle.jce.provider.JDKMessageDigest$RIPEMD256");
      StringBuilder var58 = (new StringBuilder()).append("Alg.Alias.MessageDigest.");
      DERObjectIdentifier var59 = TeleTrusTObjectIdentifiers.ripemd256;
      String var60 = var58.append(var59).toString();
      this.put(var60, "RIPEMD256");
      Object var62 = this.put("MessageDigest.RIPEMD320", "myorg.bouncycastle.jce.provider.JDKMessageDigest$RIPEMD320");
      Object var63 = this.put("MessageDigest.Tiger", "myorg.bouncycastle.jce.provider.JDKMessageDigest$Tiger");
      Object var64 = this.put("MessageDigest.WHIRLPOOL", "myorg.bouncycastle.jce.provider.JDKMessageDigest$Whirlpool");
      Object var65 = this.put("MessageDigest.GOST3411", "myorg.bouncycastle.jce.provider.JDKMessageDigest$GOST3411");
      Object var66 = this.put("Alg.Alias.MessageDigest.GOST", "GOST3411");
      Object var67 = this.put("Alg.Alias.MessageDigest.GOST-3411", "GOST3411");
      StringBuilder var68 = (new StringBuilder()).append("Alg.Alias.MessageDigest.");
      DERObjectIdentifier var69 = CryptoProObjectIdentifiers.gostR3411;
      String var70 = var68.append(var69).toString();
      this.put(var70, "GOST3411");
   }

   private void addSignatureAlgorithm(String var1, String var2, String var3, DERObjectIdentifier var4) {
      String var5 = var1 + "WITH" + var2;
      String var6 = var1 + "with" + var2;
      String var7 = var1 + "With" + var2;
      String var8 = var1 + "/" + var2;
      String var9 = "Signature." + var5;
      this.put(var9, var3);
      String var11 = "Alg.Alias.Signature." + var6;
      this.put(var11, var5);
      String var13 = "Alg.Alias.Signature." + var7;
      this.put(var13, var5);
      String var15 = "Alg.Alias.Signature." + var8;
      this.put(var15, var5);
      String var17 = "Alg.Alias.Signature." + var4;
      this.put(var17, var5);
      String var19 = "Alg.Alias.Signature.OID." + var4;
      this.put(var19, var5);
   }

   private void addSignatureAlgorithms() {
      Object var1 = this.put("Signature.MD2WithRSAEncryption", "myorg.bouncycastle.jce.provider.JDKDigestSignature$MD2WithRSAEncryption");
      Object var2 = this.put("Signature.MD4WithRSAEncryption", "myorg.bouncycastle.jce.provider.JDKDigestSignature$MD4WithRSAEncryption");
      Object var3 = this.put("Signature.MD5WithRSAEncryption", "myorg.bouncycastle.jce.provider.JDKDigestSignature$MD5WithRSAEncryption");
      Object var4 = this.put("Signature.SHA1WithRSAEncryption", "myorg.bouncycastle.jce.provider.JDKDigestSignature$SHA1WithRSAEncryption");
      Object var5 = this.put("Signature.SHA224WithRSAEncryption", "myorg.bouncycastle.jce.provider.JDKDigestSignature$SHA224WithRSAEncryption");
      Object var6 = this.put("Signature.SHA256WithRSAEncryption", "myorg.bouncycastle.jce.provider.JDKDigestSignature$SHA256WithRSAEncryption");
      Object var7 = this.put("Signature.SHA384WithRSAEncryption", "myorg.bouncycastle.jce.provider.JDKDigestSignature$SHA384WithRSAEncryption");
      Object var8 = this.put("Signature.SHA512WithRSAEncryption", "myorg.bouncycastle.jce.provider.JDKDigestSignature$SHA512WithRSAEncryption");
      Object var9 = this.put("Signature.RIPEMD160WithRSAEncryption", "myorg.bouncycastle.jce.provider.JDKDigestSignature$RIPEMD160WithRSAEncryption");
      Object var10 = this.put("Signature.RIPEMD128WithRSAEncryption", "myorg.bouncycastle.jce.provider.JDKDigestSignature$RIPEMD128WithRSAEncryption");
      Object var11 = this.put("Signature.RIPEMD256WithRSAEncryption", "myorg.bouncycastle.jce.provider.JDKDigestSignature$RIPEMD256WithRSAEncryption");
      Object var12 = this.put("Signature.DSA", "myorg.bouncycastle.jce.provider.JDKDSASigner$stdDSA");
      Object var13 = this.put("Signature.NONEWITHDSA", "myorg.bouncycastle.jce.provider.JDKDSASigner$noneDSA");
      Object var14 = this.put("Signature.SHA1withRSA/ISO9796-2", "myorg.bouncycastle.jce.provider.JDKISOSignature$SHA1WithRSAEncryption");
      Object var15 = this.put("Signature.MD5withRSA/ISO9796-2", "myorg.bouncycastle.jce.provider.JDKISOSignature$MD5WithRSAEncryption");
      Object var16 = this.put("Signature.RIPEMD160withRSA/ISO9796-2", "myorg.bouncycastle.jce.provider.JDKISOSignature$RIPEMD160WithRSAEncryption");
      Object var17 = this.put("Signature.RSASSA-PSS", "myorg.bouncycastle.jce.provider.JDKPSSSigner$PSSwithRSA");
      StringBuilder var18 = (new StringBuilder()).append("Signature.");
      DERObjectIdentifier var19 = PKCSObjectIdentifiers.id_RSASSA_PSS;
      String var20 = var18.append(var19).toString();
      this.put(var20, "myorg.bouncycastle.jce.provider.JDKPSSSigner$PSSwithRSA");
      Object var22 = this.put("Signature.SHA1withRSA/PSS", "myorg.bouncycastle.jce.provider.JDKPSSSigner$SHA1withRSA");
      Object var23 = this.put("Signature.SHA224withRSA/PSS", "myorg.bouncycastle.jce.provider.JDKPSSSigner$SHA224withRSA");
      Object var24 = this.put("Signature.SHA256withRSA/PSS", "myorg.bouncycastle.jce.provider.JDKPSSSigner$SHA256withRSA");
      Object var25 = this.put("Signature.SHA384withRSA/PSS", "myorg.bouncycastle.jce.provider.JDKPSSSigner$SHA384withRSA");
      Object var26 = this.put("Signature.SHA512withRSA/PSS", "myorg.bouncycastle.jce.provider.JDKPSSSigner$SHA512withRSA");
      Object var27 = this.put("Signature.RSA", "myorg.bouncycastle.jce.provider.JDKDigestSignature$noneRSA");
      Object var28 = this.put("Signature.RAWRSASSA-PSS", "myorg.bouncycastle.jce.provider.JDKPSSSigner$nonePSS");
      Object var29 = this.put("Alg.Alias.Signature.RAWDSA", "NONEWITHDSA");
      Object var30 = this.put("Alg.Alias.Signature.RAWRSA", "RSA");
      Object var31 = this.put("Alg.Alias.Signature.NONEWITHRSA", "RSA");
      Object var32 = this.put("Alg.Alias.Signature.RAWRSAPSS", "RAWRSASSA-PSS");
      Object var33 = this.put("Alg.Alias.Signature.NONEWITHRSAPSS", "RAWRSASSA-PSS");
      Object var34 = this.put("Alg.Alias.Signature.NONEWITHRSASSA-PSS", "RAWRSASSA-PSS");
      Object var35 = this.put("Alg.Alias.Signature.RSAPSS", "RSASSA-PSS");
      Object var36 = this.put("Alg.Alias.Signature.SHA1withRSAandMGF1", "SHA1withRSA/PSS");
      Object var37 = this.put("Alg.Alias.Signature.SHA224withRSAandMGF1", "SHA224withRSA/PSS");
      Object var38 = this.put("Alg.Alias.Signature.SHA256withRSAandMGF1", "SHA256withRSA/PSS");
      Object var39 = this.put("Alg.Alias.Signature.SHA384withRSAandMGF1", "SHA384withRSA/PSS");
      Object var40 = this.put("Alg.Alias.Signature.SHA512withRSAandMGF1", "SHA512withRSA/PSS");
      Object var41 = this.put("Alg.Alias.Signature.MD2withRSAEncryption", "MD2WithRSAEncryption");
      Object var42 = this.put("Alg.Alias.Signature.MD4withRSAEncryption", "MD4WithRSAEncryption");
      Object var43 = this.put("Alg.Alias.Signature.MD5withRSAEncryption", "MD5WithRSAEncryption");
      Object var44 = this.put("Alg.Alias.Signature.SHA1withRSAEncryption", "SHA1WithRSAEncryption");
      Object var45 = this.put("Alg.Alias.Signature.SHA224withRSAEncryption", "SHA224WithRSAEncryption");
      Object var46 = this.put("Alg.Alias.Signature.SHA256withRSAEncryption", "SHA256WithRSAEncryption");
      Object var47 = this.put("Alg.Alias.Signature.SHA384withRSAEncryption", "SHA384WithRSAEncryption");
      Object var48 = this.put("Alg.Alias.Signature.SHA512withRSAEncryption", "SHA512WithRSAEncryption");
      Object var49 = this.put("Alg.Alias.Signature.SHA256WithRSAEncryption", "SHA256WithRSAEncryption");
      Object var50 = this.put("Alg.Alias.Signature.SHA384WithRSAEncryption", "SHA384WithRSAEncryption");
      Object var51 = this.put("Alg.Alias.Signature.SHA512WithRSAEncryption", "SHA512WithRSAEncryption");
      Object var52 = this.put("Alg.Alias.Signature.SHA256WITHRSAENCRYPTION", "SHA256WithRSAEncryption");
      Object var53 = this.put("Alg.Alias.Signature.SHA384WITHRSAENCRYPTION", "SHA384WithRSAEncryption");
      Object var54 = this.put("Alg.Alias.Signature.SHA512WITHRSAENCRYPTION", "SHA512WithRSAEncryption");
      Object var55 = this.put("Alg.Alias.Signature.RIPEMD160withRSAEncryption", "RIPEMD160WithRSAEncryption");
      StringBuilder var56 = (new StringBuilder()).append("Alg.Alias.Signature.");
      DERObjectIdentifier var57 = PKCSObjectIdentifiers.md2WithRSAEncryption;
      String var58 = var56.append(var57).toString();
      this.put(var58, "MD2WithRSAEncryption");
      Object var60 = this.put("Alg.Alias.Signature.MD2WithRSA", "MD2WithRSAEncryption");
      Object var61 = this.put("Alg.Alias.Signature.MD2withRSA", "MD2WithRSAEncryption");
      Object var62 = this.put("Alg.Alias.Signature.MD2/RSA", "MD2WithRSAEncryption");
      Object var63 = this.put("Alg.Alias.Signature.MD5WithRSA", "MD5WithRSAEncryption");
      Object var64 = this.put("Alg.Alias.Signature.MD5withRSA", "MD5WithRSAEncryption");
      Object var65 = this.put("Alg.Alias.Signature.MD5/RSA", "MD5WithRSAEncryption");
      StringBuilder var66 = (new StringBuilder()).append("Alg.Alias.Signature.");
      DERObjectIdentifier var67 = PKCSObjectIdentifiers.md5WithRSAEncryption;
      String var68 = var66.append(var67).toString();
      this.put(var68, "MD5WithRSAEncryption");
      Object var70 = this.put("Alg.Alias.Signature.MD4WithRSA", "MD4WithRSAEncryption");
      Object var71 = this.put("Alg.Alias.Signature.MD4withRSA", "MD4WithRSAEncryption");
      Object var72 = this.put("Alg.Alias.Signature.MD4/RSA", "MD4WithRSAEncryption");
      StringBuilder var73 = (new StringBuilder()).append("Alg.Alias.Signature.");
      DERObjectIdentifier var74 = PKCSObjectIdentifiers.md4WithRSAEncryption;
      String var75 = var73.append(var74).toString();
      this.put(var75, "MD4WithRSAEncryption");
      Object var77 = this.put("Alg.Alias.Signature.SHA1WithRSA", "SHA1WithRSAEncryption");
      Object var78 = this.put("Alg.Alias.Signature.SHA1withRSA", "SHA1WithRSAEncryption");
      Object var79 = this.put("Alg.Alias.Signature.SHA224WithRSA", "SHA224WithRSAEncryption");
      Object var80 = this.put("Alg.Alias.Signature.SHA224withRSA", "SHA224WithRSAEncryption");
      Object var81 = this.put("Alg.Alias.Signature.SHA256WithRSA", "SHA256WithRSAEncryption");
      Object var82 = this.put("Alg.Alias.Signature.SHA256withRSA", "SHA256WithRSAEncryption");
      Object var83 = this.put("Alg.Alias.Signature.SHA384WithRSA", "SHA384WithRSAEncryption");
      Object var84 = this.put("Alg.Alias.Signature.SHA384withRSA", "SHA384WithRSAEncryption");
      Object var85 = this.put("Alg.Alias.Signature.SHA512WithRSA", "SHA512WithRSAEncryption");
      Object var86 = this.put("Alg.Alias.Signature.SHA512withRSA", "SHA512WithRSAEncryption");
      Object var87 = this.put("Alg.Alias.Signature.SHA1/RSA", "SHA1WithRSAEncryption");
      Object var88 = this.put("Alg.Alias.Signature.SHA-1/RSA", "SHA1WithRSAEncryption");
      StringBuilder var89 = (new StringBuilder()).append("Alg.Alias.Signature.");
      DERObjectIdentifier var90 = PKCSObjectIdentifiers.sha1WithRSAEncryption;
      String var91 = var89.append(var90).toString();
      this.put(var91, "SHA1WithRSAEncryption");
      StringBuilder var93 = (new StringBuilder()).append("Alg.Alias.Signature.");
      DERObjectIdentifier var94 = PKCSObjectIdentifiers.sha224WithRSAEncryption;
      String var95 = var93.append(var94).toString();
      this.put(var95, "SHA224WithRSAEncryption");
      StringBuilder var97 = (new StringBuilder()).append("Alg.Alias.Signature.");
      DERObjectIdentifier var98 = PKCSObjectIdentifiers.sha256WithRSAEncryption;
      String var99 = var97.append(var98).toString();
      this.put(var99, "SHA256WithRSAEncryption");
      StringBuilder var101 = (new StringBuilder()).append("Alg.Alias.Signature.");
      DERObjectIdentifier var102 = PKCSObjectIdentifiers.sha384WithRSAEncryption;
      String var103 = var101.append(var102).toString();
      this.put(var103, "SHA384WithRSAEncryption");
      StringBuilder var105 = (new StringBuilder()).append("Alg.Alias.Signature.");
      DERObjectIdentifier var106 = PKCSObjectIdentifiers.sha512WithRSAEncryption;
      String var107 = var105.append(var106).toString();
      this.put(var107, "SHA512WithRSAEncryption");
      Object var109 = this.put("Alg.Alias.Signature.1.3.14.3.2.26with1.2.840.113549.1.1.1", "SHA1WithRSAEncryption");
      Object var110 = this.put("Alg.Alias.Signature.1.3.14.3.2.26with1.2.840.113549.1.1.5", "SHA1WithRSAEncryption");
      Object var111 = this.put("Alg.Alias.Signature.1.2.840.113549.2.5with1.2.840.113549.1.1.1", "MD5WithRSAEncryption");
      Object var112 = this.put("Alg.Alias.Signature.RIPEMD160WithRSA", "RIPEMD160WithRSAEncryption");
      Object var113 = this.put("Alg.Alias.Signature.RIPEMD160withRSA", "RIPEMD160WithRSAEncryption");
      Object var114 = this.put("Alg.Alias.Signature.RIPEMD128WithRSA", "RIPEMD128WithRSAEncryption");
      Object var115 = this.put("Alg.Alias.Signature.RIPEMD128withRSA", "RIPEMD128WithRSAEncryption");
      Object var116 = this.put("Alg.Alias.Signature.RIPEMD256WithRSA", "RIPEMD256WithRSAEncryption");
      Object var117 = this.put("Alg.Alias.Signature.RIPEMD256withRSA", "RIPEMD256WithRSAEncryption");
      Object var118 = this.put("Alg.Alias.Signature.RIPEMD-160/RSA", "RIPEMD160WithRSAEncryption");
      Object var119 = this.put("Alg.Alias.Signature.RMD160withRSA", "RIPEMD160WithRSAEncryption");
      Object var120 = this.put("Alg.Alias.Signature.RMD160/RSA", "RIPEMD160WithRSAEncryption");
      Object var121 = this.put("Alg.Alias.Signature.1.3.36.3.3.1.2", "RIPEMD160WithRSAEncryption");
      Object var122 = this.put("Alg.Alias.Signature.1.3.36.3.3.1.3", "RIPEMD128WithRSAEncryption");
      Object var123 = this.put("Alg.Alias.Signature.1.3.36.3.3.1.4", "RIPEMD256WithRSAEncryption");
      StringBuilder var124 = (new StringBuilder()).append("Alg.Alias.Signature.");
      DERObjectIdentifier var125 = OIWObjectIdentifiers.sha1WithRSA;
      String var126 = var124.append(var125).toString();
      this.put(var126, "SHA1WithRSAEncryption");
      Object var128 = this.put("Alg.Alias.Signature.MD2WITHRSAENCRYPTION", "MD2WithRSAEncryption");
      Object var129 = this.put("Alg.Alias.Signature.MD5WITHRSAENCRYPTION", "MD5WithRSAEncryption");
      Object var130 = this.put("Alg.Alias.Signature.SHA1WITHRSAENCRYPTION", "SHA1WithRSAEncryption");
      Object var131 = this.put("Alg.Alias.Signature.RIPEMD160WITHRSAENCRYPTION", "RIPEMD160WithRSAEncryption");
      Object var132 = this.put("Alg.Alias.Signature.MD5WITHRSA", "MD5WithRSAEncryption");
      Object var133 = this.put("Alg.Alias.Signature.SHA1WITHRSA", "SHA1WithRSAEncryption");
      Object var134 = this.put("Alg.Alias.Signature.RIPEMD160WITHRSA", "RIPEMD160WithRSAEncryption");
      Object var135 = this.put("Alg.Alias.Signature.RMD160WITHRSA", "RIPEMD160WithRSAEncryption");
      Object var136 = this.put("Alg.Alias.Signature.RIPEMD160WITHRSA", "RIPEMD160WithRSAEncryption");
      DERObjectIdentifier var137 = NISTObjectIdentifiers.dsa_with_sha224;
      this.addSignatureAlgorithm("SHA224", "DSA", "myorg.bouncycastle.jce.provider.JDKDSASigner$dsa224", var137);
      DERObjectIdentifier var138 = NISTObjectIdentifiers.dsa_with_sha256;
      this.addSignatureAlgorithm("SHA256", "DSA", "myorg.bouncycastle.jce.provider.JDKDSASigner$dsa256", var138);
      DERObjectIdentifier var139 = NISTObjectIdentifiers.dsa_with_sha384;
      this.addSignatureAlgorithm("SHA384", "DSA", "myorg.bouncycastle.jce.provider.JDKDSASigner$dsa384", var139);
      DERObjectIdentifier var140 = NISTObjectIdentifiers.dsa_with_sha512;
      this.addSignatureAlgorithm("SHA512", "DSA", "myorg.bouncycastle.jce.provider.JDKDSASigner$dsa512", var140);
      Object var141 = this.put("Alg.Alias.Signature.SHA/DSA", "DSA");
      Object var142 = this.put("Alg.Alias.Signature.SHA1withDSA", "DSA");
      Object var143 = this.put("Alg.Alias.Signature.SHA1WITHDSA", "DSA");
      Object var144 = this.put("Alg.Alias.Signature.1.3.14.3.2.26with1.2.840.10040.4.1", "DSA");
      Object var145 = this.put("Alg.Alias.Signature.1.3.14.3.2.26with1.2.840.10040.4.3", "DSA");
      Object var146 = this.put("Alg.Alias.Signature.DSAwithSHA1", "DSA");
      Object var147 = this.put("Alg.Alias.Signature.DSAWITHSHA1", "DSA");
      Object var148 = this.put("Alg.Alias.Signature.SHA1WithDSA", "DSA");
      Object var149 = this.put("Alg.Alias.Signature.DSAWithSHA1", "DSA");
      Object var150 = this.put("Alg.Alias.Signature.1.2.840.10040.4.3", "DSA");
      Object var151 = this.put("Alg.Alias.Signature.MD5WithRSA/ISO9796-2", "MD5withRSA/ISO9796-2");
      Object var152 = this.put("Alg.Alias.Signature.SHA1WithRSA/ISO9796-2", "SHA1withRSA/ISO9796-2");
      Object var153 = this.put("Alg.Alias.Signature.RIPEMD160WithRSA/ISO9796-2", "RIPEMD160withRSA/ISO9796-2");
      Object var154 = this.put("Signature.ECGOST3410", "myorg.bouncycastle.jce.provider.JDKGOST3410Signer$ecgost3410");
      Object var155 = this.put("Alg.Alias.Signature.ECGOST-3410", "ECGOST3410");
      Object var156 = this.put("Alg.Alias.Signature.GOST-3410-2001", "ECGOST3410");
      Object var157 = this.put("Alg.Alias.Signature.GOST3411withECGOST3410", "ECGOST3410");
      Object var158 = this.put("Alg.Alias.Signature.GOST3411WITHECGOST3410", "ECGOST3410");
      Object var159 = this.put("Alg.Alias.Signature.GOST3411WithECGOST3410", "ECGOST3410");
      StringBuilder var160 = (new StringBuilder()).append("Alg.Alias.Signature.");
      DERObjectIdentifier var161 = CryptoProObjectIdentifiers.gostR3411_94_with_gostR3410_2001;
      String var162 = var160.append(var161).toString();
      this.put(var162, "ECGOST3410");
      Object var164 = this.put("Signature.GOST3410", "myorg.bouncycastle.jce.provider.JDKGOST3410Signer$gost3410");
      Object var165 = this.put("Alg.Alias.Signature.GOST-3410", "GOST3410");
      Object var166 = this.put("Alg.Alias.Signature.GOST-3410-94", "GOST3410");
      Object var167 = this.put("Alg.Alias.Signature.GOST3411withGOST3410", "GOST3410");
      Object var168 = this.put("Alg.Alias.Signature.GOST3411WITHGOST3410", "GOST3410");
      Object var169 = this.put("Alg.Alias.Signature.GOST3411WithGOST3410", "GOST3410");
      StringBuilder var170 = (new StringBuilder()).append("Alg.Alias.Signature.");
      DERObjectIdentifier var171 = CryptoProObjectIdentifiers.gostR3411_94_with_gostR3410_94;
      String var172 = var170.append(var171).toString();
      this.put(var172, "GOST3410");
   }

   private void loadAlgorithms(String var1, String[] var2) {
      int var3 = 0;

      while(true) {
         int var4 = var2.length;
         if(var3 == var4) {
            return;
         }

         Class var5 = null;

         label37: {
            Class var10;
            label36: {
               try {
                  ClassLoader var6 = this.getClass().getClassLoader();
                  if(var6 != null) {
                     StringBuilder var7 = (new StringBuilder()).append(var1);
                     String var8 = var2[var3];
                     String var9 = var7.append(var8).append("Mappings").toString();
                     var10 = var6.loadClass(var9);
                     break label36;
                  }

                  StringBuilder var12 = (new StringBuilder()).append(var1);
                  String var13 = var2[var3];
                  var10 = Class.forName(var12.append(var13).append("Mappings").toString());
               } catch (ClassNotFoundException var20) {
                  break label37;
               }

               var5 = var10;
               break label37;
            }

            var5 = var10;
         }

         if(var5 != null) {
            try {
               Map var11 = (Map)var5.newInstance();
               this.addMappings(var11);
            } catch (Exception var19) {
               StringBuilder var15 = (new StringBuilder()).append("cannot create instance of ").append(var1);
               String var16 = var2[var3];
               String var17 = var15.append(var16).append("Mappings : ").append(var19).toString();
               throw new InternalError(var17);
            }
         }

         ++var3;
      }
   }

   private void setup() {
      String[] var1 = SYMMETRIC_CIPHERS;
      this.loadAlgorithms("myorg.bouncycastle.jce.provider.symmetric.", var1);
      String[] var2 = ASYMMETRIC_CIPHERS;
      this.loadAlgorithms("myorg.bouncycastle.jce.provider.asymmetric.", var2);
      Object var3 = this.put("X509Store.CERTIFICATE/COLLECTION", "myorg.bouncycastle.jce.provider.X509StoreCertCollection");
      Object var4 = this.put("X509Store.ATTRIBUTECERTIFICATE/COLLECTION", "myorg.bouncycastle.jce.provider.X509StoreAttrCertCollection");
      Object var5 = this.put("X509Store.CRL/COLLECTION", "myorg.bouncycastle.jce.provider.X509StoreCRLCollection");
      Object var6 = this.put("X509Store.CERTIFICATEPAIR/COLLECTION", "myorg.bouncycastle.jce.provider.X509StoreCertPairCollection");
      Object var7 = this.put("X509Store.CERTIFICATE/LDAP", "myorg.bouncycastle.jce.provider.X509StoreLDAPCerts");
      Object var8 = this.put("X509Store.CRL/LDAP", "myorg.bouncycastle.jce.provider.X509StoreLDAPCRLs");
      Object var9 = this.put("X509Store.ATTRIBUTECERTIFICATE/LDAP", "myorg.bouncycastle.jce.provider.X509StoreLDAPAttrCerts");
      Object var10 = this.put("X509Store.CERTIFICATEPAIR/LDAP", "myorg.bouncycastle.jce.provider.X509StoreLDAPCertPairs");
      Object var11 = this.put("X509StreamParser.CERTIFICATE", "myorg.bouncycastle.jce.provider.X509CertParser");
      Object var12 = this.put("X509StreamParser.ATTRIBUTECERTIFICATE", "myorg.bouncycastle.jce.provider.X509AttrCertParser");
      Object var13 = this.put("X509StreamParser.CRL", "myorg.bouncycastle.jce.provider.X509CRLParser");
      Object var14 = this.put("X509StreamParser.CERTIFICATEPAIR", "myorg.bouncycastle.jce.provider.X509CertPairParser");
      Object var15 = this.put("KeyStore.BKS", "myorg.bouncycastle.jce.provider.JDKKeyStore");
      Object var16 = this.put("KeyStore.BouncyCastle", "myorg.bouncycastle.jce.provider.JDKKeyStore$BouncyCastleStore");
      Object var17 = this.put("KeyStore.PKCS12", "myorg.bouncycastle.jce.provider.JDKPKCS12KeyStore$BCPKCS12KeyStore");
      Object var18 = this.put("KeyStore.BCPKCS12", "myorg.bouncycastle.jce.provider.JDKPKCS12KeyStore$BCPKCS12KeyStore");
      Object var19 = this.put("KeyStore.PKCS12-DEF", "myorg.bouncycastle.jce.provider.JDKPKCS12KeyStore$DefPKCS12KeyStore");
      Object var20 = this.put("KeyStore.PKCS12-3DES-40RC2", "myorg.bouncycastle.jce.provider.JDKPKCS12KeyStore$BCPKCS12KeyStore");
      Object var21 = this.put("KeyStore.PKCS12-3DES-3DES", "myorg.bouncycastle.jce.provider.JDKPKCS12KeyStore$BCPKCS12KeyStore3DES");
      Object var22 = this.put("KeyStore.PKCS12-DEF-3DES-40RC2", "myorg.bouncycastle.jce.provider.JDKPKCS12KeyStore$DefPKCS12KeyStore");
      Object var23 = this.put("KeyStore.PKCS12-DEF-3DES-3DES", "myorg.bouncycastle.jce.provider.JDKPKCS12KeyStore$DefPKCS12KeyStore3DES");
      Object var24 = this.put("Alg.Alias.KeyStore.UBER", "BouncyCastle");
      Object var25 = this.put("Alg.Alias.KeyStore.BOUNCYCASTLE", "BouncyCastle");
      Object var26 = this.put("Alg.Alias.KeyStore.bouncycastle", "BouncyCastle");
      Object var27 = this.put("CertificateFactory.X.509", "myorg.bouncycastle.jce.provider.JDKX509CertificateFactory");
      Object var28 = this.put("Alg.Alias.CertificateFactory.X509", "X.509");
      Object var29 = this.put("AlgorithmParameterGenerator.DH", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameterGenerator$DH");
      Object var30 = this.put("AlgorithmParameterGenerator.DSA", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameterGenerator$DSA");
      Object var31 = this.put("AlgorithmParameterGenerator.GOST3410", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameterGenerator$GOST3410");
      Object var32 = this.put("AlgorithmParameterGenerator.ELGAMAL", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameterGenerator$ElGamal");
      Object var33 = this.put("AlgorithmParameterGenerator.DES", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameterGenerator$DES");
      Object var34 = this.put("AlgorithmParameterGenerator.DESEDE", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameterGenerator$DES");
      StringBuilder var35 = (new StringBuilder()).append("AlgorithmParameterGenerator.");
      DERObjectIdentifier var36 = PKCSObjectIdentifiers.des_EDE3_CBC;
      String var37 = var35.append(var36).toString();
      this.put(var37, "myorg.bouncycastle.jce.provider.JDKAlgorithmParameterGenerator$DES");
      StringBuilder var39 = (new StringBuilder()).append("AlgorithmParameterGenerator.");
      DERObjectIdentifier var40 = OIWObjectIdentifiers.desCBC;
      String var41 = var39.append(var40).toString();
      this.put(var41, "myorg.bouncycastle.jce.provider.JDKAlgorithmParameterGenerator$DES");
      Object var43 = this.put("AlgorithmParameterGenerator.RC2", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameterGenerator$RC2");
      Object var44 = this.put("AlgorithmParameterGenerator.1.2.840.113549.3.2", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameterGenerator$RC2");
      Object var45 = this.put("Alg.Alias.AlgorithmParameterGenerator.DIFFIEHELLMAN", "DH");
      Object var46 = this.put("Alg.Alias.AlgorithmParameterGenerator.GOST-3410", "GOST3410");
      Object var47 = this.put("AlgorithmParameters.OAEP", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$OAEP");
      Object var48 = this.put("AlgorithmParameters.PSS", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$PSS");
      Object var49 = this.put("AlgorithmParameters.DH", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$DH");
      Object var50 = this.put("Alg.Alias.AlgorithmParameters.DIFFIEHELLMAN", "DH");
      Object var51 = this.put("AlgorithmParameters.DSA", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$DSA");
      Object var52 = this.put("AlgorithmParameters.ELGAMAL", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$ElGamal");
      Object var53 = this.put("AlgorithmParameters.IES", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$IES");
      Object var54 = this.put("AlgorithmParameters.PKCS12PBE", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$PKCS12PBE");
      StringBuilder var55 = (new StringBuilder()).append("AlgorithmParameters.");
      DERObjectIdentifier var56 = PKCSObjectIdentifiers.des_EDE3_CBC;
      String var57 = var55.append(var56).toString();
      this.put(var57, "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$IVAlgorithmParameters");
      StringBuilder var59 = (new StringBuilder()).append("AlgorithmParameters.");
      DERObjectIdentifier var60 = PKCSObjectIdentifiers.id_PBKDF2;
      String var61 = var59.append(var60).toString();
      this.put(var61, "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$PBKDF2");
      Object var63 = this.put("AlgorithmParameters.GOST3410", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$GOST3410");
      Object var64 = this.put("Alg.Alias.AlgorithmParameters.GOST-3410", "GOST3410");
      Object var65 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHA1ANDRC2", "PKCS12PBE");
      Object var66 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAAND3-KEYTRIPLEDES", "PKCS12PBE");
      Object var67 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAAND2-KEYTRIPLEDES", "PKCS12PBE");
      Object var68 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAANDRC2", "PKCS12PBE");
      Object var69 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAANDRC4", "PKCS12PBE");
      Object var70 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAANDTWOFISH", "PKCS12PBE");
      Object var71 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHA1ANDRC2-CBC", "PKCS12PBE");
      Object var72 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAAND3-KEYTRIPLEDES-CBC", "PKCS12PBE");
      Object var73 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAAND2-KEYTRIPLEDES-CBC", "PKCS12PBE");
      Object var74 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAANDDES3KEY-CBC", "PKCS12PBE");
      Object var75 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAANDDES2KEY-CBC", "PKCS12PBE");
      Object var76 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAAND40BITRC2-CBC", "PKCS12PBE");
      Object var77 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAAND40BITRC4", "PKCS12PBE");
      Object var78 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAAND128BITRC2-CBC", "PKCS12PBE");
      Object var79 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAAND128BITRC4", "PKCS12PBE");
      Object var80 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAANDTWOFISH", "PKCS12PBE");
      Object var81 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAANDTWOFISH-CBC", "PKCS12PBE");
      Object var82 = this.put("Alg.Alias.AlgorithmParameters.1.2.840.113549.1.12.1.1", "PKCS12PBE");
      Object var83 = this.put("Alg.Alias.AlgorithmParameters.1.2.840.113549.1.12.1.2", "PKCS12PBE");
      Object var84 = this.put("Alg.Alias.AlgorithmParameters.1.2.840.113549.1.12.1.3", "PKCS12PBE");
      Object var85 = this.put("Alg.Alias.AlgorithmParameters.1.2.840.113549.1.12.1.4", "PKCS12PBE");
      Object var86 = this.put("Alg.Alias.AlgorithmParameters.1.2.840.113549.1.12.1.5", "PKCS12PBE");
      Object var87 = this.put("Alg.Alias.AlgorithmParameters.1.2.840.113549.1.12.1.6", "PKCS12PBE");
      Object var88 = this.put("Alg.Alias.AlgorithmParameters.PBEWithSHAAnd3KeyTripleDES", "PKCS12PBE");
      StringBuilder var89 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      String var90 = BCObjectIdentifiers.bc_pbe_sha1_pkcs12_aes128_cbc.getId();
      String var91 = var89.append(var90).toString();
      this.put(var91, "PKCS12PBE");
      StringBuilder var93 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      String var94 = BCObjectIdentifiers.bc_pbe_sha1_pkcs12_aes192_cbc.getId();
      String var95 = var93.append(var94).toString();
      this.put(var95, "PKCS12PBE");
      StringBuilder var97 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      String var98 = BCObjectIdentifiers.bc_pbe_sha1_pkcs12_aes256_cbc.getId();
      String var99 = var97.append(var98).toString();
      this.put(var99, "PKCS12PBE");
      StringBuilder var101 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      String var102 = BCObjectIdentifiers.bc_pbe_sha256_pkcs12_aes128_cbc.getId();
      String var103 = var101.append(var102).toString();
      this.put(var103, "PKCS12PBE");
      StringBuilder var105 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      String var106 = BCObjectIdentifiers.bc_pbe_sha256_pkcs12_aes192_cbc.getId();
      String var107 = var105.append(var106).toString();
      this.put(var107, "PKCS12PBE");
      StringBuilder var109 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      String var110 = BCObjectIdentifiers.bc_pbe_sha256_pkcs12_aes256_cbc.getId();
      String var111 = var109.append(var110).toString();
      this.put(var111, "PKCS12PBE");
      StringBuilder var113 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      DERObjectIdentifier var114 = PKCSObjectIdentifiers.id_RSAES_OAEP;
      String var115 = var113.append(var114).toString();
      this.put(var115, "OAEP");
      Object var117 = this.put("Alg.Alias.AlgorithmParameters.RSAPSS", "PSS");
      Object var118 = this.put("Alg.Alias.AlgorithmParameters.RSASSA-PSS", "PSS");
      StringBuilder var119 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      DERObjectIdentifier var120 = PKCSObjectIdentifiers.id_RSASSA_PSS;
      String var121 = var119.append(var120).toString();
      this.put(var121, "PSS");
      Object var123 = this.put("Alg.Alias.AlgorithmParameters.SHA1withRSA/PSS", "PSS");
      Object var124 = this.put("Alg.Alias.AlgorithmParameters.SHA224withRSA/PSS", "PSS");
      Object var125 = this.put("Alg.Alias.AlgorithmParameters.SHA256withRSA/PSS", "PSS");
      Object var126 = this.put("Alg.Alias.AlgorithmParameters.SHA384withRSA/PSS", "PSS");
      Object var127 = this.put("Alg.Alias.AlgorithmParameters.SHA512withRSA/PSS", "PSS");
      Object var128 = this.put("Alg.Alias.AlgorithmParameters.SHA1WITHRSAANDMGF1", "PSS");
      Object var129 = this.put("Alg.Alias.AlgorithmParameters.SHA224WITHRSAANDMGF1", "PSS");
      Object var130 = this.put("Alg.Alias.AlgorithmParameters.SHA256WITHRSAANDMGF1", "PSS");
      Object var131 = this.put("Alg.Alias.AlgorithmParameters.SHA384WITHRSAANDMGF1", "PSS");
      Object var132 = this.put("Alg.Alias.AlgorithmParameters.SHA512WITHRSAANDMGF1", "PSS");
      Object var133 = this.put("Alg.Alias.AlgorithmParameters.RAWRSAPSS", "PSS");
      Object var134 = this.put("Alg.Alias.AlgorithmParameters.NONEWITHRSAPSS", "PSS");
      Object var135 = this.put("Alg.Alias.AlgorithmParameters.NONEWITHRSASSA-PSS", "PSS");
      Object var136 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAAND128BITAES-CBC-BC", "PKCS12PBE");
      Object var137 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAAND192BITAES-CBC-BC", "PKCS12PBE");
      Object var138 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHAAND256BITAES-CBC-BC", "PKCS12PBE");
      Object var139 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHA256AND128BITAES-CBC-BC", "PKCS12PBE");
      Object var140 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHA256AND192BITAES-CBC-BC", "PKCS12PBE");
      Object var141 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHA256AND256BITAES-CBC-BC", "PKCS12PBE");
      Object var142 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHA1AND128BITAES-CBC-BC", "PKCS12PBE");
      Object var143 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHA1AND192BITAES-CBC-BC", "PKCS12PBE");
      Object var144 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHA1AND256BITAES-CBC-BC", "PKCS12PBE");
      Object var145 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHA-1AND128BITAES-CBC-BC", "PKCS12PBE");
      Object var146 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHA-1AND192BITAES-CBC-BC", "PKCS12PBE");
      Object var147 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHA-1AND256BITAES-CBC-BC", "PKCS12PBE");
      Object var148 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHA-256AND128BITAES-CBC-BC", "PKCS12PBE");
      Object var149 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHA-256AND192BITAES-CBC-BC", "PKCS12PBE");
      Object var150 = this.put("Alg.Alias.AlgorithmParameters.PBEWITHSHA-256AND256BITAES-CBC-BC", "PKCS12PBE");
      Object var151 = this.put("AlgorithmParameters.SHA1WITHECDSA", "myorg.bouncycastle.jce.provider.JDKECDSAAlgParameters$SigAlgParameters");
      Object var152 = this.put("AlgorithmParameters.SHA224WITHECDSA", "myorg.bouncycastle.jce.provider.JDKECDSAAlgParameters$SigAlgParameters");
      Object var153 = this.put("AlgorithmParameters.SHA256WITHECDSA", "myorg.bouncycastle.jce.provider.JDKECDSAAlgParameters$SigAlgParameters");
      Object var154 = this.put("AlgorithmParameters.SHA384WITHECDSA", "myorg.bouncycastle.jce.provider.JDKECDSAAlgParameters$SigAlgParameters");
      Object var155 = this.put("AlgorithmParameters.SHA512WITHECDSA", "myorg.bouncycastle.jce.provider.JDKECDSAAlgParameters$SigAlgParameters");
      Object var156 = this.put("KeyAgreement.DH", "myorg.bouncycastle.jce.provider.JCEDHKeyAgreement");
      Object var157 = this.put("Alg.Alias.KeyAgreement.DIFFIEHELLMAN", "DH");
      Object var158 = this.put("Cipher.DES", "myorg.bouncycastle.jce.provider.JCEBlockCipher$DES");
      Object var159 = this.put("Cipher.DESEDE", "myorg.bouncycastle.jce.provider.JCEBlockCipher$DESede");
      StringBuilder var160 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var161 = PKCSObjectIdentifiers.des_EDE3_CBC;
      String var162 = var160.append(var161).toString();
      this.put(var162, "myorg.bouncycastle.jce.provider.JCEBlockCipher$DESedeCBC");
      StringBuilder var164 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var165 = OIWObjectIdentifiers.desCBC;
      String var166 = var164.append(var165).toString();
      this.put(var166, "myorg.bouncycastle.jce.provider.JCEBlockCipher$DESCBC");
      Object var168 = this.put("Cipher.DESEDEWRAP", "myorg.bouncycastle.jce.provider.WrapCipherSpi$DESEDEWrap");
      StringBuilder var169 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var170 = PKCSObjectIdentifiers.id_alg_CMS3DESwrap;
      String var171 = var169.append(var170).toString();
      this.put(var171, "myorg.bouncycastle.jce.provider.WrapCipherSpi$DESEDEWrap");
      Object var173 = this.put("Cipher.SKIPJACK", "myorg.bouncycastle.jce.provider.JCEBlockCipher$Skipjack");
      Object var174 = this.put("Cipher.BLOWFISH", "myorg.bouncycastle.jce.provider.JCEBlockCipher$Blowfish");
      Object var175 = this.put("Cipher.1.3.6.1.4.1.3029.1.2", "myorg.bouncycastle.jce.provider.JCEBlockCipher$BlowfishCBC");
      Object var176 = this.put("Cipher.TWOFISH", "myorg.bouncycastle.jce.provider.JCEBlockCipher$Twofish");
      Object var177 = this.put("Cipher.RC2", "myorg.bouncycastle.jce.provider.JCEBlockCipher$RC2");
      Object var178 = this.put("Cipher.RC2WRAP", "myorg.bouncycastle.jce.provider.WrapCipherSpi$RC2Wrap");
      Object var179 = this.put("Cipher.1.2.840.113549.1.9.16.3.7", "myorg.bouncycastle.jce.provider.WrapCipherSpi$RC2Wrap");
      Object var180 = this.put("Cipher.ARC4", "myorg.bouncycastle.jce.provider.JCEStreamCipher$RC4");
      Object var181 = this.put("Alg.Alias.Cipher.1.2.840.113549.3.4", "ARC4");
      Object var182 = this.put("Alg.Alias.Cipher.ARCFOUR", "ARC4");
      Object var183 = this.put("Alg.Alias.Cipher.RC4", "ARC4");
      Object var184 = this.put("Cipher.SALSA20", "myorg.bouncycastle.jce.provider.JCEStreamCipher$Salsa20");
      Object var185 = this.put("Cipher.HC128", "myorg.bouncycastle.jce.provider.JCEStreamCipher$HC128");
      Object var186 = this.put("Cipher.HC256", "myorg.bouncycastle.jce.provider.JCEStreamCipher$HC256");
      Object var187 = this.put("Cipher.VMPC", "myorg.bouncycastle.jce.provider.JCEStreamCipher$VMPC");
      Object var188 = this.put("Cipher.VMPC-KSA3", "myorg.bouncycastle.jce.provider.JCEStreamCipher$VMPCKSA3");
      Object var189 = this.put("Cipher.RC5", "myorg.bouncycastle.jce.provider.JCEBlockCipher$RC5");
      Object var190 = this.put("Cipher.1.2.840.113549.3.2", "myorg.bouncycastle.jce.provider.JCEBlockCipher$RC2CBC");
      Object var191 = this.put("Alg.Alias.Cipher.RC5-32", "RC5");
      Object var192 = this.put("Cipher.RC5-64", "myorg.bouncycastle.jce.provider.JCEBlockCipher$RC564");
      Object var193 = this.put("Cipher.RC6", "myorg.bouncycastle.jce.provider.JCEBlockCipher$RC6");
      Object var194 = this.put("Cipher.RIJNDAEL", "myorg.bouncycastle.jce.provider.JCEBlockCipher$Rijndael");
      Object var195 = this.put("Cipher.DESEDERFC3211WRAP", "myorg.bouncycastle.jce.provider.WrapCipherSpi$RFC3211DESedeWrap");
      Object var196 = this.put("Cipher.SERPENT", "myorg.bouncycastle.jce.provider.JCEBlockCipher$Serpent");
      Object var197 = this.put("Cipher.CAST6", "myorg.bouncycastle.jce.provider.JCEBlockCipher$CAST6");
      Object var198 = this.put("Alg.Alias.Cipher.PBEWithSHAAnd3KeyTripleDES", "PBEWITHSHAAND3-KEYTRIPLEDES-CBC");
      Object var199 = this.put("Cipher.GOST28147", "myorg.bouncycastle.jce.provider.JCEBlockCipher$GOST28147");
      Object var200 = this.put("Alg.Alias.Cipher.GOST", "GOST28147");
      Object var201 = this.put("Alg.Alias.Cipher.GOST-28147", "GOST28147");
      StringBuilder var202 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var203 = CryptoProObjectIdentifiers.gostR28147_cbc;
      String var204 = var202.append(var203).toString();
      this.put(var204, "myorg.bouncycastle.jce.provider.JCEBlockCipher$GOST28147cbc");
      Object var206 = this.put("Cipher.TEA", "myorg.bouncycastle.jce.provider.JCEBlockCipher$TEA");
      Object var207 = this.put("Cipher.XTEA", "myorg.bouncycastle.jce.provider.JCEBlockCipher$XTEA");
      Object var208 = this.put("Cipher.RSA", "myorg.bouncycastle.jce.provider.JCERSACipher$NoPadding");
      Object var209 = this.put("Cipher.RSA/RAW", "myorg.bouncycastle.jce.provider.JCERSACipher$NoPadding");
      Object var210 = this.put("Cipher.RSA/PKCS1", "myorg.bouncycastle.jce.provider.JCERSACipher$PKCS1v1_5Padding");
      Object var211 = this.put("Cipher.1.2.840.113549.1.1.1", "myorg.bouncycastle.jce.provider.JCERSACipher$PKCS1v1_5Padding");
      Object var212 = this.put("Cipher.2.5.8.1.1", "myorg.bouncycastle.jce.provider.JCERSACipher$PKCS1v1_5Padding");
      Object var213 = this.put("Cipher.RSA/1", "myorg.bouncycastle.jce.provider.JCERSACipher$PKCS1v1_5Padding_PrivateOnly");
      Object var214 = this.put("Cipher.RSA/2", "myorg.bouncycastle.jce.provider.JCERSACipher$PKCS1v1_5Padding_PublicOnly");
      Object var215 = this.put("Cipher.RSA/OAEP", "myorg.bouncycastle.jce.provider.JCERSACipher$OAEPPadding");
      StringBuilder var216 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var217 = PKCSObjectIdentifiers.id_RSAES_OAEP;
      String var218 = var216.append(var217).toString();
      this.put(var218, "myorg.bouncycastle.jce.provider.JCERSACipher$OAEPPadding");
      Object var220 = this.put("Cipher.RSA/ISO9796-1", "myorg.bouncycastle.jce.provider.JCERSACipher$ISO9796d1Padding");
      Object var221 = this.put("Cipher.ECIES", "myorg.bouncycastle.jce.provider.JCEIESCipher$ECIES");
      Object var222 = this.put("Cipher.BrokenECIES", "myorg.bouncycastle.jce.provider.JCEIESCipher$BrokenECIES");
      Object var223 = this.put("Cipher.IES", "myorg.bouncycastle.jce.provider.JCEIESCipher$IES");
      Object var224 = this.put("Cipher.BrokenIES", "myorg.bouncycastle.jce.provider.JCEIESCipher$BrokenIES");
      Object var225 = this.put("Cipher.ELGAMAL", "myorg.bouncycastle.jce.provider.JCEElGamalCipher$NoPadding");
      Object var226 = this.put("Cipher.ELGAMAL/PKCS1", "myorg.bouncycastle.jce.provider.JCEElGamalCipher$PKCS1v1_5Padding");
      Object var227 = this.put("Alg.Alias.Cipher.RSA//RAW", "RSA");
      Object var228 = this.put("Alg.Alias.Cipher.RSA//NOPADDING", "RSA");
      Object var229 = this.put("Alg.Alias.Cipher.RSA//PKCS1PADDING", "RSA/PKCS1");
      Object var230 = this.put("Alg.Alias.Cipher.RSA//OAEPPADDING", "RSA/OAEP");
      Object var231 = this.put("Alg.Alias.Cipher.RSA//ISO9796-1PADDING", "RSA/ISO9796-1");
      Object var232 = this.put("Alg.Alias.Cipher.ELGAMAL/ECB/PKCS1PADDING", "ELGAMAL/PKCS1");
      Object var233 = this.put("Alg.Alias.Cipher.ELGAMAL/NONE/PKCS1PADDING", "ELGAMAL/PKCS1");
      Object var234 = this.put("Alg.Alias.Cipher.ELGAMAL/NONE/NOPADDING", "ELGAMAL");
      Object var235 = this.put("Cipher.PBEWITHMD5ANDDES", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithMD5AndDES");
      Object var236 = this.put("Cipher.BROKENPBEWITHMD5ANDDES", "myorg.bouncycastle.jce.provider.BrokenJCEBlockCipher$BrokePBEWithMD5AndDES");
      Object var237 = this.put("Cipher.PBEWITHMD5ANDRC2", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithMD5AndRC2");
      Object var238 = this.put("Cipher.PBEWITHSHA1ANDDES", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithSHA1AndDES");
      Object var239 = this.put("Cipher.BROKENPBEWITHSHA1ANDDES", "myorg.bouncycastle.jce.provider.BrokenJCEBlockCipher$BrokePBEWithSHA1AndDES");
      Object var240 = this.put("Cipher.PBEWITHSHA1ANDRC2", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithSHA1AndRC2");
      Object var241 = this.put("Cipher.PBEWITHSHAAND3-KEYTRIPLEDES-CBC", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithSHAAndDES3Key");
      Object var242 = this.put("Cipher.BROKENPBEWITHSHAAND3-KEYTRIPLEDES-CBC", "myorg.bouncycastle.jce.provider.BrokenJCEBlockCipher$BrokePBEWithSHAAndDES3Key");
      Object var243 = this.put("Cipher.OLDPBEWITHSHAAND3-KEYTRIPLEDES-CBC", "myorg.bouncycastle.jce.provider.BrokenJCEBlockCipher$OldPBEWithSHAAndDES3Key");
      Object var244 = this.put("Cipher.PBEWITHSHAAND2-KEYTRIPLEDES-CBC", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithSHAAndDES2Key");
      Object var245 = this.put("Cipher.BROKENPBEWITHSHAAND2-KEYTRIPLEDES-CBC", "myorg.bouncycastle.jce.provider.BrokenJCEBlockCipher$BrokePBEWithSHAAndDES2Key");
      Object var246 = this.put("Cipher.PBEWITHSHAAND128BITRC2-CBC", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithSHAAnd128BitRC2");
      Object var247 = this.put("Cipher.PBEWITHSHAAND40BITRC2-CBC", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithSHAAnd40BitRC2");
      Object var248 = this.put("Cipher.PBEWITHSHAAND128BITRC4", "myorg.bouncycastle.jce.provider.JCEStreamCipher$PBEWithSHAAnd128BitRC4");
      Object var249 = this.put("Cipher.PBEWITHSHAAND40BITRC4", "myorg.bouncycastle.jce.provider.JCEStreamCipher$PBEWithSHAAnd40BitRC4");
      Object var250 = this.put("Alg.Alias.Cipher.PBEWITHSHA1AND3-KEYTRIPLEDES-CBC", "Cipher.PBEWITHSHAAND3-KEYTRIPLEDES-CBC");
      Object var251 = this.put("Alg.Alias.Cipher.PBEWITHSHA1AND2-KEYTRIPLEDES-CBC", "Cipher.PBEWITHSHAAND2-KEYTRIPLEDES-CBC");
      Object var252 = this.put("Alg.Alias.Cipher.PBEWITHSHA1AND128BITRC2-CBC", "Cipher.PBEWITHSHAAND128BITRC2-CBC");
      Object var253 = this.put("Alg.Alias.Cipher.PBEWITHSHA1AND40BITRC2-CBC", "Cipher.PBEWITHSHAAND40BITRC2-CBC");
      Object var254 = this.put("Alg.Alias.Cipher.PBEWITHSHA1AND128BITRC4", "Cipher.PBEWITHSHAAND128BITRC4");
      Object var255 = this.put("Alg.Alias.Cipher.PBEWITHSHA1AND40BITRC4", "Cipher.PBEWITHSHAAND40BITRC4");
      StringBuilder var256 = (new StringBuilder()).append("Alg.Alias.Cipher.");
      String var257 = BCObjectIdentifiers.bc_pbe_sha1_pkcs12_aes128_cbc.getId();
      String var258 = var256.append(var257).toString();
      this.put(var258, "PBEWITHSHAAND128BITAES-CBC-BC");
      StringBuilder var260 = (new StringBuilder()).append("Alg.Alias.Cipher.");
      String var261 = BCObjectIdentifiers.bc_pbe_sha1_pkcs12_aes192_cbc.getId();
      String var262 = var260.append(var261).toString();
      this.put(var262, "PBEWITHSHAAND192BITAES-CBC-BC");
      StringBuilder var264 = (new StringBuilder()).append("Alg.Alias.Cipher.");
      String var265 = BCObjectIdentifiers.bc_pbe_sha1_pkcs12_aes256_cbc.getId();
      String var266 = var264.append(var265).toString();
      this.put(var266, "PBEWITHSHAAND256BITAES-CBC-BC");
      StringBuilder var268 = (new StringBuilder()).append("Alg.Alias.Cipher.");
      String var269 = BCObjectIdentifiers.bc_pbe_sha256_pkcs12_aes128_cbc.getId();
      String var270 = var268.append(var269).toString();
      this.put(var270, "PBEWITHSHA256AND128BITAES-CBC-BC");
      StringBuilder var272 = (new StringBuilder()).append("Alg.Alias.Cipher.");
      String var273 = BCObjectIdentifiers.bc_pbe_sha256_pkcs12_aes192_cbc.getId();
      String var274 = var272.append(var273).toString();
      this.put(var274, "PBEWITHSHA256AND192BITAES-CBC-BC");
      StringBuilder var276 = (new StringBuilder()).append("Alg.Alias.Cipher.");
      String var277 = BCObjectIdentifiers.bc_pbe_sha256_pkcs12_aes256_cbc.getId();
      String var278 = var276.append(var277).toString();
      this.put(var278, "PBEWITHSHA256AND256BITAES-CBC-BC");
      Object var280 = this.put("Cipher.PBEWITHSHAAND128BITAES-CBC-BC", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithAESCBC");
      Object var281 = this.put("Cipher.PBEWITHSHAAND192BITAES-CBC-BC", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithAESCBC");
      Object var282 = this.put("Cipher.PBEWITHSHAAND256BITAES-CBC-BC", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithAESCBC");
      Object var283 = this.put("Cipher.PBEWITHSHA256AND128BITAES-CBC-BC", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithAESCBC");
      Object var284 = this.put("Cipher.PBEWITHSHA256AND192BITAES-CBC-BC", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithAESCBC");
      Object var285 = this.put("Cipher.PBEWITHSHA256AND256BITAES-CBC-BC", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithAESCBC");
      Object var286 = this.put("Alg.Alias.Cipher.PBEWITHSHA1AND128BITAES-CBC-BC", "PBEWITHSHAAND128BITAES-CBC-BC");
      Object var287 = this.put("Alg.Alias.Cipher.PBEWITHSHA1AND192BITAES-CBC-BC", "PBEWITHSHAAND192BITAES-CBC-BC");
      Object var288 = this.put("Alg.Alias.Cipher.PBEWITHSHA1AND256BITAES-CBC-BC", "PBEWITHSHAAND256BITAES-CBC-BC");
      Object var289 = this.put("Alg.Alias.Cipher.PBEWITHSHA-1AND128BITAES-CBC-BC", "PBEWITHSHAAND128BITAES-CBC-BC");
      Object var290 = this.put("Alg.Alias.Cipher.PBEWITHSHA-1AND192BITAES-CBC-BC", "PBEWITHSHAAND192BITAES-CBC-BC");
      Object var291 = this.put("Alg.Alias.Cipher.PBEWITHSHA-1AND256BITAES-CBC-BC", "PBEWITHSHAAND256BITAES-CBC-BC");
      Object var292 = this.put("Alg.Alias.Cipher.PBEWITHSHA-256AND128BITAES-CBC-BC", "PBEWITHSHA256AND128BITAES-CBC-BC");
      Object var293 = this.put("Alg.Alias.Cipher.PBEWITHSHA-256AND192BITAES-CBC-BC", "PBEWITHSHA256AND192BITAES-CBC-BC");
      Object var294 = this.put("Alg.Alias.Cipher.PBEWITHSHA-256AND256BITAES-CBC-BC", "PBEWITHSHA256AND256BITAES-CBC-BC");
      Object var295 = this.put("Cipher.PBEWITHMD5AND128BITAES-CBC-OPENSSL", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithAESCBC");
      Object var296 = this.put("Cipher.PBEWITHMD5AND192BITAES-CBC-OPENSSL", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithAESCBC");
      Object var297 = this.put("Cipher.PBEWITHMD5AND256BITAES-CBC-OPENSSL", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithAESCBC");
      Object var298 = this.put("Cipher.PBEWITHSHAANDTWOFISH-CBC", "myorg.bouncycastle.jce.provider.JCEBlockCipher$PBEWithSHAAndTwofish");
      Object var299 = this.put("Cipher.OLDPBEWITHSHAANDTWOFISH-CBC", "myorg.bouncycastle.jce.provider.BrokenJCEBlockCipher$OldPBEWithSHAAndTwofish");
      Object var300 = this.put("Alg.Alias.Cipher.1.2.840.113549.1.12.1.1", "PBEWITHSHAAND128BITRC4");
      Object var301 = this.put("Alg.Alias.Cipher.1.2.840.113549.1.12.1.2", "PBEWITHSHAAND40BITRC4");
      Object var302 = this.put("Alg.Alias.Cipher.1.2.840.113549.1.12.1.3", "PBEWITHSHAAND3-KEYTRIPLEDES-CBC");
      Object var303 = this.put("Alg.Alias.Cipher.1.2.840.113549.1.12.1.4", "PBEWITHSHAAND2-KEYTRIPLEDES-CBC");
      Object var304 = this.put("Alg.Alias.Cipher.1.2.840.113549.1.12.1.5", "PBEWITHSHAAND128BITRC2-CBC");
      Object var305 = this.put("Alg.Alias.Cipher.1.2.840.113549.1.12.1.6", "PBEWITHSHAAND40BITRC2-CBC");
      Object var306 = this.put("Alg.Alias.Cipher.PBEWITHSHA1ANDDESEDE", "PBEWITHSHAAND3-KEYTRIPLEDES-CBC");
      Object var307 = this.put("KeyGenerator.DES", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$DES");
      StringBuilder var308 = (new StringBuilder()).append("Alg.Alias.KeyGenerator.");
      DERObjectIdentifier var309 = OIWObjectIdentifiers.desCBC;
      String var310 = var308.append(var309).toString();
      this.put(var310, "DES");
      Object var312 = this.put("KeyGenerator.DESEDE", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$DESede");
      StringBuilder var313 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var314 = PKCSObjectIdentifiers.des_EDE3_CBC;
      String var315 = var313.append(var314).toString();
      this.put(var315, "myorg.bouncycastle.jce.provider.JCEKeyGenerator$DESede3");
      Object var317 = this.put("KeyGenerator.DESEDEWRAP", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$DESede");
      Object var318 = this.put("KeyGenerator.SKIPJACK", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$Skipjack");
      Object var319 = this.put("KeyGenerator.BLOWFISH", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$Blowfish");
      Object var320 = this.put("Alg.Alias.KeyGenerator.1.3.6.1.4.1.3029.1.2", "BLOWFISH");
      Object var321 = this.put("KeyGenerator.TWOFISH", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$Twofish");
      Object var322 = this.put("KeyGenerator.RC2", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$RC2");
      Object var323 = this.put("KeyGenerator.1.2.840.113549.3.2", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$RC2");
      Object var324 = this.put("KeyGenerator.RC4", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$RC4");
      Object var325 = this.put("Alg.Alias.KeyGenerator.ARC4", "RC4");
      Object var326 = this.put("Alg.Alias.KeyGenerator.1.2.840.113549.3.4", "RC4");
      Object var327 = this.put("KeyGenerator.RC5", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$RC5");
      Object var328 = this.put("Alg.Alias.KeyGenerator.RC5-32", "RC5");
      Object var329 = this.put("KeyGenerator.RC5-64", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$RC564");
      Object var330 = this.put("KeyGenerator.RC6", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$RC6");
      Object var331 = this.put("KeyGenerator.RIJNDAEL", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$Rijndael");
      Object var332 = this.put("KeyGenerator.SERPENT", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$Serpent");
      Object var333 = this.put("KeyGenerator.SALSA20", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$Salsa20");
      Object var334 = this.put("KeyGenerator.HC128", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$HC128");
      Object var335 = this.put("KeyGenerator.HC256", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$HC256");
      Object var336 = this.put("KeyGenerator.VMPC", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$VMPC");
      Object var337 = this.put("KeyGenerator.VMPC-KSA3", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$VMPCKSA3");
      Object var338 = this.put("KeyGenerator.CAST6", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$CAST6");
      Object var339 = this.put("KeyGenerator.TEA", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$TEA");
      Object var340 = this.put("KeyGenerator.XTEA", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$XTEA");
      Object var341 = this.put("KeyGenerator.GOST28147", "myorg.bouncycastle.jce.provider.JCEKeyGenerator$GOST28147");
      Object var342 = this.put("Alg.Alias.KeyGenerator.GOST", "GOST28147");
      Object var343 = this.put("Alg.Alias.KeyGenerator.GOST-28147", "GOST28147");
      StringBuilder var344 = (new StringBuilder()).append("Alg.Alias.KeyGenerator.");
      DERObjectIdentifier var345 = CryptoProObjectIdentifiers.gostR28147_cbc;
      String var346 = var344.append(var345).toString();
      this.put(var346, "GOST28147");
      Object var348 = this.put("KeyPairGenerator.RSA", "myorg.bouncycastle.jce.provider.JDKKeyPairGenerator$RSA");
      Object var349 = this.put("KeyPairGenerator.DH", "myorg.bouncycastle.jce.provider.JDKKeyPairGenerator$DH");
      Object var350 = this.put("KeyPairGenerator.DSA", "myorg.bouncycastle.jce.provider.JDKKeyPairGenerator$DSA");
      Object var351 = this.put("KeyPairGenerator.ELGAMAL", "myorg.bouncycastle.jce.provider.JDKKeyPairGenerator$ElGamal");
      Object var352 = this.put("Alg.Alias.KeyPairGenerator.1.2.840.113549.1.1.1", "RSA");
      Object var353 = this.put("Alg.Alias.KeyPairGenerator.DIFFIEHELLMAN", "DH");
      Object var354 = this.put("KeyPairGenerator.GOST3410", "myorg.bouncycastle.jce.provider.JDKKeyPairGenerator$GOST3410");
      Object var355 = this.put("Alg.Alias.KeyPairGenerator.GOST-3410", "GOST3410");
      Object var356 = this.put("Alg.Alias.KeyPairGenerator.GOST-3410-94", "GOST3410");
      Object var357 = this.put("KeyFactory.RSA", "myorg.bouncycastle.jce.provider.JDKKeyFactory$RSA");
      Object var358 = this.put("KeyFactory.DH", "myorg.bouncycastle.jce.provider.JDKKeyFactory$DH");
      Object var359 = this.put("KeyFactory.DSA", "myorg.bouncycastle.jce.provider.JDKKeyFactory$DSA");
      Object var360 = this.put("KeyFactory.ELGAMAL", "myorg.bouncycastle.jce.provider.JDKKeyFactory$ElGamal");
      Object var361 = this.put("KeyFactory.ElGamal", "myorg.bouncycastle.jce.provider.JDKKeyFactory$ElGamal");
      Object var362 = this.put("KeyFactory.X.509", "myorg.bouncycastle.jce.provider.JDKKeyFactory$X509");
      Object var363 = this.put("Alg.Alias.KeyFactory.1.2.840.113549.1.1.1", "RSA");
      Object var364 = this.put("Alg.Alias.KeyFactory.1.2.840.10040.4.1", "DSA");
      Object var365 = this.put("Alg.Alias.KeyFactory.DIFFIEHELLMAN", "DH");
      Object var366 = this.put("KeyFactory.GOST3410", "myorg.bouncycastle.jce.provider.JDKKeyFactory$GOST3410");
      Object var367 = this.put("Alg.Alias.KeyFactory.GOST-3410", "GOST3410");
      Object var368 = this.put("Alg.Alias.KeyFactory.GOST-3410-94", "GOST3410");
      StringBuilder var369 = (new StringBuilder()).append("Alg.Alias.KeyFactory.");
      DERObjectIdentifier var370 = CryptoProObjectIdentifiers.gostR3410_94;
      String var371 = var369.append(var370).toString();
      this.put(var371, "GOST3410");
      Object var373 = this.put("AlgorithmParameters.DES", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$IVAlgorithmParameters");
      StringBuilder var374 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      DERObjectIdentifier var375 = OIWObjectIdentifiers.desCBC;
      String var376 = var374.append(var375).toString();
      this.put(var376, "DES");
      Object var378 = this.put("AlgorithmParameters.DESEDE", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$IVAlgorithmParameters");
      StringBuilder var379 = (new StringBuilder()).append("AlgorithmParameters.");
      DERObjectIdentifier var380 = PKCSObjectIdentifiers.des_EDE3_CBC;
      String var381 = var379.append(var380).toString();
      this.put(var381, "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$IVAlgorithmParameters");
      Object var383 = this.put("AlgorithmParameters.RC2", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$RC2AlgorithmParameters");
      Object var384 = this.put("AlgorithmParameters.1.2.840.113549.3.2", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$RC2AlgorithmParameters");
      Object var385 = this.put("AlgorithmParameters.RC5", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$IVAlgorithmParameters");
      Object var386 = this.put("AlgorithmParameters.RC6", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$IVAlgorithmParameters");
      Object var387 = this.put("AlgorithmParameters.BLOWFISH", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$IVAlgorithmParameters");
      Object var388 = this.put("Alg.Alias.AlgorithmParameters.1.3.6.1.4.1.3029.1.2", "BLOWFISH");
      Object var389 = this.put("AlgorithmParameters.TWOFISH", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$IVAlgorithmParameters");
      Object var390 = this.put("AlgorithmParameters.SKIPJACK", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$IVAlgorithmParameters");
      Object var391 = this.put("AlgorithmParameters.RIJNDAEL", "myorg.bouncycastle.jce.provider.JDKAlgorithmParameters$IVAlgorithmParameters");
      Object var392 = this.put("SecretKeyFactory.DES", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$DES");
      Object var393 = this.put("SecretKeyFactory.DESEDE", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$DESede");
      Object var394 = this.put("SecretKeyFactory.PBEWITHMD2ANDDES", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithMD2AndDES");
      Object var395 = this.put("SecretKeyFactory.PBEWITHMD2ANDRC2", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithMD2AndRC2");
      Object var396 = this.put("SecretKeyFactory.PBEWITHMD5ANDDES", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithMD5AndDES");
      Object var397 = this.put("SecretKeyFactory.PBEWITHMD5ANDRC2", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithMD5AndRC2");
      Object var398 = this.put("SecretKeyFactory.PBEWITHSHA1ANDDES", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHA1AndDES");
      Object var399 = this.put("SecretKeyFactory.PBEWITHSHA1ANDRC2", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHA1AndRC2");
      Object var400 = this.put("SecretKeyFactory.PBEWITHSHAAND3-KEYTRIPLEDES-CBC", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHAAndDES3Key");
      Object var401 = this.put("SecretKeyFactory.PBEWITHSHAAND2-KEYTRIPLEDES-CBC", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHAAndDES2Key");
      Object var402 = this.put("SecretKeyFactory.PBEWITHSHAAND128BITRC4", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHAAnd128BitRC4");
      Object var403 = this.put("SecretKeyFactory.PBEWITHSHAAND40BITRC4", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHAAnd40BitRC4");
      Object var404 = this.put("SecretKeyFactory.PBEWITHSHAAND128BITRC2-CBC", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHAAnd128BitRC2");
      Object var405 = this.put("SecretKeyFactory.PBEWITHSHAAND40BITRC2-CBC", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHAAnd40BitRC2");
      Object var406 = this.put("SecretKeyFactory.PBEWITHSHAANDTWOFISH-CBC", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHAAndTwofish");
      Object var407 = this.put("SecretKeyFactory.PBEWITHHMACRIPEMD160", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithRIPEMD160");
      Object var408 = this.put("SecretKeyFactory.PBEWITHHMACSHA1", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHA");
      Object var409 = this.put("SecretKeyFactory.PBEWITHHMACTIGER", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithTiger");
      Object var410 = this.put("SecretKeyFactory.PBEWITHMD5AND128BITAES-CBC-OPENSSL", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithMD5And128BitAESCBCOpenSSL");
      Object var411 = this.put("SecretKeyFactory.PBEWITHMD5AND192BITAES-CBC-OPENSSL", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithMD5And192BitAESCBCOpenSSL");
      Object var412 = this.put("SecretKeyFactory.PBEWITHMD5AND256BITAES-CBC-OPENSSL", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithMD5And256BitAESCBCOpenSSL");
      Object var413 = this.put("Alg.Alias.SecretKeyFactory.PBE", "PBE/PKCS5");
      Object var414 = this.put("Alg.Alias.SecretKeyFactory.BROKENPBEWITHMD5ANDDES", "PBE/PKCS5");
      Object var415 = this.put("Alg.Alias.SecretKeyFactory.BROKENPBEWITHSHA1ANDDES", "PBE/PKCS5");
      Object var416 = this.put("Alg.Alias.SecretKeyFactory.OLDPBEWITHSHAAND3-KEYTRIPLEDES-CBC", "PBE/PKCS12");
      Object var417 = this.put("Alg.Alias.SecretKeyFactory.BROKENPBEWITHSHAAND3-KEYTRIPLEDES-CBC", "PBE/PKCS12");
      Object var418 = this.put("Alg.Alias.SecretKeyFactory.BROKENPBEWITHSHAAND2-KEYTRIPLEDES-CBC", "PBE/PKCS12");
      Object var419 = this.put("Alg.Alias.SecretKeyFactory.OLDPBEWITHSHAANDTWOFISH-CBC", "PBE/PKCS12");
      Object var420 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHMD2ANDDES-CBC", "PBEWITHMD2ANDDES");
      Object var421 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHMD2ANDRC2-CBC", "PBEWITHMD2ANDRC2");
      Object var422 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHMD5ANDDES-CBC", "PBEWITHMD5ANDDES");
      Object var423 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHMD5ANDRC2-CBC", "PBEWITHMD5ANDRC2");
      Object var424 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHSHA1ANDDES-CBC", "PBEWITHSHA1ANDDES");
      Object var425 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHSHA1ANDRC2-CBC", "PBEWITHSHA1ANDRC2");
      StringBuilder var426 = (new StringBuilder()).append("Alg.Alias.SecretKeyFactory.");
      DERObjectIdentifier var427 = PKCSObjectIdentifiers.pbeWithMD2AndDES_CBC;
      String var428 = var426.append(var427).toString();
      this.put(var428, "PBEWITHMD2ANDDES");
      StringBuilder var430 = (new StringBuilder()).append("Alg.Alias.SecretKeyFactory.");
      DERObjectIdentifier var431 = PKCSObjectIdentifiers.pbeWithMD2AndRC2_CBC;
      String var432 = var430.append(var431).toString();
      this.put(var432, "PBEWITHMD2ANDRC2");
      StringBuilder var434 = (new StringBuilder()).append("Alg.Alias.SecretKeyFactory.");
      DERObjectIdentifier var435 = PKCSObjectIdentifiers.pbeWithMD5AndDES_CBC;
      String var436 = var434.append(var435).toString();
      this.put(var436, "PBEWITHMD5ANDDES");
      StringBuilder var438 = (new StringBuilder()).append("Alg.Alias.SecretKeyFactory.");
      DERObjectIdentifier var439 = PKCSObjectIdentifiers.pbeWithMD5AndRC2_CBC;
      String var440 = var438.append(var439).toString();
      this.put(var440, "PBEWITHMD5ANDRC2");
      StringBuilder var442 = (new StringBuilder()).append("Alg.Alias.SecretKeyFactory.");
      DERObjectIdentifier var443 = PKCSObjectIdentifiers.pbeWithSHA1AndDES_CBC;
      String var444 = var442.append(var443).toString();
      this.put(var444, "PBEWITHSHA1ANDDES");
      StringBuilder var446 = (new StringBuilder()).append("Alg.Alias.SecretKeyFactory.");
      DERObjectIdentifier var447 = PKCSObjectIdentifiers.pbeWithSHA1AndRC2_CBC;
      String var448 = var446.append(var447).toString();
      this.put(var448, "PBEWITHSHA1ANDRC2");
      Object var450 = this.put("Alg.Alias.SecretKeyFactory.1.2.840.113549.1.12.1.1", "PBEWITHSHAAND128BITRC4");
      Object var451 = this.put("Alg.Alias.SecretKeyFactory.1.2.840.113549.1.12.1.2", "PBEWITHSHAAND40BITRC4");
      Object var452 = this.put("Alg.Alias.SecretKeyFactory.1.2.840.113549.1.12.1.3", "PBEWITHSHAAND3-KEYTRIPLEDES-CBC");
      Object var453 = this.put("Alg.Alias.SecretKeyFactory.1.2.840.113549.1.12.1.4", "PBEWITHSHAAND2-KEYTRIPLEDES-CBC");
      Object var454 = this.put("Alg.Alias.SecretKeyFactory.1.2.840.113549.1.12.1.5", "PBEWITHSHAAND128BITRC2-CBC");
      Object var455 = this.put("Alg.Alias.SecretKeyFactory.1.2.840.113549.1.12.1.6", "PBEWITHSHAAND40BITRC2-CBC");
      Object var456 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHHMACSHA", "PBEWITHHMACSHA1");
      Object var457 = this.put("Alg.Alias.SecretKeyFactory.1.3.14.3.2.26", "PBEWITHHMACSHA1");
      Object var458 = this.put("Alg.Alias.SecretKeyFactory.PBEWithSHAAnd3KeyTripleDES", "PBEWITHSHAAND3-KEYTRIPLEDES-CBC");
      Object var459 = this.put("SecretKeyFactory.PBEWITHSHAAND128BITAES-CBC-BC", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHAAnd128BitAESBC");
      Object var460 = this.put("SecretKeyFactory.PBEWITHSHAAND192BITAES-CBC-BC", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHAAnd192BitAESBC");
      Object var461 = this.put("SecretKeyFactory.PBEWITHSHAAND256BITAES-CBC-BC", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHAAnd256BitAESBC");
      Object var462 = this.put("SecretKeyFactory.PBEWITHSHA256AND128BITAES-CBC-BC", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHA256And128BitAESBC");
      Object var463 = this.put("SecretKeyFactory.PBEWITHSHA256AND192BITAES-CBC-BC", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHA256And192BitAESBC");
      Object var464 = this.put("SecretKeyFactory.PBEWITHSHA256AND256BITAES-CBC-BC", "myorg.bouncycastle.jce.provider.JCESecretKeyFactory$PBEWithSHA256And256BitAESBC");
      Object var465 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHSHA1AND128BITAES-CBC-BC", "PBEWITHSHAAND128BITAES-CBC-BC");
      Object var466 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHSHA1AND192BITAES-CBC-BC", "PBEWITHSHAAND192BITAES-CBC-BC");
      Object var467 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHSHA1AND256BITAES-CBC-BC", "PBEWITHSHAAND256BITAES-CBC-BC");
      Object var468 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHSHA-1AND128BITAES-CBC-BC", "PBEWITHSHAAND128BITAES-CBC-BC");
      Object var469 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHSHA-1AND192BITAES-CBC-BC", "PBEWITHSHAAND192BITAES-CBC-BC");
      Object var470 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHSHA-1AND256BITAES-CBC-BC", "PBEWITHSHAAND256BITAES-CBC-BC");
      Object var471 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHSHA-256AND128BITAES-CBC-BC", "PBEWITHSHA256AND128BITAES-CBC-BC");
      Object var472 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHSHA-256AND192BITAES-CBC-BC", "PBEWITHSHA256AND192BITAES-CBC-BC");
      Object var473 = this.put("Alg.Alias.SecretKeyFactory.PBEWITHSHA-256AND256BITAES-CBC-BC", "PBEWITHSHA256AND256BITAES-CBC-BC");
      StringBuilder var474 = (new StringBuilder()).append("Alg.Alias.SecretKeyFactory.");
      String var475 = BCObjectIdentifiers.bc_pbe_sha1_pkcs12_aes128_cbc.getId();
      String var476 = var474.append(var475).toString();
      this.put(var476, "PBEWITHSHAAND128BITAES-CBC-BC");
      StringBuilder var478 = (new StringBuilder()).append("Alg.Alias.SecretKeyFactory.");
      String var479 = BCObjectIdentifiers.bc_pbe_sha1_pkcs12_aes192_cbc.getId();
      String var480 = var478.append(var479).toString();
      this.put(var480, "PBEWITHSHAAND192BITAES-CBC-BC");
      StringBuilder var482 = (new StringBuilder()).append("Alg.Alias.SecretKeyFactory.");
      String var483 = BCObjectIdentifiers.bc_pbe_sha1_pkcs12_aes256_cbc.getId();
      String var484 = var482.append(var483).toString();
      this.put(var484, "PBEWITHSHAAND256BITAES-CBC-BC");
      StringBuilder var486 = (new StringBuilder()).append("Alg.Alias.SecretKeyFactory.");
      String var487 = BCObjectIdentifiers.bc_pbe_sha256_pkcs12_aes128_cbc.getId();
      String var488 = var486.append(var487).toString();
      this.put(var488, "PBEWITHSHA256AND128BITAES-CBC-BC");
      StringBuilder var490 = (new StringBuilder()).append("Alg.Alias.SecretKeyFactory.");
      String var491 = BCObjectIdentifiers.bc_pbe_sha256_pkcs12_aes192_cbc.getId();
      String var492 = var490.append(var491).toString();
      this.put(var492, "PBEWITHSHA256AND192BITAES-CBC-BC");
      StringBuilder var494 = (new StringBuilder()).append("Alg.Alias.SecretKeyFactory.");
      String var495 = BCObjectIdentifiers.bc_pbe_sha256_pkcs12_aes256_cbc.getId();
      String var496 = var494.append(var495).toString();
      this.put(var496, "PBEWITHSHA256AND256BITAES-CBC-BC");
      this.addMacAlgorithms();
      this.addMessageDigestAlgorithms();
      this.addSignatureAlgorithms();
      Object var498 = this.put("CertPathValidator.RFC3281", "myorg.bouncycastle.jce.provider.PKIXAttrCertPathValidatorSpi");
      Object var499 = this.put("CertPathBuilder.RFC3281", "myorg.bouncycastle.jce.provider.PKIXAttrCertPathBuilderSpi");
      Object var500 = this.put("CertPathValidator.RFC3280", "myorg.bouncycastle.jce.provider.PKIXCertPathValidatorSpi");
      Object var501 = this.put("CertPathBuilder.RFC3280", "myorg.bouncycastle.jce.provider.PKIXCertPathBuilderSpi");
      Object var502 = this.put("CertPathValidator.PKIX", "myorg.bouncycastle.jce.provider.PKIXCertPathValidatorSpi");
      Object var503 = this.put("CertPathBuilder.PKIX", "myorg.bouncycastle.jce.provider.PKIXCertPathBuilderSpi");
      Object var504 = this.put("CertStore.Collection", "myorg.bouncycastle.jce.provider.CertStoreCollectionSpi");
      Object var505 = this.put("CertStore.LDAP", "myorg.bouncycastle.jce.provider.X509LDAPCertStoreSpi");
      Object var506 = this.put("CertStore.Multi", "myorg.bouncycastle.jce.provider.MultiCertStoreSpi");
      Object var507 = this.put("Alg.Alias.CertStore.X509LDAP", "LDAP");
   }

   public void setParameter(String var1, Object var2) {
      ProviderUtil.setParameter(var1, var2);
   }

   class 1 implements PrivilegedAction {

      1() {}

      public Object run() {
         BouncyCastleProvider.this.setup();
         return null;
      }
   }
}
