package org.apache.commons.httpclient;

import org.apache.commons.httpclient.HeaderElement;
import org.apache.commons.httpclient.HttpException;
import org.apache.commons.httpclient.NameValuePair;

public class Header extends NameValuePair {

   private boolean isAutogenerated;


   public Header() {
      this((String)null, (String)null);
   }

   public Header(String var1, String var2) {
      super(var1, var2);
      this.isAutogenerated = (boolean)0;
   }

   public Header(String var1, String var2, boolean var3) {
      super(var1, var2);
      this.isAutogenerated = (boolean)0;
      this.isAutogenerated = var3;
   }

   public HeaderElement[] getElements() {
      return HeaderElement.parseElements(this.getValue());
   }

   public HeaderElement[] getValues() throws HttpException {
      return HeaderElement.parse(this.getValue());
   }

   public boolean isAutogenerated() {
      return this.isAutogenerated;
   }

   public String toExternalForm() {
      StringBuilder var1 = new StringBuilder();
      String var2;
      if(this.getName() == null) {
         var2 = "";
      } else {
         var2 = this.getName();
      }

      StringBuilder var3 = var1.append(var2).append(": ");
      String var4;
      if(this.getValue() == null) {
         var4 = "";
      } else {
         var4 = this.getValue();
      }

      return var3.append(var4).append("\r\n").toString();
   }

   public String toString() {
      return this.toExternalForm();
   }
}
