drop table ANALYTE_LINE if exists;
drop table AUDIT_LOG if exists;
drop table BATTERY_LINE if exists;
drop table CPT if exists;
drop table GST_ADDRESS if exists;
drop table GST_ALLERGY if exists;
drop table GST_ALLERGY_EVENT_INGRED if exists;
drop table GST_ALLERGY_FDB_XREF if exists;
drop table GST_APPLIANCE_ORDER if exists;
drop table GST_APPLIANCE_ORDER_DEF if exists;
drop table GST_ATTACHMENT if exists;
drop table GST_BILLABLE_ITEM if exists;
drop table GST_BODY_SYSTEM if exists;
drop table GST_CLINIC if exists;
drop table GST_CLINICAL_CONCEPT if exists;
drop table GST_CLINICAL_EVENT if exists;
drop table GST_CLINIC_PATIENT if exists;
drop table GST_CLINIC_PATIENT_VW if exists;
drop table GST_COMMON_VALUE if exists;
drop table GST_COMMON_VALUE_MEDIA if exists;
drop table GST_COMMON_VALUE_MEDIA_GRID if exists;
drop table GST_COMMON_VALUE_URL_LIST if exists;
drop table GST_CONCEPT if exists;
drop table GST_CONCEPT_COLLECTION_TRIGGER if exists;
drop table GST_CONCEPT_DISEASE_INDICATOR if exists;
drop table GST_CONCEPT_GROUP_CONCEPT if exists;
drop table GST_CONCEPT_ITEM_GROUP if exists;
drop table GST_CONCEPT_MEDIA if exists;
drop table GST_CONCEPT_MEDIA_GRID if exists;
drop table GST_CONCEPT_TEMPLATE if exists;
drop table GST_CONCEPT_TEMPLATE_FIELD if exists;
drop table GST_CONCEPT_TEMPLATE_LINE if exists;
drop table GST_CONCEPT_TEMPLATE_SECTION if exists;
drop table GST_CONCEPT_URL_LIST if exists;
drop table GST_CURRENT_PROBLEM if exists;
drop table GST_CURRENT_PROBLEM_HIST if exists;
drop table GST_CURRENT_PROBLEM_STATUS if exists;
drop table GST_DISEASE if exists;
drop table GST_DISEASE_DXID if exists;
drop table GST_DISEASE_GSLOINCS if exists;
drop table GST_DISEASE_LAB_TEST if exists;
drop table GST_DOC_TEMPLATES if exists;
drop table GST_DOC_TREATMENT_TEMPLATES if exists;
drop table GST_DOMAIN_ROLE if exists;
drop table GST_DUMMY_ENTITY if exists;
drop table GST_EXAM_ELEMENT if exists;
drop table GST_EXAM_TYPE if exists;
drop table GST_EXAM_TYPE_SECTION if exists;
drop table GST_EXPECTED_OUTCOME_DEF if exists;
drop table GST_FDB_DUR_ACTION if exists;
drop table GST_FDB_DUR_ACTION_RESULT if exists;
drop table GST_FINDING_COLLECTION if exists;
drop table GST_FINDING_COLLECTION_LIST if exists;
drop table GST_FINDING_REFERENCE if exists;
drop table GST_HCPCS_RIC if exists;
drop table GST_HPI_MODIFIERS if exists;
drop table GST_JGK_A if exists;
drop table GST_JGK_B if exists;
drop table GST_LAB_ANALYTE if exists;
drop table GST_LAB_CATEGORY_TEST_LIST if exists;
drop table GST_LAB_ORDER_DEF if exists;
drop table GST_LAB_PANEL if exists;
drop table GST_LAB_PANEL_COMPONENT if exists;
drop table GST_LAB_TEST if exists;
drop table GST_LAB_TEST_CATEGORY if exists;
drop table GST_LAB_TEST_GSLOINC_LIST if exists;
drop table GST_LAB_TEST_ITEM if exists;
drop table GST_MEDIA if exists;
drop table GST_MEDICATION_ORDER if exists;
drop table GST_MEDICATION_ORDER_DEF if exists;
drop table GST_MED_ALLERGY_INFO if exists;
drop table GST_MED_EVENT_FDB_DISEASE if exists;
drop table GST_MED_STATUS if exists;
drop table GST_MED_STATUS_REASON if exists;
drop table GST_MED_THERAPEUTIC_EFFECT if exists;
drop table GST_NORMAL_PARENT_CHILD if exists;
drop table GST_NORMAL_RANGE if exists;
drop table GST_ORGANIZATION if exists;
drop table GST_ORGANIZATION_ROLE if exists;
drop table GST_PARTY if exists;
drop table GST_PATIENT if exists;
drop table GST_PATIENT_ALLERGY if exists;
drop table GST_PATIENT_INSTRUCTIONS if exists;
drop table GST_PATIENT_INSTRUCTION_DEF if exists;
drop table GST_PERFORMING_LAB if exists;
drop table GST_PERSON if exists;
drop table GST_PERSONALIZED_TREE if exists;
drop table GST_PERSONALIZED_TREE_ITEM if exists;
drop table GST_PERSON_ROLE if exists;
drop table GST_PHONE if exists;
drop table GST_PHYS_SIG if exists;
drop table GST_PRACTITIONER if exists;
drop table GST_PROCEDURE if exists;
drop table GST_PROCEDURE_ORDER if exists;
drop table GST_PROCEDURE_ORDER_DEF if exists;
drop table GST_PROCEDURE_URL_LIST if exists;
drop table GST_PROCEDURE_VALID_VALUE if exists;
drop table GST_RAD_CATEGORY_DISEASES if exists;
drop table GST_RAD_CLINICAL_CONDITION if exists;
drop table GST_RAD_CLIN_COND_SOURCE if exists;
drop table GST_RAD_CONCEPT if exists;
drop table GST_RAD_MEDICATION if exists;
drop table GST_RAD_MODALITY if exists;
drop table GST_RAD_ORDERABLE_ITEM if exists;
drop table GST_RAD_ORDERABLE_MEDICATION if exists;
drop table GST_RAD_ORDERABLE_MODALITY if exists;
drop table GST_RAD_ORDERABLE_TOPOLOGY if exists;
drop table GST_RAD_ORDERABLE_VIEW if exists;
drop table GST_RAD_ORDERING_PROCEDURE if exists;
drop table GST_RAD_ORDER_ACTION if exists;
drop table GST_RAD_ORDER_DEFINITION if exists;
drop table GST_RAD_TOPOLOGY if exists;
drop table GST_RAD_VARIANT if exists;
drop table GST_RAD_VIEW if exists;
drop table GST_RESULT_VALUE if exists;
drop table GST_ROLE_RELATIONSHIP if exists;
drop table GST_SPECIMEN_SOURCE if exists;
drop table GST_SPONSOR_SITE if exists;
drop table GST_TREATMENT_ACTION if exists;
drop table GST_TREATMENT_ACTION_LOG if exists;
drop table GST_TREATMENT_ITEM_DEFINITION if exists;
drop table GST_TREATMENT_LAB_ORDER if exists;
drop table GST_TREATMENT_PLAN if exists;
drop table GST_TREATMENT_PLAN_OUTCOME if exists;
drop table GST_TREATMENT_PROBLEM if exists;
drop table GST_TREATMENT_STEP if exists;
drop table GST_TREATMENT_STEP_DEFINITION if exists;
drop table GST_TREATMENT_TEMPLATE if exists;
drop table GST_TREATMENT_TEMPLATE_CAT if exists;
drop table GST_TREATMENT_TEMPLATE_CONCEPT if exists;
drop table GST_TREATMENT_TEMPLATE_DISEASE if exists;
drop table GST_TREATMENT_TEMPLATE_SOURCE if exists;
drop table GST_TRIGGER_CONCEPT_COLLECTION if exists;
drop table GST_USERNAME if exists;
drop table GST_US_STATE if exists;
drop table GST_VALID_VALUE if exists;
drop table GST_ZIPCODE_INFO if exists;
drop table GS_LOINC if exists;
drop table GS_REF_RANGE if exists;
drop table GS_UNITS if exists;
drop table HCPCS_ACTION_CODE if exists;
drop table HCPCS_BE_TOS if exists;
drop table HCPCS_BODY_SYSTEM if exists;
drop table HCPCS_CATEGORY if exists;
drop table HCPCS_CMS_TOS if exists;
drop table HCPCS_CODE if exists;
drop table HCPCS_CODE_CIM_REF if exists;
drop table HCPCS_CODE_CMS_TOS if exists;
drop table HCPCS_CODE_LABCERT if exists;
drop table HCPCS_CODE_MCM_REF if exists;
drop table HCPCS_CODE_PIC if exists;
drop table HCPCS_CODE_XREF if exists;
drop table HCPCS_COVERAGE_CODE if exists;
drop table HCPCS_LAB_CERT_CODE if exists;
drop table HCPCS_MODIFIER_CIM_REF if exists;
drop table HCPCS_MODIFIER_CODE if exists;
drop table HCPCS_MODIFIER_MCM_REF if exists;
drop table HCPCS_MODIFIER_XREF if exists;
drop table HCPCS_MOG_PMT_GRP_CODE if exists;
drop table HCPCS_MOG_PMT_POLICY_IND_CODE if exists;
drop table HCPCS_MULTI_PIC if exists;
drop table HCPCS_PIC if exists;
drop table HCPCS_TREE if exists;
drop table INTERIM_REPORT if exists;
drop table LAB_ORDER_CODE if exists;
drop table ORDER_REASON_LIST if exists;
drop table Person if exists;
drop table REQ_REPORT_FORM if exists;
drop table SPECIMEN_LINE if exists;
drop table TEXT_LINE if exists;
drop table icd9 if exists;
drop table icd9_class if exists;
drop sequence null if exists;
drop table GST_DISEASE if exists;
create table ANALYTE_LINE (INTERIM_NAME varchar(255) not null, DESCRIPTION_COLOR varchar(255), DESCRIPTION_FONT varchar(255), DESCRIPTION_JUSTIFICATION varchar(255), DESCRIPTION_PT_SIZE double, DESCRIPTION_WIDTH double, DESCRIPTION_X_OFFSET double, FREQUENCY_PLOT_HEIGHT double, FREQUENCY_PLOT_WIDTH double, FREQUENCY_PLOT_X_OFFSET double, HISTORICAL_PLOT_HEIGHT double, HISTORICAL_PLOT_WIDTH double, HISTORICAL_PLOT_X_OFFSET double, PERFORMING_LAB_COLOR varchar(255), PERFORMING_LAB_FONT varchar(255), PERFORMING_LAB_JUSTIFICATION varchar(255), PERFORMING_LAB_PT_SIZE double, PERFORMING_LAB_WIDTH double, PERFORMING_LAB_X_OFFSET double, QA_FLAG_COLOR varchar(255), QA_FLAG_FONT varchar(255), QA_FLAG_JUSTIFICATION varchar(255), QA_FLAG_PT_SIZE double, QA_FLAG_WIDTH double, QA_FLAG_X_OFFSET double, REF_RANGE_COLOR varchar(255), REF_RANGE_FONT varchar(255), REF_RANGE_JUSTIFICATION varchar(255), REF_RANGE_PT_SIZE double, REF_RANGE_WIDTH double, REF_RANGE_X_OFFSET double, RESULT_COLOR varchar(255), RESULT_DISPLAY_TYPE varchar(255), RESULT_FONT varchar(255), RESULT_JUSTIFICATION varchar(255), RESULT_PT_SIZE double, RESULT_WIDTH double, RESULT_X_OFFSET double, UNITS_COLOR varchar(255), UNITS_FONT varchar(255), UNITS_JUSTIFICATION varchar(255), UNITS_PT_SIZE double, UNITS_WIDTH double, UNITS_X_OFFSET double, PLOT_BUTTON_X_OFFSET double, primary key (INTERIM_NAME));
create table AUDIT_LOG (AUDIT_LOG_ID bigint generated by default as identity (start with 1), MESSAGE varchar(255) not null, CREATED timestamp not null, ENTITY_CLASS varchar(255) not null, ENTITY_ID bigint not null, USER_ID bigint not null, primary key (AUDIT_LOG_ID));
create table BATTERY_LINE (INTERIM_NAME varchar(255) not null, CURRENT_STATE_COLOR varchar(255), CURRENT_STATE_DESC_X_OFFSET double, CURRENT_STATE_FONT varchar(255), CURRENT_STATE_JUSTIFICATION varchar(255), CURRENT_STATE_PT_SIZE double, CURRENT_STATE_WIDTH double, DESCRIPTION_COLOR varchar(255), DESCRIPTION_FONT varchar(255), DESCRIPTION_JUSTIFICATION varchar(255), DESCRIPTION_PT_SIZE double, DESCRIPTION_WIDTH double, DESCRIPTION_X_OFFSET double, ORDERING_DIAG_COLOR varchar(255), ORDERING_DIAG_FONT varchar(255), ORDERING_DIAG_JUSTIFICATION varchar(255), ORDERING_DIAG_PT_SIZE double, ORDERING_DIAG_WIDTH double, ORDERING_DIAG_X_OFFSET double, PERFORMING_LAB_COLOR varchar(255), PERFORMING_LAB_FONT varchar(255), PERFORMING_LAB_JUSTIFICATION varchar(255), PERFORMING_LAB_WIDTH double, PERFORMING_LAB_X_OFFSET double, VERSION integer, primary key (INTERIM_NAME));
create table CPT (CPT_ID bigint not null, ABN_EDIT varchar(20), CLASS_NAME varchar(255), LONG_DESCRIPTION varchar(4000), MED_DESCRIPTION varchar(100), MODIFIED_DATE date, SHORT_DESCRIPTION varchar(30), SIBLING_ORDER double, STATUS double, CPT_CODE varchar(255) not null, primary key (CPT_ID));
create table GST_ADDRESS (ADDRESS_ID bigint generated by default as identity (start with 1), DISPLAY_ORDER integer, ADDRESS_TYPE varchar(255), LINE1 varchar(255), LINE2 varchar(255), CITY varchar(255), STATE varchar(255), COUNTRY varchar(255), ZIPCODE varchar(255), PARTY_ID bigint, primary key (ADDRESS_ID));
create table GST_ALLERGY (ALLERGY_ID bigint generated by default as identity (start with 1), ABBREVIATED_DESCRIPTION varchar(255), DESCRIPTION varchar(255), primary key (ALLERGY_ID));
create table GST_ALLERGY_EVENT_INGRED (ALLERGY_EVENT_INGRED_ID bigint generated by default as identity (start with 1), HIC_SEQN bigint, DISPLAY_ORDER integer, RECORDED_TIME timestamp, MED_ALLERGY_INFO_ID bigint, primary key (ALLERGY_EVENT_INGRED_ID));
create table GST_ALLERGY_FDB_XREF (ALLERGY_FDB_XREF_ID bigint generated by default as identity (start with 1), CONCEPT_ID bigint, MATCH_TYPE varchar(255), PHY_REVIEW_REQUIRED_YN varchar(1), CODE_VALUE varchar(255), REVIEWED_BY varchar(255), REVIEWED_DATE timestamp, DAM_ALRGN_GRP bigint, IS_MATCH_YN varchar(1), primary key (ALLERGY_FDB_XREF_ID));
create table GST_APPLIANCE_ORDER (TREATMENT_ACTION_ID bigint not null, HCPCS_CODE bigint, primary key (TREATMENT_ACTION_ID));
create table GST_APPLIANCE_ORDER_DEF (TREATMENT_ITEM_DEF_ID bigint not null, HCPCS_CODE bigint, primary key (TREATMENT_ITEM_DEF_ID));
create table GST_ATTACHMENT (ATTACHMENT_ID bigint generated by default as identity (start with 1), FILE_NAME varchar(255), FILE_SIZE bigint, MIME_TYPE varchar(255), DESCRIPTION varchar(255), FILE_DATA longvarbinary, THUMBNAIL longvarbinary, CHECKSUM bigint, CREATED_DATE timestamp, primary key (ATTACHMENT_ID));
create table GST_BILLABLE_ITEM (BILLABLE_ITEM_ID bigint generated by default as identity (start with 1), CONCEPT_ID bigint, DISPLAY_ORDER integer, VISIT_ID bigint, primary key (BILLABLE_ITEM_ID));
create table GST_BODY_SYSTEM (BODY_SYSTEM_ID bigint generated by default as identity (start with 1), DESCRIPTION varchar(255), ICON_POINTER varchar(255), BODY_SYSTEM_MODIFIER_ID bigint, primary key (BODY_SYSTEM_ID));
create table GST_CLINIC (ROLE_ID bigint not null, CLINIC_ABBR varchar(255), SITE bigint, primary key (ROLE_ID));
create table GST_CLINICAL_CONCEPT (CONCEPT_ID bigint not null, DISEASE_YN varchar(1), SKIP_EM_FILTER_YN varchar(1), PATIENT_TEXT varchar(255), PLOTABLE_YN varchar(1), AGE_GROUP varchar(255), BODY_SYSTEM_ID bigint, COMMONALITY_RANK smallint, RESULT_TYPE varchar(255), ABNORMAL_YN varchar(1), NEUTRAL_YN varchar(1), NORMAL_YN varchar(1), PARTICIPATE_PARENT_NORMAL_YN varchar(1), ROUTINE_YN varchar(1), STRUCTURE_YN varchar(1), SNOMED_ID varchar(30), LOINC_ID varchar(30), FIELD_TYPE varchar(255), NORMAL_ID bigint, PARENT_ID bigint, SUPPRESSED_YN varchar(1), FORMAT_PATTERN varchar(40), LOGICALLY_NORMAL_YN varchar(1), NEW_BLOCK_YN varchar(1), POSSIBLE_SUPERCEDE_BY_YN varchar(1), HPI_MODIFIER_ID bigint, PATIENT_GENERATE_NORMAL_YN varchar(1), PATIENT_REVERSE_BINDING_YN varchar(1), PATIENT_TEXT_MODE varchar(255), VOLUNTEER_RESULT_INPUT_YN varchar(1), GET_INPUT_YN varchar(1), HAS_CHILDREN_IN_NORMAL_YN varchar(1), DISPLAY_OBS_WHEN_NORMAL_YN varchar(1), primary key (CONCEPT_ID));
create table GST_CLINICAL_EVENT (ID bigint generated by default as identity (start with 1), EVENT_TYPE varchar(255) not null, VERSION integer not null, MED_STATUS_REASON bigint, ANNOTATION varchar(255), PARENT_EVENT_ID bigint, PATIENT bigint, SIBLING_ORDER integer, END_TIMESTAMP timestamp, START_TIMESTAMP timestamp, SUPERCEDED_YN varchar(1), CONTEXT varchar(10), ALLERGY_DISPLAY_VALUE varchar(255), GCN_SEQNO bigint, MED_NAME_ID bigint, ROUTED_MEDID bigint, ROUTED_DOSAGE_FORM_MEDID bigint, MEDID bigint, MED_CONTEXT varchar(255), MED_SUB_CONTEXT varchar(255), PRACTITIONER bigint, PROVIDED_BY_ORGANIZATION bigint, DESCRIPTION varchar(255), PRINT_CONCEPT_YN varchar(1), COORDS_AS_DELIMITED_STRING varchar(255), DOCUMENTED_BY bigint, RECORDED_TIME timestamp, NORMALITY varchar(255), OBSERVED_CONCEPT bigint, PATIENT_ANSWER_YN  varchar(1), HIDDEN_YN varchar(1), PLACEHOLDER_ONLY_YN varchar(1), PRINT_OBSERVATION_YN  varchar(1), DIAGNOSIS_TYPE varchar(255), OBSERVED_DISEASE bigint, BULLETS_SCORED bigint, CATEGORY varchar(255), COUNSEL_TIME integer, CPT bigint, DATA_REVIEW varchar(255), DECISION_MAKING varchar(255), DECISION_TYPE varchar(255), EXAM_LEVEL varchar(255), EXAM_TYPE_ID bigint, FIRST_VISIT bit, HISTORY_LEVEL varchar(255), HPI_LEVEL varchar(255), MANAGEMENT_OPTIONS varchar(255), ORGAN_SYSTEMS_SCORED bigint, PATIENT_VISIT_TYPE varchar(255), PFSH_LEVEL varchar(255), PREVIOUS_VISIT_ID bigint, REFERAL_MADE bit, RISK varchar(255), ROS_LEVEL varchar(255), SCHEDULED_START_TIMESTAMP timestamp, STATUS varchar(255), VISIT_LENGTH_MINUTES integer, OVERRIDE_CPT_ID bigint, CLINIC_PATIENT_ID bigint, RX_ORDER_ID bigint, MED_STATUS bigint, MED_THERAPEUTIC_EFFECT bigint, MODIFIED_GROUP_ID bigint, DISPLAY_ORDER integer, MODIFIED_OBSERVATION_ID bigint, primary key (ID));
create table GST_CLINIC_PATIENT (CLINIC_PATIENT_ID bigint generated by default as identity (start with 1), CLINIC_ID bigint, PATIENT_ID bigint, CLINIC_GEN_PATIENT_ID varchar(255), primary key (CLINIC_PATIENT_ID));
create table GST_CLINIC_PATIENT_VW (CLINIC_PATIENT_ID bigint generated by default as identity (start with 1), BIRTHDATE timestamp, GENDER varchar(20), LAST_NAME varchar(255), FIRST_NAME varchar(255), CLINIC_ID bigint, CLINIC_GEN_PATIENT_ID varchar(255), primary key (CLINIC_PATIENT_ID));
create table GST_COMMON_VALUE (COMMON_VALUE_ID bigint generated by default as identity (start with 1), NAVIGATION_ONLY_YN varchar(1), SENSITIVE_YN varchar(1), ABBREVIATION varchar(255), TEXT varchar(4000), PARENT_ID bigint, PRINT_IN_PARENT_TREE_YN varchar(1), EXPOSE_CHILDREN_YN varchar(1), EXTERNAL_LINK_ICON_YN varchar(1), CODE_SYSTEM varchar(255), CODE_VALUE varchar(255), VERSION varchar(255), DISPLAY_ORDER integer, DISPLAY_VALUE varchar(255), NODE_LEVEL integer, TREE_PATH varchar(255), GRID_ICON_YN varchar(1), MEDIA_ICON_YN varchar(1), HAS_CHILDREN_YN varchar(1), primary key (COMMON_VALUE_ID));
create table GST_COMMON_VALUE_MEDIA (COMMON_VALUE_MEDIA_ID bigint generated by default as identity (start with 1), COMMON_VALUE_ID bigint not null, MIME_TYPE_VENDOR varchar(30), GRID_COLUMNS integer, GRID_ROWS integer, ANGLE integer, CLOCKWISE_YN varchar(1), POINT_A_X_VALUE integer, POINT_A_Y_VALUE integer, POINT_B_X_VALUE integer, POINT_B_Y_VALUE integer, POINT_C_X_VALUE integer, POINT_C_Y_VALUE integer, MEDIA_ID bigint not null, primary key (COMMON_VALUE_MEDIA_ID));
create table GST_COMMON_VALUE_MEDIA_GRID (COMMON_VALUE_MEDIA_ID bigint not null, ROW_NUMBER integer not null, COLUMN_NUMBER integer not null, COMMON_VALUE_CHILD bigint, primary key (COMMON_VALUE_MEDIA_ID, ROW_NUMBER, COLUMN_NUMBER));
create table GST_COMMON_VALUE_URL_LIST (COMMON_VALUE_ID bigint not null, URL_POINTER varchar(255) not null, primary key (COMMON_VALUE_ID, URL_POINTER));
create table GST_CONCEPT (CONCEPT_ID bigint generated by default as identity (start with 1), SIDE_EFFECT_YN varchar(1), CODE_SYSTEM varchar(255), CODE_VALUE varchar(255), VERSION varchar(255), DISPLAY_VALUE varchar(255), DISPLAY_ORDER integer, INCLUDE_IN_SEARCH_YN varchar(1), REPORT_TEXT varchar(400), NODE_LEVEL integer, PARENT_ID bigint, TREE_PATH varchar(255), GRID_ICON_YN varchar(1), MEDIA_ICON_YN varchar(1), CONCEPT_TYPE varchar(10), GENDER varchar(10), PRINT_IN_PARENT_TREE_YN varchar(1), EXPOSE_CHILDREN_YN varchar(1), EXTERNAL_LINK_ICON_YN varchar(1), INACTIVE_DATE timestamp, TEXT_INFO varchar(4000), CONTEXT varchar(10), HAS_CHILDREN_YN varchar(1), NAVIGATION_ONLY_YN varchar(1), CONCEPT_SUBTYPE varchar(10), SUB_SUBTYPE varchar(10), primary key (CONCEPT_ID));
create table GST_CONCEPT_COLLECTION_TRIGGER (CONCEPT_ID bigint not null, COLLECTION_ID bigint not null, DISPLAY_ORDER integer not null, primary key (CONCEPT_ID, DISPLAY_ORDER));
create table GST_CONCEPT_DISEASE_INDICATOR (INDICATOR_ID bigint generated by default as identity (start with 1), QA_FLAG varchar(3), DISEASE_ID bigint, INDICATION_STRENGTH bigint, CLINICAL_CONCEPT_ID bigint, COMMON_VALUE_ID bigint, primary key (INDICATOR_ID));
create table GST_CONCEPT_GROUP_CONCEPT (CONCEPT_ID bigint not null, GROUP_ID bigint not null, primary key (GROUP_ID, CONCEPT_ID));
create table GST_CONCEPT_ITEM_GROUP (CONCEPT_ITEM_GROUP_ID bigint generated by default as identity (start with 1), DESCRIPTION varchar(255), SIBLING_ORDER integer, primary key (CONCEPT_ITEM_GROUP_ID));
create table GST_CONCEPT_MEDIA (CONCEPT_MEDIA_ID bigint generated by default as identity (start with 1), CONCEPT_ID bigint not null, MIME_TYPE_VENDOR varchar(30), GRID_COLUMNS integer, GRID_ROWS integer, ANGLE integer, CLOCKWISE_YN varchar(1), POINT_A_X_VALUE integer, POINT_A_Y_VALUE integer, POINT_B_X_VALUE integer, POINT_B_Y_VALUE integer, POINT_C_X_VALUE integer, POINT_C_Y_VALUE integer, MEDIA_ID bigint not null, primary key (CONCEPT_MEDIA_ID));
create table GST_CONCEPT_MEDIA_GRID (CONCEPT_MEDIA_ID bigint not null, ROW_NUMBER integer not null, COLUMN_NUMBER integer not null, CONCEPT_CHILD bigint, primary key (CONCEPT_MEDIA_ID, ROW_NUMBER, COLUMN_NUMBER));
create table GST_CONCEPT_TEMPLATE (TEMPLATE_ID bigint generated by default as identity (start with 1), VERSION integer not null, CREATED_DATE timestamp, DEFAULT_COLOR_BACKGROUND varchar(255), DEFAULT_COLOR varchar(255), DEFAULT_FONT varchar(255), DEFAULT_PT_SIZE varchar(255), DESCRIPTION varchar(255), MODIFIED_BY bigint, MODIFIED_DATE timestamp, NUMBER_OF_COLUMNS integer, OWNED_BY bigint, TEMPLATE_NAME varchar(255) not null, TEMPLATE_TYPE varchar(255) not null, VISIT_TEMPLATE_YN bit, AGE_GROUP varchar(255), GENDER varchar(255), primary key (TEMPLATE_ID));
create table GST_CONCEPT_TEMPLATE_FIELD (FIELD_ID bigint generated by default as identity (start with 1), X_OFFSET integer, Y_OFFSET integer, LINE_ID bigint not null, DISPLAY_ORDER integer, FIELD_VALUE varchar(255), CONCEPT_ID bigint, primary key (FIELD_ID));
create table GST_CONCEPT_TEMPLATE_LINE (LINE_ID bigint generated by default as identity (start with 1), SECTION_ID bigint not null, DESCRIPTION varchar(255), DISPLAY_ORDER integer, primary key (LINE_ID));
create table GST_CONCEPT_TEMPLATE_SECTION (SECTION_ID bigint generated by default as identity (start with 1), TEMPLATE_ID bigint not null, BACKGROUND_COLOR varchar(255), COLUMN_NUMBER integer, FONT varchar(255), FOREGROUND_COLOR varchar(255), PT_SIZE varchar(255), ROW_NUMBER integer, SECTION_HEADING varchar(255) not null, DISPLAY_ORDER integer, primary key (SECTION_ID));
create table GST_CONCEPT_URL_LIST (CONCEPT_ID bigint not null, URL_POINTER varchar(255) not null, primary key (CONCEPT_ID, URL_POINTER));
create table GST_CURRENT_PROBLEM (CURRENT_PROBLEM_ID bigint generated by default as identity (start with 1), PATIENT_ID bigint not null, CONCEPT_ID bigint not null, PRACTITIONER_ID bigint not null, ANNOTATION varchar(255), CONTEXT varchar(255), ORIGINATING_ID bigint, CREATE_DATETIME timestamp, MODIFIED_DATETIME timestamp, VERSION varchar(255), STATUS bigint, primary key (CURRENT_PROBLEM_ID));
create table GST_CURRENT_PROBLEM_HIST (CURRENT_PROBLEM_HIST_ID bigint generated by default as identity (start with 1), ANNOTATION varchar(255), CREATE_DATETIME timestamp, CURRENT_PROBLEM_STATUS_ID bigint, CURRENT_PROBLEM_ID bigint, primary key (CURRENT_PROBLEM_HIST_ID));
create table GST_CURRENT_PROBLEM_STATUS (CURRENT_PROBLEM_STATUS_ID bigint not null, CREATE_DATETIME timestamp, DISPLAY_VALUE varchar(255), DISPLAY_ORDER integer, primary key (CURRENT_PROBLEM_STATUS_ID));
create table GST_DISEASE (CONCEPT_ID bigint not null, DISEASE_PROCESS varchar(255), ICD9_CODE varchar(255), PROBLEM_LEVEL varchar(255), PARENT_ID bigint, SNOMED_ID varchar(30), COMMONALITY_RANK smallint, BODY_SYSTEM_ID bigint, AGE_GROUP varchar(255), primary key (CONCEPT_ID));
create table GST_DISEASE_DXID (DISEASE_DXID_ID bigint generated by default as identity (start with 1), CONCEPT_ID bigint, DXID integer, MATCH_TYPE varchar(255), PHY_REVIEW_REQUIRED_YN varchar(1), CODE_VALUE varchar(255), REVIEWED_BY varchar(255), REVIEWED_DATE timestamp, primary key (DISEASE_DXID_ID));
create table GST_DISEASE_GSLOINCS (DISEASE_GSLOINCS_ID bigint generated by default as identity (start with 1), CONCEPT_ID bigint not null, TYPE varchar(255), DISPLAY_ORDER integer, GS_LOINC_CD varchar(255), primary key (DISEASE_GSLOINCS_ID));
create table GST_DISEASE_LAB_TEST (DISEASE_LAB_TEST_ID bigint generated by default as identity (start with 1), DISPLAY_ORDER integer, TEST_ID bigint, CONCEPT_ID bigint, DISEASE_LAB_TEST_TYPE varchar(255), primary key (DISEASE_LAB_TEST_ID));
create table GST_DOC_TEMPLATES (PRACTITIONER_ID bigint not null, TEMPLATE_ID bigint not null, primary key (PRACTITIONER_ID, TEMPLATE_ID));
create table GST_DOC_TREATMENT_TEMPLATES (PRACTITIONER_ID bigint not null, TREATMENT_TEMPLATE_ID bigint not null, primary key (PRACTITIONER_ID, TREATMENT_TEMPLATE_ID));
create table GST_DOMAIN_ROLE (ROLE_ID bigint generated by default as identity (start with 1), DESCRIPTION varchar(255), ACTIVE_FROM timestamp, ACTIVE_TO timestamp, PARTY_ID bigint not null, primary key (ROLE_ID));
create table GST_DUMMY_ENTITY (ID bigint generated by default as identity (start with 1), INT_VAL integer, STR_VAL varchar(255), primary key (ID));
create table GST_EXAM_ELEMENT (EXAM_ELEMENT_ID bigint generated by default as identity (start with 1), EXAM_ELEMENT_TYPE varchar(255) not null, PARENT_BULLET_ID bigint, DESCRIPTION varchar(255), SIBLING_ORDER integer, GENDER varchar(255), MIN_CHILDREN_COUNT integer, EXAM_SECTION_ID bigint, CONCEPT_ITEM_GROUP bigint, primary key (EXAM_ELEMENT_ID));
create table GST_EXAM_TYPE (EXAM_TYPE_ID bigint generated by default as identity (start with 1), DESCRIPTION varchar(255), SIBLING_ORDER integer, primary key (EXAM_TYPE_ID));
create table GST_EXAM_TYPE_SECTION (EXAM_SECTION_ID bigint generated by default as identity (start with 1), DESCRIPTION varchar(255), SIBLING_ORDER integer, MIN_CHILDREN_COUNT integer, MIN_FOR_COMPREHENSIVE integer, EXAM_TYPE_ID bigint not null, primary key (EXAM_SECTION_ID));
create table GST_EXPECTED_OUTCOME_DEF (TREATMENT_ITEM_DEF_ID bigint not null, CONCEPT_ID bigint, OPERATOR varchar(255), VALUE numeric, CATEGORY varchar(255), GS_LOINC_CD varchar(255), NORMAL_RANGE_ID bigint, TEST_ID bigint, primary key (TREATMENT_ITEM_DEF_ID));
create table GST_FDB_DUR_ACTION (FDB_DUR_ACTION_ID varchar(255) not null, DESCRIPTION varchar(255), DISPLAY_ORDER bigint, primary key (FDB_DUR_ACTION_ID));
create table GST_FDB_DUR_ACTION_RESULT (FDB_DUR_ACTION_RESULT_ID varchar(255) not null, DESCRIPTION varchar(255), DISPLAY_ORDER bigint, primary key (FDB_DUR_ACTION_RESULT_ID));
create table GST_FINDING_COLLECTION (COLLECTION_ID bigint generated by default as identity (start with 1), VERSION integer not null, PATIENT_AGE_GROUP varchar(255), DISPLAY_VALUE varchar(255), PATIENT_GENDER varchar(255), QUORUM numeric, DISPLAY_ORDER bigint, primary key (COLLECTION_ID));
create table GST_FINDING_COLLECTION_LIST (FINDING_COL_LIST_ID bigint generated by default as identity (start with 1), TRIGGER_VALUE numeric, DISPLAY_ORDER integer, MANDATORY_YN varchar(1), CONCEPT_ID bigint, TRIGGER_YN varchar(255), NORMALITY_CODE varchar(255), COLLECTION_ID bigint, GS_FINDING_NUMBER varchar(255), primary key (FINDING_COL_LIST_ID));
create table GST_FINDING_REFERENCE (REFERENCE_ID bigint generated by default as identity (start with 1), DISPLAY_ORDER integer, DOCUMENT longvarbinary, DISPLAY_VALUE varchar(255), URL varchar(255), SOURCE_TYPE varchar(255), MIME_TYPE varchar(255), FILE_NAME varchar(255), RECORDED_BY bigint, RECORDED_ON timestamp, COLLECTION_ID bigint, primary key (REFERENCE_ID));
create table GST_HCPCS_RIC (HCPCS_RIC_ID varchar(255) not null, DESCRIPTION varchar(255), primary key (HCPCS_RIC_ID));
create table GST_HPI_MODIFIERS (HPI_MODIFIER_ID bigint generated by default as identity (start with 1), DISPLAY_ORDER integer, TREE_PATH varchar(255), PARENT_ID bigint, NODE_LEVEL integer, CONCEPT_ID bigint, HAS_CHILDREN_YN varchar(1), primary key (HPI_MODIFIER_ID));
create table GST_JGK_A (A_KEY_1 varchar(255) not null, primary key (A_KEY_1));
create table GST_JGK_B (B_KEY_1 varchar(255) not null, B_KEY_2 numeric, primary key (B_KEY_1));
create table GST_LAB_ANALYTE (TEST_ID bigint not null, RESULT_AT_ORDER_YN varchar(1), SUPPRESSED_YN varchar(1), AUTO_RESULT_CODE bigint, PRIMARY_TUBE_TYPE varchar(255), PRIMARY_TUBE_TYPE_VOLUME varchar(255), SECONDARY_TUBE_TYPE varchar(255), SECONDARY_TUBE_TYPE_VOLUME varchar(255), AMBIENT_TIME numeric, REFRIGERATED_TIME numeric, FROZEN_TIME numeric, SPECIMEN_SOURCE_CODE varchar(20), SME_ENTERED_AMBIENT_TIME varchar(255), SME_ENTERED_FROZEN_TIME varchar(255), SME_ENTERED_REFRIGERATED_TIME varchar(255), primary key (TEST_ID));
create table GST_LAB_CATEGORY_TEST_LIST (TEST_ID bigint not null, TEST_CATEGORY_ID bigint not null, DISPLAY_ORDER integer not null, primary key (TEST_CATEGORY_ID, DISPLAY_ORDER));
create table GST_LAB_ORDER_DEF (TREATMENT_ITEM_DEF_ID bigint not null, COLLECT_DATE_OFFSET bigint, RELATIVE_TO varchar(255), COLLECTION_TIME bigint, MERIDIEM_TYPE varchar(2), BEFORE_AFTER varchar(255), COLLECT_DATE_OFFSET_UNITS varchar(255), primary key (TREATMENT_ITEM_DEF_ID));
create table GST_LAB_PANEL (TEST_ID bigint not null, primary key (TEST_ID));
create table GST_LAB_PANEL_COMPONENT (PANEL_TEST_ID bigint not null, TEST_ID bigint not null, DISPLAY_ORDER integer not null, primary key (PANEL_TEST_ID, DISPLAY_ORDER));
create table GST_LAB_TEST (TEST_ID bigint generated by default as identity (start with 1), DISPLAY_VALUE varchar(100), TEST_TYPE varchar(10), INACTIVE_DATE timestamp, NOTES varchar(4000), CLINICAL_UTILITIES varchar(4000), TEST_MNEMONIC varchar(20), ORDERABLE_YN varchar(1), PENDING_TEXT_CODE bigint, TURN_AROUND_TIME varchar(100), CPT_ID bigint, SPECIMEN_REJECTION_REASON varchar(255), COLLECTION_INSTRUCTIONS varchar(255), DISPLAY_ORDER integer, primary key (TEST_ID));
create table GST_LAB_TEST_CATEGORY (TEST_CATEGORY_ID bigint generated by default as identity (start with 1), DISPLAY_VALUE varchar(100), DISPLAY_ORDER integer, primary key (TEST_CATEGORY_ID));
create table GST_LAB_TEST_GSLOINC_LIST (TEST_ID bigint not null, GS_LOINC_CD varchar(255) not null, primary key (TEST_ID, GS_LOINC_CD));
create table GST_LAB_TEST_ITEM (LAB_TEST_ITEM_ID bigint generated by default as identity (start with 1), GS_LOINC_CD varchar(255), DISPLAY_ORDER integer, TREATMENT_ITEM_DEF_ID bigint, TEST_ID bigint, primary key (LAB_TEST_ITEM_ID));
create table GST_MEDIA (MEDIA_ID bigint generated by default as identity (start with 1), MIME_TYPE_OLD varchar(255), DESCRIPTION varchar(255), IMAGE_HEIGHT integer, IMAGE_WIDTH integer, BLOB_INFO longvarbinary, MIME_TYPE varchar(255), BLOB_INFO_THUMBNAIL longvarbinary, OLD_MEDIA_ID varchar(30), primary key (MEDIA_ID));
create table GST_MEDICATION_ORDER (TREATMENT_ACTION_ID bigint not null, ROUTE_CUSTOM varchar(255), LOWIU_TEXT varchar(255), END_TEXT varchar(255), MEDID bigint, ORDER_SET_ID bigint, ORDER_STRING_ID bigint, GCN_SEQNO bigint, CONTRAINDICATION_SEVERITY varchar(255), ORDER_TEXT varchar(255), ROUTE_D integer, HIGHD numeric, HIGHDFA numeric, LOWD numeric, LOWDFA numeric, HIGHDFU integer, HIGHDR integer, HIGHDRU integer, HIGHDU integer, HIGHF integer, HIGHI integer, HIGHIU integer, LOWDFU integer, LOWDR integer, LOWDRU integer, LOWDU integer, LOWF integer, LOWI integer, LOWIU integer, ROUTE integer, SLOWF integer, SLOWI integer, SLOWIU integer, INFO4 varchar(255), INFO1 varchar(255), INFO2 varchar(255), INFO3 varchar(255), QUANTITY bigint, REFILLS bigint, SET_TYPE varchar(255), FFT_TYPE varchar(255), SUBSTITUTION_PERMISSIBLE_YN varchar(1), LOWDFAU varchar(255), ROUTE_DESC varchar(255), CLINICAL_EVENT_ID bigint, primary key (TREATMENT_ACTION_ID));
create table GST_MEDICATION_ORDER_DEF (TREATMENT_ITEM_DEF_ID bigint not null, REFILLS bigint, HIGHDR integer, HIGHDRU integer, ORDER_TEXT varchar(255), ORDER_SET_ID bigint, ORDER_STRING_ID bigint, GCN_SEQNO bigint, HIGHDFU integer, HIGHDU integer, HIGHD numeric, HIGHDFA numeric, HIGHF integer, HIGHI integer, HIGHIU integer, INFO4 varchar(255), INFO1 varchar(255), INFO2 varchar(255), INFO3 varchar(255), LOWD numeric, LOWDFA numeric, LOWDFU integer, LOWDR integer, LOWDRU integer, LOWDU integer, LOWF integer, LOWI integer, LOWIU integer, MEDID bigint, QUANTITY bigint, SET_TYPE varchar(255), FFT_TYPE varchar(255), ROUTE_D integer, ROUTE integer, SLOWF integer, SLOWI integer, SUBSTITUTION_PERMISSIBLE_YN varchar(1), END_TEXT varchar(255), primary key (TREATMENT_ITEM_DEF_ID));
create table GST_MED_ALLERGY_INFO (MED_ALLERGY_INFO_ID bigint generated by default as identity (start with 1), VERSION integer not null, ALLERGY_CONCEPT_ID integer, ALLERGY_CONCEPT_TYPE integer, ALLERGY_DESCRIPTION varchar(255), CLINICAL_EVENT_ID bigint, PARENT_INFO_ID bigint, primary key (MED_ALLERGY_INFO_ID));
create table GST_MED_EVENT_FDB_DISEASE (MED_EVENT_FDB_DISEASE_ID bigint generated by default as identity (start with 1), DISPLAY_VALUE varchar(255), DXID bigint, MEDICATION_EVENT_ID bigint, primary key (MED_EVENT_FDB_DISEASE_ID));
create table GST_MED_STATUS (MED_STATUS_ID bigint generated by default as identity (start with 1), DESCRIPTION varchar(255), primary key (MED_STATUS_ID));
create table GST_MED_STATUS_REASON (MED_STATUS_REASON_ID bigint generated by default as identity (start with 1), STATUS bigint, CREATE_DATETIME timestamp, DISPLAY_VALUE varchar(255), DISPLAY_ORDER integer, primary key (MED_STATUS_REASON_ID));
create table GST_MED_THERAPEUTIC_EFFECT (MED_THERAPEUTIC_EFFECT_ID bigint generated by default as identity (start with 1), DESCRIPTION varchar(255), primary key (MED_THERAPEUTIC_EFFECT_ID));
create table GST_NORMAL_PARENT_CHILD (PARENT_ID bigint not null, CHILD_ID bigint not null, primary key (PARENT_ID, CHILD_ID));
create table GST_NORMAL_RANGE (NORMAL_ID bigint generated by default as identity (start with 1), DEFAULT_PLOT_VALUE double, PLOT_HIGH double, PLOT_LOW double, NORMAL_LOW double, NORMAL_HIGH double, NON_NUMERIC_NORMAL varchar(255), NORMAL_TYPE varchar(255), GENDER varchar(255), MAXIMUM_AGE_IN_DAYS integer, MINIMUM_AGE_IN_DAYS integer, UNITS varchar(255), CONCEPT_ID bigint, primary key (NORMAL_ID));
create table GST_ORGANIZATION (PARTY_ID bigint not null, DESCRIPTION varchar(255), NAME varchar(255), primary key (PARTY_ID));
create table GST_ORGANIZATION_ROLE (ROLE_ID bigint not null, primary key (ROLE_ID));
create table GST_PARTY (PARTY_ID bigint generated by default as identity (start with 1), primary key (PARTY_ID));
create table GST_PATIENT (ROLE_ID bigint not null, PHOTO_MEDIA_ID bigint, CONFIDENTIAL_CD varchar(20), EMPLOYER_NAME varchar(50), MEDICARE_NUMBER varchar(20), PERSON_PARTY_ID bigint, PRIMARY_PHYSICIAN_ID bigint, primary key (ROLE_ID));
create table GST_PATIENT_ALLERGY (ALLERGY_ID bigint not null, PATIENT_ID bigint not null, primary key (ALLERGY_ID, PATIENT_ID));
create table GST_PATIENT_INSTRUCTIONS (TREATMENT_ACTION_ID bigint not null, INSTRUCTION longvarchar, primary key (TREATMENT_ACTION_ID));
create table GST_PATIENT_INSTRUCTION_DEF (TREATMENT_ITEM_DEF_ID bigint not null, INSTRUCTION longvarchar, primary key (TREATMENT_ITEM_DEF_ID));
create table GST_PERFORMING_LAB (ANCILLARY_ABBR varchar(255) not null, LAB_ABBR varchar(255) not null, DESCRIPTION varchar(255), PRINT_TEXT_FLAG varchar(255), TEXT_LINE_1 varchar(255), TEXT_LINE_2 varchar(255), TEXT_LINE_3 varchar(255), FIELD_TO_DISPLAY varchar(255), ICON_FILE_POINTER varchar(255), PRINT_CODE varchar(255), primary key (ANCILLARY_ABBR, LAB_ABBR));
create table GST_PERSON (PERSON_PARTY_ID bigint not null, OLD_PERSON_ID varchar(20), GENDER varchar(20), ALIAS_FIRST_NAME varchar(30), ALIAS_LAST_NAME varchar(30), ALIAS_MIDDLE_NAME varchar(30), BIRTHDATE timestamp, FIRST_NAME varchar(30), LAST_NAME varchar(30), MIDDLE_NAME varchar(30), RACE varchar(20), REAL_FIRST_NAME varchar(30), REAL_LAST_NAME varchar(30), REAL_MIDDLE_NAME varchar(30), SUFFIX varchar(30), TITLE varchar(20), INACTIVE_YN varchar(10), SOCIAL_SECURITY_NUMBER varchar(20), ADDRESS_LINE1 varchar(100), ADDRESS_LINE2 varchar(100), ADDRESS_CITY varchar(30), ADDRESS_ZIP varchar(20), ADDRESS_STATE varchar(20), ADDRESS_COUNTRY varchar(20), DECEASED_DATETIME timestamp, EMPI_NUMBER varchar(30), HOME_PHONE_NUMBER varchar(20), BEEPER_NUMBER varchar(20), MOBILE_NUMBER varchar(20), WORK_PHONE_NUMBER varchar(20), EMAIL_ADDRESS varchar(255), TIMEZONE_NAME varchar(64), LOGIN_DATE_TIME timestamp, primary key (PERSON_PARTY_ID));
create table GST_PERSONALIZED_TREE (PERSONALIZED_TREE_ID bigint generated by default as identity (start with 1), NAME varchar(50) not null, DESCRIPTION varchar(255), PRACTITIONER_ID bigint, TREE_TYPE varchar(255), primary key (PERSONALIZED_TREE_ID));
create table GST_PERSONALIZED_TREE_ITEM (PERSONALIZED_TREE_ITEM_ID bigint generated by default as identity (start with 1), PERSONALIZED_TREE_ID bigint, CONCEPT_ID bigint, SHOW_CHILDREN_YN varchar(1), EXPOSE_ME_YN varchar(1), primary key (PERSONALIZED_TREE_ITEM_ID));
create table GST_PERSON_ROLE (ROLE_ID bigint not null, primary key (ROLE_ID));
create table GST_PHONE (PHONE_ID bigint generated by default as identity (start with 1), PHONE_TYPE varchar(255), PHONE_NUMBER varchar(255), DISPLAY_ORDER integer, PARTY_ID bigint, primary key (PHONE_ID));
create table GST_PHYS_SIG (PHYS_SIG_ID bigint generated by default as identity (start with 1), GCN_SEQNO bigint, MED_COUNT integer, MEDID bigint, PHYSICIAN_ID bigint, ORDER_STRING_ID bigint, STR_TYPE varchar(255), ORDER_SET_ID bigint, primary key (PHYS_SIG_ID));
create table GST_PRACTITIONER (ROLE_ID bigint not null, DEF_NORM_OBS bigint, SPECIALTY varchar(255), UPIN varchar(255), DEFAULT_TEMPLATE_ID bigint, DEA_NUMBER varchar(255), LICENSE_NUMBER varchar(255), primary key (ROLE_ID));
create table GST_PROCEDURE (PROCEDURE_ID bigint generated by default as identity (start with 1), SENSITIVE_YN varchar(1), ABBREVIATION varchar(255), TEXT varchar(4000), PARENT_ID bigint, PRINT_IN_PARENT_TREE_YN varchar(1), EXPOSE_CHILDREN_YN varchar(1), EXTERNAL_LINK_ICON_YN varchar(1), CODE_SYSTEM varchar(255), CODE_VALUE varchar(255), VERSION varchar(255), DISPLAY_ORDER integer, DISPLAY_VALUE varchar(255), NODE_LEVEL integer, TREE_PATH varchar(255), GRID_ICON_YN varchar(1), MEDIA_ICON_YN varchar(1), REPORT_TEXT varchar(400), HAS_CHILDREN_YN varchar(1), SNOMED_CONCEPT_ID varchar(20), CPT_CLASS_NAME varchar(30), CPT_ID bigint, PROCEDURE_TYPE varchar(20), ABNORMAL_YN varchar(1), AGE_GROUP varchar(255), COMMONALITY_RANK smallint, FIELD_TYPE varchar(255), GENDER varchar(10), NEUTRAL_YN varchar(1), NORMAL_YN varchar(1), NORMAL_ID bigint, RESULT_TYPE varchar(255), FORMAT_PATTERN varchar(40), primary key (PROCEDURE_ID));
create table GST_PROCEDURE_ORDER (TREATMENT_ACTION_ID bigint not null, TREATMENT_PROCEDURE_ID bigint, REFERRED_TO bigint, SCHEDULED_TIMESTAMP timestamp, primary key (TREATMENT_ACTION_ID));
create table GST_PROCEDURE_ORDER_DEF (TREATMENT_ITEM_DEF_ID bigint not null, TREATMENT_PROCEDURE_ID bigint, primary key (TREATMENT_ITEM_DEF_ID));
create table GST_PROCEDURE_URL_LIST (PROCEDURE_ID bigint not null, URL_POINTER varchar(255) not null, primary key (PROCEDURE_ID, URL_POINTER));
create table GST_PROCEDURE_VALID_VALUE (TREATMENT_PROCEDURE_ID bigint not null, COMMON_VALUE_ID bigint not null, VALUE_DISPLAY_ORDER integer not null, primary key (TREATMENT_PROCEDURE_ID, VALUE_DISPLAY_ORDER));
create table GST_RAD_CATEGORY_DISEASES (CLINICAL_CONDITION_ID bigint not null, CONCEPT_ID bigint not null, primary key (CLINICAL_CONDITION_ID, CONCEPT_ID));
create table GST_RAD_CLINICAL_CONDITION (CLINICAL_CONDITION_ID bigint generated by default as identity (start with 1), TOPOLOGY_ID bigint, TITLE varchar(255), DISPLAY_ORDER integer, AGE_GROUP varchar(255), GENDER varchar(255), primary key (CLINICAL_CONDITION_ID));
create table GST_RAD_CLIN_COND_SOURCE (RAD_CLIN_COND_SOURCE_ID bigint generated by default as identity (start with 1), DISPLAY_ORDER integer, DOCUMENT longvarbinary, DISPLAY_VALUE varchar(255), URL varchar(255), SOURCE_TYPE varchar(255), MIME_TYPE varchar(255), FILE_NAME varchar(255), RECORDED_BY bigint, RECORDED_ON timestamp, CLINICAL_CONDITION_ID bigint, primary key (RAD_CLIN_COND_SOURCE_ID));
create table GST_RAD_CONCEPT (RAD_CONCEPT_ID bigint generated by default as identity (start with 1), CONCEPT_TYPE varchar(10), DISPLAY_ORDER integer, DISPLAY_VALUE varchar(255), TREE_PATH varchar(255), EXPOSE_CHILDREN_YN varchar(1), HAS_CHILDREN_YN varchar(1), ABBREVIATION varchar(10), NODE_LEVEL integer, GENDER varchar(10), CODE_SYSTEM varchar(255), CODE_VALUE varchar(255), VERSION varchar(255), AGE_GROUP varchar(255), SNOMED_ID varchar(30), PARENT_ID bigint, primary key (RAD_CONCEPT_ID));
create table GST_RAD_MEDICATION (RAD_CONCEPT_ID bigint not null, GCN varchar(255), primary key (RAD_CONCEPT_ID));
create table GST_RAD_MODALITY (RAD_CONCEPT_ID bigint not null, primary key (RAD_CONCEPT_ID));
create table GST_RAD_ORDERABLE_ITEM (RAD_ORD_ITEM_ID bigint generated by default as identity (start with 1), LONG_DESCRIPTION varchar(255), SHORT_DESCRIPTION varchar(255), DISPLAY_ORDER integer, primary key (RAD_ORD_ITEM_ID));
create table GST_RAD_ORDERABLE_MEDICATION (RAD_ORD_ITEM_ID bigint not null, RAD_CONCEPT_ID bigint not null, DISPLAY_ORDER integer not null, primary key (RAD_ORD_ITEM_ID, DISPLAY_ORDER));
create table GST_RAD_ORDERABLE_MODALITY (RAD_ORD_ITEM_ID bigint not null, RAD_CONCEPT_ID bigint not null, DISPLAY_ORDER integer not null, primary key (RAD_ORD_ITEM_ID, DISPLAY_ORDER));
create table GST_RAD_ORDERABLE_TOPOLOGY (RAD_ORD_ITEM_ID bigint not null, RAD_CONCEPT_ID bigint not null, DISPLAY_ORDER integer not null, primary key (RAD_ORD_ITEM_ID, DISPLAY_ORDER));
create table GST_RAD_ORDERABLE_VIEW (RAD_ORD_ITEM_ID bigint not null, RAD_CONCEPT_ID bigint not null, DISPLAY_ORDER integer not null, primary key (RAD_ORD_ITEM_ID, DISPLAY_ORDER));
create table GST_RAD_ORDERING_PROCEDURE (RAD_ORD_PROCEDURE_ID bigint generated by default as identity (start with 1), DISPLAY_ORDER integer, APPROPRIATE_RATING bigint, COMMENTS varchar(1000), RAD_ORD_ITEM_ID bigint, INSTRUCTION longvarchar, RAD_VARIANT_ID bigint, RRL varchar(255), primary key (RAD_ORD_PROCEDURE_ID));
create table GST_RAD_ORDER_ACTION (TREATMENT_ACTION_ID bigint not null, COMMENTS varchar(1000), RAD_ORD_ITEM_ID bigint, primary key (TREATMENT_ACTION_ID));
create table GST_RAD_ORDER_DEFINITION (TREATMENT_ITEM_DEF_ID bigint not null, RAD_ORD_ITEM_ID bigint, primary key (TREATMENT_ITEM_DEF_ID));
create table GST_RAD_TOPOLOGY (RAD_CONCEPT_ID bigint not null, primary key (RAD_CONCEPT_ID));
create table GST_RAD_VARIANT (RAD_VARIANT_ID bigint generated by default as identity (start with 1), DISPLAY_ORDER integer, DESCRIPTION varchar(255), CLINICAL_CONDITION_ID bigint, primary key (RAD_VARIANT_ID));
create table GST_RAD_VIEW (RAD_CONCEPT_ID bigint not null, primary key (RAD_CONCEPT_ID));
create table GST_RESULT_VALUE (VALUE_ID bigint generated by default as identity (start with 1), OBSERVATION_ID bigint, COORDS_AS_DELIMITED_STRING varchar(255), ANNOTATION_TEXT varchar(255), CODED_VALUE bigint, NUMERIC_VALUE numeric, TEXT_VALUE varchar(255), VALUE_TYPE varchar(255), DISPLAY_ORDER bigint, MIME_TYPE varchar(255), BIN_DATA longvarbinary, DOCUMENTED_BY bigint, RECORDED_TIME timestamp, QA_FLAG varchar(255), END_DATE timestamp, START_DATE timestamp, NUMERIC_VALUE_1 numeric, NUMERIC_VALUE_2 numeric, NUMERIC_VALUE_3 numeric, MED_EVENT bigint, ALLERGY_EVENT_ID bigint, DATE_VALUE timestamp, PROCEDURE_ID bigint, OUTCOME_ID bigint, TREATMENT_ITEM_DEF_ID bigint, primary key (VALUE_ID));
create table GST_ROLE_RELATIONSHIP (PARTY_ID bigint generated by default as identity (start with 1), FROM_ID bigint not null, TO_ID bigint not null, ROLE_ID bigint, primary key (PARTY_ID));
create table GST_SPECIMEN_SOURCE (SPECIMEN_SOURCE_CODE varchar(20) not null, DISPLAY_VALUE varchar(255), primary key (SPECIMEN_SOURCE_CODE));
create table GST_SPONSOR_SITE (ROLE_ID bigint not null, ADDRESS_LINE1 varchar(100), ADDRESS_LINE2 varchar(100), ADDRESS_CITY varchar(30), ADDRESS_ZIP varchar(20), ADDRESS_STATE varchar(20), ADDRESS_COUNTRY varchar(20), primary key (ROLE_ID));
create table GST_TREATMENT_ACTION (TREATMENT_ACTION_ID bigint generated by default as identity (start with 1), ANNOTATION varchar(255), PERFORMED_AT_DATE timestamp, PERFORMED_BY bigint, STATUS varchar(255), TREATMENT_STEP_ID bigint, DISPLAY_ORDER integer, TREATMENT_ACTION_TYPE varchar(255), primary key (TREATMENT_ACTION_ID));
create table GST_TREATMENT_ACTION_LOG (TREATMENT_ACTION_LOG_ID bigint generated by default as identity (start with 1), ANNOTATION varchar(255), FDB_DUR_ACTION_ID varchar(255), FDB_DUR_ACTION_RESULT_ID varchar(255), LOG_BY bigint, LOG_TIME timestamp, MESSAGE varchar(255), TREATMENT_ACTION_ID bigint, primary key (TREATMENT_ACTION_LOG_ID));
create table GST_TREATMENT_ITEM_DEFINITION (TREATMENT_ITEM_DEF_ID bigint generated by default as identity (start with 1), DESCRIPTION varchar(255), TREATMENT_STEP_DEF_ID bigint, DISPLAY_ORDER integer, ANNOTATION varchar(255), TREATMENT_ITEM_DEF_TYPE varchar(255), primary key (TREATMENT_ITEM_DEF_ID));
create table GST_TREATMENT_LAB_ORDER (TREATMENT_ACTION_ID bigint not null, ORDER_ID varchar(255), primary key (TREATMENT_ACTION_ID));
create table GST_TREATMENT_PLAN (TREATMENT_PLAN_ID bigint generated by default as identity (start with 1), ANNOTATION varchar(255), PATIENT bigint, STATUS varchar(255), VISIT_ID bigint, DISPLAY_ORDER integer, primary key (TREATMENT_PLAN_ID));
create table GST_TREATMENT_PLAN_OUTCOME (TREATMENT_ACTION_ID bigint not null, CONCEPT_ID bigint, OPERATOR varchar(255), VALUE numeric, CATEGORY varchar(255), GS_LOINC_CD varchar(255), NORMAL_RANGE_ID bigint, TEST_ID bigint, RECORDED_BY bigint, RECORDED_DATE timestamp, OUTCOME_TYPE varchar(255), ACTUAL_OUTCOME_ID bigint, PARENT_OUTCOME_ID bigint, primary key (TREATMENT_ACTION_ID));
create table GST_TREATMENT_PROBLEM (TREATMENT_PROBLEM_ID bigint generated by default as identity (start with 1), CONCEPT_ID bigint, TREATMENT_PLAN_ID bigint, DISPLAY_ORDER integer, primary key (TREATMENT_PROBLEM_ID));
create table GST_TREATMENT_STEP (TREATMENT_STEP_ID bigint generated by default as identity (start with 1), ACTUAL_END_DATE timestamp, ACTUAL_START_DATE timestamp, ANNOTATION varchar(255), ASSESED_TIME timestamp, ASSESMENT_METHOD varchar(255), PLANNED_END_DATE timestamp, PLANNED_START_DATE timestamp, STATUS varchar(255), TREATMENT_PLAN_ID bigint, NAME varchar(255), DISPLAY_ORDER integer, primary key (TREATMENT_STEP_ID));
create table GST_TREATMENT_STEP_DEFINITION (TREATMENT_STEP_DEF_ID bigint generated by default as identity (start with 1), DESCRIPTION varchar(255), EXPECTED_DURATION integer, TREATMENT_TEMPLATE_ID bigint, DURATION_UNITS varchar(255), DURATION bigint, DURATION_OPERATOR varchar(255), DURATION_REFERENCE varchar(255), DISPLAY_ORDER integer, ANNOTATION varchar(4000), primary key (TREATMENT_STEP_DEF_ID));
create table GST_TREATMENT_TEMPLATE (TREATMENT_TEMPLATE_ID bigint generated by default as identity (start with 1), VERSION integer not null, ACTIVE_FROM_DATE timestamp, ACTIVE_TO_DATE timestamp, DESCRIPTION varchar(255), CREATED_DATE_TIME timestamp, MODIFIED_BY bigint, MODIFIED_DATE_TIME timestamp, OWNED_BY bigint, PRIVATE_TEMPLATE_YN varchar(1), PATIENT_AGE_GROUP varchar(255), PATIENT_GENDER varchar(255), REVIEW_DURATION_UNIT varchar(255), REVIEW_FREQUENCY varchar(255), REVIEW_DURATION varchar(255), DISPLAY_ORDER integer, HIDE_AUTHOR_DETAILS_YN varchar(1), MANDATORY_FOR_DISEASE_YN varchar(1), TREATMENT_TEMPLATE_CAT_ID bigint, primary key (TREATMENT_TEMPLATE_ID));
create table GST_TREATMENT_TEMPLATE_CAT (TREATMENT_TEMPLATE_CAT_ID bigint generated by default as identity (start with 1), DISPLAY_ORDER integer, DESCRIPTION varchar(255), CREATED_BY bigint, CREATED_DATE timestamp, MODIFIED_BY bigint, MODIFIED_DATE timestamp, primary key (TREATMENT_TEMPLATE_CAT_ID));
create table GST_TREATMENT_TEMPLATE_CONCEPT (TREATMENT_TEMPLATE_ID bigint not null, CONCEPT_ID bigint not null, TEMPLATE_DISPLAY_ORDER integer not null, primary key (TREATMENT_TEMPLATE_ID, TEMPLATE_DISPLAY_ORDER));
create table GST_TREATMENT_TEMPLATE_DISEASE (TREATMENT_TEMPLATE_ID bigint not null, DISEASE_ID bigint not null, TEMPLATE_DISPLAY_ORDER integer not null, primary key (TREATMENT_TEMPLATE_ID, TEMPLATE_DISPLAY_ORDER));
create table GST_TREATMENT_TEMPLATE_SOURCE (TREATMENT_TEMPLATE_SOURCE_ID bigint generated by default as identity (start with 1), DISPLAY_ORDER integer, TREATMENT_TEMPLATE_ID bigint, DOCUMENT longvarbinary, DISPLAY_VALUE varchar(255), URL varchar(255), SOURCE_TYPE varchar(255), MIME_TYPE varchar(255), FILE_NAME varchar(255), RECORDED_BY bigint, RECORDED_ON timestamp, primary key (TREATMENT_TEMPLATE_SOURCE_ID));
create table GST_TRIGGER_CONCEPT_COLLECTION (TRIGGER_COLLECTION_ID bigint generated by default as identity (start with 1), VISIT_ID bigint, COLLECTION_ID bigint, TRIGGER_COUNT integer, CONCEPT_COLLECTION_STATUS varchar(255), DISPLAY_ORDER integer, primary key (TRIGGER_COLLECTION_ID));
create table GST_USERNAME (ROLE_ID bigint not null, PERSON_PARTY_ID bigint not null, INTERIM_NAME varchar(20), PASSWORD varchar(30) not null, PASSWORD_EXPIRATION_DATE timestamp, PASSWORD_REMINDER varchar(30), PASSWORD_STATUS varchar(20), USER_EXPIRATION_DATE timestamp, USERNAME varchar(30) not null, USER_TYPE varchar(20), primary key (ROLE_ID), unique (USERNAME));
create table GST_US_STATE (US_STATE_ID varchar(255) not null, MODIFIED_DATETIME timestamp, CREATE_DATETIME timestamp, DISPLAY_VALUE varchar(255), DISPLAY_ORDER integer, primary key (US_STATE_ID));
create table GST_VALID_VALUE (CONCEPT_ID bigint not null, COMMON_VALUE_ID bigint not null, VALUE_DISPLAY_ORDER integer not null, primary key (CONCEPT_ID, VALUE_DISPLAY_ORDER));
create table GST_ZIPCODE_INFO (ZIPCODE_INFO_ID bigint generated by default as identity (start with 1), AREA_CODE varchar(255), CITY varchar(255), STATE varchar(255), TIMEZONE varchar(255), ZIPCODE varchar(255), CREATE_DATETIME timestamp, MODIFIED_DATETIME timestamp, primary key (ZIPCODE_INFO_ID));
create table GS_LOINC (GS_LOINC_CD varchar(255) not null, ANALYTE_ABBR varchar(255), DESCRIPTION varchar(255), DISPLAY_NORMALS_YN varchar(255), LOINC_NUM varchar(255), PLOT_YN varchar(255), PREVIOUS_RESULT_SIGNIFICANT varchar(255), RESULT_FORMAT varchar(255), TYPE_OF_TEST varchar(255), STANDARD_YN varchar(255), CPT varchar(255), CPT_MAP_YN varchar(255), MODIFIED_DATETIME timestamp, HIGH_VALUE_ICD9_CODE varchar(255), LOW_VALUE_ICD9_CODE varchar(255), ABNORMAL_ICD9_CODE varchar(255), primary key (GS_LOINC_CD));
create table GS_REF_RANGE (GS_LOINC_CD varchar(255) not null, SEQUENCE_NUMBER bigint not null, HIGH_RANGE double, LOW_RANGE double, RANGE_TYPE varchar(255), RANGE_VALUE varchar(255), primary key (GS_LOINC_CD, SEQUENCE_NUMBER));
create table GS_UNITS (GS_LOINC_CD varchar(255) not null, SEQUENCE_NUMBER double not null, UNITS varchar(255), primary key (GS_LOINC_CD, SEQUENCE_NUMBER));
create table HCPCS_ACTION_CODE (HCPCS_ACTION_CODE_ID varchar(255) not null, DESCRIPTION varchar(255), primary key (HCPCS_ACTION_CODE_ID));
create table HCPCS_BE_TOS (HCPCS_BE_TOS_ID varchar(255) not null, DESCRIPTION varchar(255), primary key (HCPCS_BE_TOS_ID));
create table HCPCS_BODY_SYSTEM (HCPCS_BODY_SYSTEM_ID varchar(255) not null, DESCRIPTION varchar(255), primary key (HCPCS_BODY_SYSTEM_ID));
create table HCPCS_CATEGORY (HCPCS_CATEGORY_ID bigint generated by default as identity (start with 1), SHORT_DESCRIPTION varchar(255), LONG_DESCRIPTION varchar(255), PREFIX varchar(255), RANGE_LOW varchar(255), RANGE_HIGH varchar(255), SIBLING_ORDER integer, CREATED_DATE timestamp, MODIFIED_DATE timestamp, PARENT_ID bigint, FGCOLOR varchar(255), BGCOLOR varchar(255), primary key (HCPCS_CATEGORY_ID));
create table HCPCS_CMS_TOS (HCPCS_CMS_TOS_ID varchar(255) not null, DESCRIPTION varchar(255), primary key (HCPCS_CMS_TOS_ID));
create table HCPCS_CODE (HCPCS_CODE_ID bigint generated by default as identity (start with 1), CODE varchar(255), LONG_DESC varchar(255), SHORT_DESC varchar(255), STATUTE varchar(255), ASC_PAYMENT_GRP_CODE varchar(255), ASC_PAYMENT_GRP_EFF_DATE timestamp, MOG_EFF_DATE timestamp, CODE_ADDED_DATE timestamp, ACTION_EFF_DATE timestamp, CODE_TERMINATION_DATE timestamp, ANEST_BASE_UNIT_QTY integer, HCPCS_MULTI_PIC varchar(255), COVERAGE_CODE varchar(255), ACTION_CODE varchar(255), PROC_NOTE_NUMBER varchar(255), MOG_PMT_GRP_CODE varchar(255), BE_TOS varchar(255), MOG_PMT_POLICY_IND_CODE varchar(255), primary key (HCPCS_CODE_ID));
create table HCPCS_CODE_CIM_REF (HCPCS_CODE_ID bigint not null, SECTION_NUMBER varchar(255) not null, primary key (HCPCS_CODE_ID, SECTION_NUMBER));
create table HCPCS_CODE_CMS_TOS (HCPCS_CODE_ID bigint not null, HCPCS_CMS_TOS_ID varchar(255) not null, primary key (HCPCS_CODE_ID, HCPCS_CMS_TOS_ID));
create table HCPCS_CODE_LABCERT (HCPCS_CODE_ID bigint not null, HCPCS_LAB_CERT_CODE_ID varchar(255) not null, primary key (HCPCS_CODE_ID, HCPCS_LAB_CERT_CODE_ID));
create table HCPCS_CODE_MCM_REF (HCPCS_CODE_ID bigint not null, SECTION_NUMBER varchar(255) not null, primary key (HCPCS_CODE_ID, SECTION_NUMBER));
create table HCPCS_CODE_PIC (HCPCS_CODE_ID bigint not null, HCPCS_PIC_ID varchar(255) not null, primary key (HCPCS_CODE_ID, HCPCS_PIC_ID));
create table HCPCS_CODE_XREF (HCPCS_CODE_ID bigint not null, XREF varchar(255) not null, primary key (HCPCS_CODE_ID, XREF));
create table HCPCS_COVERAGE_CODE (HCPCS_COVERAGE_CODE_ID varchar(255) not null, DESCRIPTION varchar(255), COLOR varchar(255), primary key (HCPCS_COVERAGE_CODE_ID));
create table HCPCS_LAB_CERT_CODE (HCPCS_LAB_CERT_CODE_ID varchar(255) not null, PARENT_ID varchar(255), DESCRIPTION varchar(255), primary key (HCPCS_LAB_CERT_CODE_ID));
create table HCPCS_MODIFIER_CIM_REF (HCPCS_MODIFIER_CODE_ID bigint not null, SECTION_NUMBER varchar(255) not null, primary key (HCPCS_MODIFIER_CODE_ID, SECTION_NUMBER));
create table HCPCS_MODIFIER_CODE (HCPCS_MODIFIER_CODE_ID bigint generated by default as identity (start with 1), CODE varchar(255), LONG_DESC varchar(255), SHORT_DESC varchar(255), COVERAGE_CODE varchar(255), PROC_NOTE_NUMBER varchar(255), ANEST_BASE_UNIT_QTY integer, CODE_ADDED_DATE timestamp, ACTION_EFFECTIVE_DATE timestamp, CODE_TERMINATION_DATE timestamp, ACTION_CODE varchar(255), primary key (HCPCS_MODIFIER_CODE_ID));
create table HCPCS_MODIFIER_MCM_REF (HCPCS_MODIFIER_CODE_ID bigint not null, SECTION_NUMBER varchar(255));
create table HCPCS_MODIFIER_XREF (HCPCS_MODIFIER_CODE_ID bigint not null, XREF varchar(255) not null, primary key (HCPCS_MODIFIER_CODE_ID, XREF));
create table HCPCS_MOG_PMT_GRP_CODE (HCPCS_MOG_PMT_GRP_CODE_ID varchar(255) not null, DESCRIPTION varchar(255), SEQUENCE_NUM integer, LEVEL_OF_INTENSITY varchar(255), HCPCS_BODY_SYSTEM_ID varchar(255), primary key (HCPCS_MOG_PMT_GRP_CODE_ID));
create table HCPCS_MOG_PMT_POLICY_IND_CODE (HCPCS_MOG_PMT_POLICY_IND_CODE varchar(255) not null, DESCRIPTION varchar(255), primary key (HCPCS_MOG_PMT_POLICY_IND_CODE));
create table HCPCS_MULTI_PIC (HCPCS_MULTI_PIC_ID varchar(255) not null, DESCRIPTION varchar(255), primary key (HCPCS_MULTI_PIC_ID));
create table HCPCS_PIC (HCPCS_PIC_ID varchar(255) not null, DESCRIPTION varchar(255), primary key (HCPCS_PIC_ID));
create table HCPCS_TREE (HCPCS_TREE_ID bigint generated by default as identity (start with 1), SHORT_DESC varchar(255), LONG_DESC varchar(255), SIBLING_ORDER integer, CATEGORY bigint, HCPCS_CODE bigint, PARENT_ID bigint, TREE_NAME varchar(255), primary key (HCPCS_TREE_ID));
create table INTERIM_REPORT (INTERIM_NAME varchar(255) not null, DESCRIPTION varchar(255), JAVA_CLASS_HTML_HDR varchar(255), JAVA_CLASS_PDF_HDR varchar(255), OWNED_BY varchar(255), CREATED_DATE timestamp, MODIFIED_DATE timestamp, MODIFIED_BY varchar(255), VERSION integer, primary key (INTERIM_NAME));
create table LAB_ORDER_CODE (ANCILLARY_ABBR varchar(255) not null, ORDER_CODE varchar(255) not null, DESCRIPTION varchar(255), ORDER_CODE_TYPE varchar(255), ORDERABLE varchar(255), COLLECTION_INFO varchar(255), STORAGE_INFO varchar(255), SPECIMEN_SOURCE varchar(255), RESULTING_METHOD varchar(255), LOINC_NUM varchar(255), primary key (ANCILLARY_ABBR, ORDER_CODE));
create table ORDER_REASON_LIST (ORDER_CODE varchar(255) not null, ORDER_ID varchar(255) not null, PERSON_ID varchar(255) not null, REASON_CD varchar(255) not null, SPECIMEN_ID varchar(255) not null, CD_TYPE varchar(255), primary key (ORDER_CODE, ORDER_ID, PERSON_ID, REASON_CD, SPECIMEN_ID));
create table Person (PERSON_ID varchar(255) not null, ADDRESS_CITY varchar(255), ADDRESS_COUNTRY varchar(255), ADDRESS_LINE1 varchar(255), ADDRESS_LINE2 varchar(255), ADDRESS_STATE varchar(255), ADDRESS_ZIP varchar(255), ALIAS_FIRST_NAME varchar(255), ALIAS_LAST_NAME varchar(255), ALIAS_MIDDLE_NAME varchar(255), BEEPER_NUMBER varchar(255), BIRTHDATE date, DECEASED_DATETIME timestamp, EMAIL_ADDRESS varchar(255), FIRST_NAME varchar(255), GENDER varchar(255), HOME_PHONE_NUMBER varchar(255), LAST_NAME varchar(255), MIDDLE_NAME varchar(255), MOBILE_NUMBER varchar(255), RACE varchar(255), REAL_FIRST_NAME varchar(255), REAL_LAST_NAME varchar(255), SOCIAL_SECURITY_NUMBER varchar(255), SUFFIX varchar(255), TITLE varchar(255), UPIN varchar(255), WORK_PHONE_NUMBER varchar(255), EMPI_NUMBER varchar(255), INACTIVE_YN varchar(255), NORMAL_TEXT_OBS varchar(255), PARTY_ID bigint, primary key (PERSON_ID));
create table REQ_REPORT_FORM (REQUISITION_NAME varchar(255) not null, DESCRIPTION varchar(255), INTERIM_NAME varchar(255), OWNED_BY varchar(255), CREATED_DATE timestamp, MODIFIED_DATE timestamp, primary key (REQUISITION_NAME));
create table SPECIMEN_LINE (INTERIM_NAME varchar(255) not null, COLLECT_DATE_COLOR varchar(255), COLLECT_DATE_FONT varchar(255), COLLECT_DATE_JUSTIFICATION varchar(255), COLLECT_DATE_PT_SIZE double, COLLECT_DATE_WIDTH double, COLLECT_DATE_X_OFFSET double, COLLECT_TIME_COLOR varchar(255), COLLECT_TIME_FONT varchar(255), COLLECT_TIME_JUSTIFICATION varchar(255), COLLECT_TIME_PT_SIZE double, COLLECT_TIME_WIDTH double, COLLECT_TIME_X_OFFSET double, SPECIMEN_ID_COLOR varchar(255), SPECIMEN_ID_FONT varchar(255), SPECIMEN_ID_JUSTIFICATION varchar(255), SPECIMEN_ID_PT_SIZE double, SPECIMEN_ID_WIDTH double, SPECIMEN_ID_X_OFFSET double, SPECIMEN_TYPE_COLOR varchar(255), SPECIMEN_TYPE_FONT varchar(255), SPECIMEN_TYPE_JUSTIFICATION varchar(255), SPECIMEN_TYPE_PT_SIZE double, SPECIMEN_TYPE_WIDTH double, SPECIMEN_TYPE_X_OFFSET double, primary key (INTERIM_NAME));
create table TEXT_LINE (INTERIM_NAME varchar(255) not null, TEXT_COLOR varchar(255), TEXT_FONT varchar(255), TEXT_JUSTIFICATION varchar(255), TEXT_PT_SIZE double, TEXT_WIDTH double, TEXT_X_OFFSET double, primary key (INTERIM_NAME));
create table icd9 (CODE varchar(255) not null, LONG_VALUE varchar(255), SHORT_VALUE varchar(255), STATUS double, VALID_MEDICARE_YN varchar(255), DISPLAY_TEXT varchar(255), CODE_STATUS varchar(255), CLASS_NAME varchar(255), primary key (CODE));
create table icd9_class (CLASS_NAME varchar(255) not null, DESCRIPTION varchar(255), PARENT_CLASS_NAME varchar(255), STATUS bigint, primary key (CLASS_NAME));
alter table GST_ADDRESS add constraint FK98A47B7D3B4F2980 foreign key (PARTY_ID) references GST_PARTY;
alter table GST_ALLERGY_EVENT_INGRED add constraint FK44E6344AC743EEA1 foreign key (MED_ALLERGY_INFO_ID) references GST_MED_ALLERGY_INFO;
alter table GST_ALLERGY_FDB_XREF add constraint FK455D19ACC2E29BD6 foreign key (CONCEPT_ID) references GST_CLINICAL_CONCEPT;
alter table GST_APPLIANCE_ORDER add constraint FKEB6EE4A5D994B13B foreign key (HCPCS_CODE) references HCPCS_CODE;
alter table GST_APPLIANCE_ORDER add constraint FKEB6EE4A569EBA068 foreign key (TREATMENT_ACTION_ID) references GST_TREATMENT_ACTION;
alter table GST_APPLIANCE_ORDER_DEF add constraint FK1A9E414BD994B13B foreign key (HCPCS_CODE) references HCPCS_CODE;
alter table GST_APPLIANCE_ORDER_DEF add constraint FK1A9E414BCA10FE35 foreign key (TREATMENT_ITEM_DEF_ID) references GST_TREATMENT_ITEM_DEFINITION;
alter table GST_BILLABLE_ITEM add constraint FKD4B9939A730DC967 foreign key (VISIT_ID) references GST_CLINICAL_EVENT;
alter table GST_BILLABLE_ITEM add constraint FKD4B9939ACBD3E677 foreign key (CONCEPT_ID) references GST_DISEASE;
alter table GST_BODY_SYSTEM add constraint FKBDE2CE95652E87B1 foreign key (BODY_SYSTEM_MODIFIER_ID) references GST_HPI_MODIFIERS;
alter table GST_CLINIC add constraint FK871C1F18589F98 foreign key (SITE) references GST_SPONSOR_SITE;
alter table GST_CLINIC add constraint FK871C1F60EB2C87 foreign key (ROLE_ID) references GST_ORGANIZATION_ROLE;
create index concept_hpi_modifier_idx on GST_CLINICAL_CONCEPT (HPI_MODIFIER_ID);
create index PCC_PARENT_PCC_IDX on GST_CLINICAL_CONCEPT (PARENT_ID);
create index concept_normal_id_idx on GST_CLINICAL_CONCEPT (NORMAL_ID);
create index concept_body_system_idx on GST_CLINICAL_CONCEPT (BODY_SYSTEM_ID);
alter table GST_CLINICAL_CONCEPT add constraint FK4A071B93DC58A3E2 foreign key (NORMAL_ID) references GST_COMMON_VALUE;
alter table GST_CLINICAL_CONCEPT add constraint FK4A071B93C3D8A1F6 foreign key (BODY_SYSTEM_ID) references GST_BODY_SYSTEM;
alter table GST_CLINICAL_CONCEPT add constraint FK4A071B93F296D926 foreign key (HPI_MODIFIER_ID) references GST_HPI_MODIFIERS;
alter table GST_CLINICAL_CONCEPT add constraint FK4A071B93A0E36F63 foreign key (CONCEPT_ID) references GST_CONCEPT;
alter table GST_CLINICAL_CONCEPT add constraint FK4A071B93B1B24E54 foreign key (PARENT_ID) references GST_CLINICAL_CONCEPT;
create index clinical_event_patient_idx on GST_CLINICAL_EVENT (PATIENT);
alter table GST_CLINICAL_EVENT add constraint FKB48B6685BA9ED399 foreign key (CPT) references CPT;
alter table GST_CLINICAL_EVENT add constraint FKB48B6685B8CCA5AF foreign key (PREVIOUS_VISIT_ID) references GST_CLINICAL_EVENT;
alter table GST_CLINICAL_EVENT add constraint FKB48B6685533A5828 foreign key (DOCUMENTED_BY) references GST_PARTY;
alter table GST_CLINICAL_EVENT add constraint FKB48B66851A56C975 foreign key (OBSERVED_CONCEPT) references GST_CLINICAL_CONCEPT;
alter table GST_CLINICAL_EVENT add constraint FKB48B6685B54E1A86 foreign key (MODIFIED_OBSERVATION_ID) references GST_CLINICAL_EVENT;
alter table GST_CLINICAL_EVENT add constraint FKB48B66854F9B9CA foreign key (MODIFIED_GROUP_ID) references GST_CLINICAL_EVENT;
alter table GST_CLINICAL_EVENT add constraint FKB48B668549E5FC60 foreign key (MED_THERAPEUTIC_EFFECT) references GST_MED_THERAPEUTIC_EFFECT;
alter table GST_CLINICAL_EVENT add constraint FKB48B6685EB34144B foreign key (MED_STATUS) references GST_MED_STATUS;
alter table GST_CLINICAL_EVENT add constraint FKB48B6685A0E03BD7 foreign key (PARENT_EVENT_ID) references GST_CLINICAL_EVENT;
alter table GST_CLINICAL_EVENT add constraint FKB48B66854E388B2A foreign key (OBSERVED_DISEASE) references GST_DISEASE;
alter table GST_CLINICAL_EVENT add constraint FKB48B66855886F610 foreign key (PATIENT) references GST_PATIENT;
alter table GST_CLINICAL_EVENT add constraint FKB48B6685B11D078 foreign key (OVERRIDE_CPT_ID) references CPT;
alter table GST_CLINICAL_EVENT add constraint FKB48B6685320C8777 foreign key (RX_ORDER_ID) references GST_MEDICATION_ORDER;
alter table GST_CLINICAL_EVENT add constraint FKB48B6685A65089EE foreign key (PRACTITIONER) references GST_PRACTITIONER;
alter table GST_CLINICAL_EVENT add constraint FKB48B668589CC1CC2 foreign key (PROVIDED_BY_ORGANIZATION) references GST_ORGANIZATION_ROLE;
alter table GST_CLINICAL_EVENT add constraint FKB48B668573BA7A68 foreign key (MED_STATUS_REASON) references GST_MED_STATUS_REASON;
alter table GST_CLINICAL_EVENT add constraint FKB48B66853B4E9D6C foreign key (EXAM_TYPE_ID) references GST_EXAM_TYPE;
alter table GST_CLINICAL_EVENT add constraint FKB48B66856490A8CF foreign key (CLINIC_PATIENT_ID) references GST_CLINIC_PATIENT;
alter table GST_CLINIC_PATIENT add constraint FK8223AAC520FC2FF4 foreign key (CLINIC_ID) references GST_CLINIC;
alter table GST_CLINIC_PATIENT add constraint FK8223AAC5CD6F7A0 foreign key (PATIENT_ID) references GST_PATIENT;
alter table GST_CLINIC_PATIENT_VW add constraint FK749F127B20FC2FF4 foreign key (CLINIC_ID) references GST_CLINIC;
alter table GST_CLINIC_PATIENT_VW add constraint FK749F127B6490A8CF foreign key (CLINIC_PATIENT_ID) references GST_CLINIC_PATIENT;
create index COMMON_VALUE_TREE_PATH_IDX on GST_COMMON_VALUE (TREE_PATH);
create index COMMON_VALUE_PARENT_VALUE_IDX on GST_COMMON_VALUE (PARENT_ID);
alter table GST_COMMON_VALUE add constraint FK2D554BF449A51D3F foreign key (PARENT_ID) references GST_COMMON_VALUE;
create index cvMedia_common_value_idx on GST_COMMON_VALUE_MEDIA (COMMON_VALUE_ID);
create index cvMedia_media_idx on GST_COMMON_VALUE_MEDIA (MEDIA_ID);
alter table GST_COMMON_VALUE_MEDIA add constraint FK9EDB5FB9691A456F foreign key (COMMON_VALUE_ID) references GST_PROCEDURE;
alter table GST_COMMON_VALUE_MEDIA add constraint FK9EDB5FB989C00AEC foreign key (COMMON_VALUE_ID) references GST_COMMON_VALUE;
alter table GST_COMMON_VALUE_MEDIA add constraint FK9EDB5FB9F735032B foreign key (MEDIA_ID) references GST_MEDIA;
create index cv_grid_child_idx on GST_COMMON_VALUE_MEDIA_GRID (COMMON_VALUE_CHILD);
alter table GST_COMMON_VALUE_MEDIA_GRID add constraint FKCF74C80CE8A453E5 foreign key (COMMON_VALUE_MEDIA_ID) references GST_COMMON_VALUE_MEDIA;
alter table GST_COMMON_VALUE_MEDIA_GRID add constraint FKCF74C80C1ED7BCE9 foreign key (COMMON_VALUE_CHILD) references GST_COMMON_VALUE;
alter table GST_COMMON_VALUE_URL_LIST add constraint FK5865A97989C00AEC foreign key (COMMON_VALUE_ID) references GST_COMMON_VALUE;
create index CONCEPT_TREE_PATH_IDX on GST_CONCEPT (TREE_PATH);
alter table GST_CONCEPT add constraint FK15BC59F18FB321E1 foreign key (PARENT_ID) references GST_CONCEPT;
alter table GST_CONCEPT_COLLECTION_TRIGGER add constraint FK2930C205D97770EB foreign key (COLLECTION_ID) references GST_FINDING_COLLECTION;
alter table GST_CONCEPT_COLLECTION_TRIGGER add constraint FK2930C205C2E29BD6 foreign key (CONCEPT_ID) references GST_CLINICAL_CONCEPT;
create index CONCEPT_DISEASE_DISEASE_IDX on GST_CONCEPT_DISEASE_INDICATOR (DISEASE_ID);
create index CONCEPT_DISEASE_CONCEPT_IDX on GST_CONCEPT_DISEASE_INDICATOR (CLINICAL_CONCEPT_ID);
create index CONCEPT_DISEASE_VALUE_IDX on GST_CONCEPT_DISEASE_INDICATOR (COMMON_VALUE_ID);
alter table GST_CONCEPT_DISEASE_INDICATOR add constraint FK7F4D4BFE89C00AEC foreign key (COMMON_VALUE_ID) references GST_COMMON_VALUE;
alter table GST_CONCEPT_DISEASE_INDICATOR add constraint FK7F4D4BFE4EE45082 foreign key (CLINICAL_CONCEPT_ID) references GST_CLINICAL_CONCEPT;
alter table GST_CONCEPT_DISEASE_INDICATOR add constraint FK7F4D4BFEB10526E3 foreign key (DISEASE_ID) references GST_DISEASE;
alter table GST_CONCEPT_GROUP_CONCEPT add constraint FKFF2A4E9AC2E29BD6 foreign key (CONCEPT_ID) references GST_CLINICAL_CONCEPT;
alter table GST_CONCEPT_GROUP_CONCEPT add constraint FKFF2A4E9AEE4B26D2 foreign key (GROUP_ID) references GST_CONCEPT_ITEM_GROUP;
create index conceptMedia_concept_idx on GST_CONCEPT_MEDIA (CONCEPT_ID);
create index conceptMedia_media_idx on GST_CONCEPT_MEDIA (MEDIA_ID);
alter table GST_CONCEPT_MEDIA add constraint FK568D3BF6A0E36F63 foreign key (CONCEPT_ID) references GST_CONCEPT;
alter table GST_CONCEPT_MEDIA add constraint FK568D3BF6F735032B foreign key (MEDIA_ID) references GST_MEDIA;
create index concept_grid_child_idx on GST_CONCEPT_MEDIA_GRID (CONCEPT_CHILD);
alter table GST_CONCEPT_MEDIA_GRID add constraint FK10A409EFAB40D596 foreign key (CONCEPT_CHILD) references GST_CONCEPT;
alter table GST_CONCEPT_MEDIA_GRID add constraint FK10A409EFAF200C98 foreign key (CONCEPT_MEDIA_ID) references GST_CONCEPT_MEDIA;
alter table GST_CONCEPT_TEMPLATE add constraint FK48133085786C49D foreign key (OWNED_BY) references GST_PARTY;
alter table GST_CONCEPT_TEMPLATE add constraint FK4813308986111F9 foreign key (MODIFIED_BY) references GST_PARTY;
create index concept_template_field_idx on GST_CONCEPT_TEMPLATE_FIELD (CONCEPT_ID);
alter table GST_CONCEPT_TEMPLATE_FIELD add constraint FKAD9D8E3C2E29BD6 foreign key (CONCEPT_ID) references GST_CLINICAL_CONCEPT;
alter table GST_CONCEPT_TEMPLATE_FIELD add constraint FKAD9D8E3EE41DA31 foreign key (LINE_ID) references GST_CONCEPT_TEMPLATE_LINE;
alter table GST_CONCEPT_TEMPLATE_LINE add constraint FKBE4BD2CBBD5FB743 foreign key (SECTION_ID) references GST_CONCEPT_TEMPLATE_SECTION;
alter table GST_CONCEPT_TEMPLATE_SECTION add constraint FK648C5C8E75590757 foreign key (TEMPLATE_ID) references GST_CONCEPT_TEMPLATE;
alter table GST_CONCEPT_URL_LIST add constraint FK1B32081CA0E36F63 foreign key (CONCEPT_ID) references GST_CONCEPT;
alter table GST_CURRENT_PROBLEM add constraint FK2DBC70422035BA82 foreign key (STATUS) references GST_CURRENT_PROBLEM_STATUS;
alter table GST_CURRENT_PROBLEM add constraint FK2DBC7042A0E36F63 foreign key (CONCEPT_ID) references GST_CONCEPT;
alter table GST_CURRENT_PROBLEM add constraint FK2DBC7042E7975734 foreign key (PRACTITIONER_ID) references GST_PRACTITIONER;
alter table GST_CURRENT_PROBLEM add constraint FK2DBC7042CD6F7A0 foreign key (PATIENT_ID) references GST_PATIENT;
alter table GST_CURRENT_PROBLEM_HIST add constraint FK9C85F8FFB0BE3F foreign key (CURRENT_PROBLEM_ID) references GST_CURRENT_PROBLEM;
alter table GST_CURRENT_PROBLEM_HIST add constraint FK9C85F8FF99930C32 foreign key (CURRENT_PROBLEM_STATUS_ID) references GST_CURRENT_PROBLEM_STATUS;
create index DISEASE_PARENT_DISEASE_IDX on GST_DISEASE (PARENT_ID);
create index disease_body_system_idx on GST_DISEASE (BODY_SYSTEM_ID);
alter table GST_DISEASE add constraint FK40ACD105C3D8A1F6 foreign key (BODY_SYSTEM_ID) references GST_BODY_SYSTEM;
alter table GST_DISEASE add constraint FK40ACD105A0E36F63 foreign key (CONCEPT_ID) references GST_CONCEPT;
alter table GST_DISEASE add constraint FK40ACD10574C52E9E foreign key (ICD9_CODE) references icd9;
alter table GST_DISEASE add constraint FK40ACD105BAA398F5 foreign key (PARENT_ID) references GST_DISEASE;
create index disease_gsloincs_concept_idx on GST_DISEASE_GSLOINCS (CONCEPT_ID);
alter table GST_DISEASE_GSLOINCS add constraint FKFD474A3E944B67D5 foreign key (GS_LOINC_CD) references GS_LOINC;
alter table GST_DISEASE_GSLOINCS add constraint FKFD474A3ECBD3E677 foreign key (CONCEPT_ID) references GST_DISEASE;
alter table GST_DISEASE_LAB_TEST add constraint FK3C52E21ECBD3E677 foreign key (CONCEPT_ID) references GST_DISEASE;
alter table GST_DISEASE_LAB_TEST add constraint FK3C52E21E8307CE50 foreign key (TEST_ID) references GST_LAB_TEST;
alter table GST_DOC_TEMPLATES add constraint FK44A6899BE7975734 foreign key (PRACTITIONER_ID) references GST_PRACTITIONER;
alter table GST_DOC_TEMPLATES add constraint FK44A6899B75590757 foreign key (TEMPLATE_ID) references GST_CONCEPT_TEMPLATE;
alter table GST_DOC_TREATMENT_TEMPLATES add constraint FKFF03C3F4BC90E668 foreign key (TREATMENT_TEMPLATE_ID) references GST_TREATMENT_TEMPLATE;
alter table GST_DOC_TREATMENT_TEMPLATES add constraint FKFF03C3F4E7975734 foreign key (PRACTITIONER_ID) references GST_PRACTITIONER;
alter table GST_DOMAIN_ROLE add constraint FKCCFA9A3A3B4F2980 foreign key (PARTY_ID) references GST_PARTY;
create index EXAM_BULLET_SECTION_IDX on GST_EXAM_ELEMENT (EXAM_SECTION_ID);
alter table GST_EXAM_ELEMENT add constraint FK85F600B338E37481 foreign key (CONCEPT_ITEM_GROUP) references GST_CONCEPT_ITEM_GROUP;
alter table GST_EXAM_ELEMENT add constraint FK85F600B39A74BBCD foreign key (PARENT_BULLET_ID) references GST_EXAM_ELEMENT;
alter table GST_EXAM_ELEMENT add constraint FK85F600B3B185CCCE foreign key (EXAM_SECTION_ID) references GST_EXAM_TYPE_SECTION;
create index EXAM_SECTION_EXAM_IDX on GST_EXAM_TYPE_SECTION (EXAM_TYPE_ID);
alter table GST_EXAM_TYPE_SECTION add constraint FK54E417493B4E9D6C foreign key (EXAM_TYPE_ID) references GST_EXAM_TYPE;
alter table GST_EXPECTED_OUTCOME_DEF add constraint FK6B27C948944B67D5 foreign key (GS_LOINC_CD) references GS_LOINC;
alter table GST_EXPECTED_OUTCOME_DEF add constraint FK6B27C948A0E36F63 foreign key (CONCEPT_ID) references GST_CONCEPT;
alter table GST_EXPECTED_OUTCOME_DEF add constraint FK6B27C9488307CE50 foreign key (TEST_ID) references GST_LAB_TEST;
alter table GST_EXPECTED_OUTCOME_DEF add constraint FK6B27C948CA10FE35 foreign key (TREATMENT_ITEM_DEF_ID) references GST_TREATMENT_ITEM_DEFINITION;
alter table GST_EXPECTED_OUTCOME_DEF add constraint FK6B27C948C7B85A74 foreign key (NORMAL_RANGE_ID) references GST_NORMAL_RANGE;
alter table GST_FINDING_COLLECTION_LIST add constraint FK887C2672D97770EB foreign key (COLLECTION_ID) references GST_FINDING_COLLECTION;
alter table GST_FINDING_COLLECTION_LIST add constraint FK887C2672C2E29BD6 foreign key (CONCEPT_ID) references GST_CLINICAL_CONCEPT;
alter table GST_FINDING_REFERENCE add constraint FK83DD963ED97770EB foreign key (COLLECTION_ID) references GST_FINDING_COLLECTION;
alter table GST_FINDING_REFERENCE add constraint FK83DD963E433F4EB2 foreign key (RECORDED_BY) references GST_PARTY;
alter table GST_HPI_MODIFIERS add constraint FK9C520EC7C2E29BD6 foreign key (CONCEPT_ID) references GST_CLINICAL_CONCEPT;
alter table GST_HPI_MODIFIERS add constraint FK9C520EC7C92C3551 foreign key (PARENT_ID) references GST_HPI_MODIFIERS;
alter table GST_JGK_B add constraint FKCED860DA9F68CEAA foreign key (B_KEY_1) references GST_JGK_A;
create index lab_analyte_auto_result_idx on GST_LAB_ANALYTE (AUTO_RESULT_CODE);
create index lab_analyte_specimen_idx on GST_LAB_ANALYTE (SPECIMEN_SOURCE_CODE);
alter table GST_LAB_ANALYTE add constraint FK3CB34EC9D5FBC2AE foreign key (AUTO_RESULT_CODE) references GST_COMMON_VALUE;
alter table GST_LAB_ANALYTE add constraint FK3CB34EC91A84C754 foreign key (SPECIMEN_SOURCE_CODE) references GST_SPECIMEN_SOURCE;
alter table GST_LAB_ANALYTE add constraint FK3CB34EC98307CE50 foreign key (TEST_ID) references GST_LAB_TEST;
alter table GST_LAB_CATEGORY_TEST_LIST add constraint FK6FC33F7390D7FF55 foreign key (TEST_CATEGORY_ID) references GST_LAB_TEST_CATEGORY;
alter table GST_LAB_CATEGORY_TEST_LIST add constraint FK6FC33F738307CE50 foreign key (TEST_ID) references GST_LAB_TEST;
alter table GST_LAB_ORDER_DEF add constraint FK2AC0ABEBCA10FE35 foreign key (TREATMENT_ITEM_DEF_ID) references GST_TREATMENT_ITEM_DEFINITION;
alter table GST_LAB_PANEL add constraint FKD5B621FB8307CE50 foreign key (TEST_ID) references GST_LAB_TEST;
alter table GST_LAB_PANEL_COMPONENT add constraint FK1B644B998593BF9B foreign key (PANEL_TEST_ID) references GST_LAB_PANEL;
alter table GST_LAB_PANEL_COMPONENT add constraint FK1B644B997B0C12E4 foreign key (TEST_ID) references GST_LAB_ANALYTE;
create index lab_test_pending_code_idx on GST_LAB_TEST (PENDING_TEXT_CODE);
alter table GST_LAB_TEST add constraint FK51394D9B617E7586 foreign key (PENDING_TEXT_CODE) references GST_COMMON_VALUE;
alter table GST_LAB_TEST add constraint FK51394D9B69ED8CA5 foreign key (CPT_ID) references CPT;
alter table GST_LAB_TEST_GSLOINC_LIST add constraint FK1159E512944B67D5 foreign key (GS_LOINC_CD) references GS_LOINC;
alter table GST_LAB_TEST_GSLOINC_LIST add constraint FK1159E5128307CE50 foreign key (TEST_ID) references GST_LAB_TEST;
alter table GST_LAB_TEST_ITEM add constraint FKFD6B2737944B67D5 foreign key (GS_LOINC_CD) references GS_LOINC;
alter table GST_LAB_TEST_ITEM add constraint FKFD6B27378307CE50 foreign key (TEST_ID) references GST_LAB_TEST;
alter table GST_LAB_TEST_ITEM add constraint FKFD6B2737F1DDC2F1 foreign key (TREATMENT_ITEM_DEF_ID) references GST_LAB_ORDER_DEF;
create index media_old_media_idx on GST_MEDIA (OLD_MEDIA_ID);
alter table GST_MEDICATION_ORDER add constraint FK82BCCC35BB919292 foreign key (CLINICAL_EVENT_ID) references GST_CLINICAL_EVENT;
alter table GST_MEDICATION_ORDER add constraint FK82BCCC3569EBA068 foreign key (TREATMENT_ACTION_ID) references GST_TREATMENT_ACTION;
alter table GST_MEDICATION_ORDER_DEF add constraint FK28DE0DBCA10FE35 foreign key (TREATMENT_ITEM_DEF_ID) references GST_TREATMENT_ITEM_DEFINITION;
alter table GST_MED_ALLERGY_INFO add constraint FK210AD457A57D686D foreign key (CLINICAL_EVENT_ID) references GST_CLINICAL_EVENT;
alter table GST_MED_ALLERGY_INFO add constraint FK210AD4574974E63E foreign key (PARENT_INFO_ID) references GST_MED_ALLERGY_INFO;
alter table GST_MED_EVENT_FDB_DISEASE add constraint FK8E859326E17C256 foreign key (MEDICATION_EVENT_ID) references GST_CLINICAL_EVENT;
alter table GST_MED_STATUS_REASON add constraint FKAFE0FE4733899A78 foreign key (STATUS) references GST_MED_STATUS;
alter table GST_NORMAL_PARENT_CHILD add constraint FKBF637BA89935B4A2 foreign key (CHILD_ID) references GST_CLINICAL_CONCEPT;
alter table GST_NORMAL_PARENT_CHILD add constraint FKBF637BA8B1B24E54 foreign key (PARENT_ID) references GST_CLINICAL_CONCEPT;
alter table GST_NORMAL_RANGE add constraint FK2F1159BCC2E29BD6 foreign key (CONCEPT_ID) references GST_CLINICAL_CONCEPT;
alter table GST_ORGANIZATION add constraint FK2161632A3B4F2980 foreign key (PARTY_ID) references GST_PARTY;
alter table GST_ORGANIZATION_ROLE add constraint FKD011386BFF3BF718 foreign key (ROLE_ID) references GST_DOMAIN_ROLE;
alter table GST_PATIENT add constraint FKADE0CA8EDE86C041 foreign key (PRIMARY_PHYSICIAN_ID) references GST_PRACTITIONER;
alter table GST_PATIENT add constraint FKADE0CA8E71D40D29 foreign key (ROLE_ID) references GST_PERSON_ROLE;
alter table GST_PATIENT add constraint FKADE0CA8EA59B8FC1 foreign key (PERSON_PARTY_ID) references GST_PERSON;
alter table GST_PATIENT_ALLERGY add constraint FK8C70F2AF3C39B863 foreign key (ALLERGY_ID) references GST_ALLERGY;
alter table GST_PATIENT_ALLERGY add constraint FK8C70F2AFCD6F7A0 foreign key (PATIENT_ID) references GST_PATIENT;
alter table GST_PATIENT_INSTRUCTIONS add constraint FK622043B669EBA068 foreign key (TREATMENT_ACTION_ID) references GST_TREATMENT_ACTION;
alter table GST_PATIENT_INSTRUCTION_DEF add constraint FK8AE14E3CA10FE35 foreign key (TREATMENT_ITEM_DEF_ID) references GST_TREATMENT_ITEM_DEFINITION;
create index person_old_person_idx on GST_PERSON (OLD_PERSON_ID);
alter table GST_PERSON add constraint FK1657A28CDF11AF2A foreign key (PERSON_PARTY_ID) references GST_PARTY;
alter table GST_PERSONALIZED_TREE add constraint FKD91B9B16E7975734 foreign key (PRACTITIONER_ID) references GST_PRACTITIONER;
alter table GST_PERSONALIZED_TREE_ITEM add constraint FK49D50E9CF2C7CB5A foreign key (PERSONALIZED_TREE_ID) references GST_PERSONALIZED_TREE;
alter table GST_PERSONALIZED_TREE_ITEM add constraint FK49D50E9CC2E29BD6 foreign key (CONCEPT_ID) references GST_CLINICAL_CONCEPT;
alter table GST_PERSON_ROLE add constraint FKAD654649FF3BF718 foreign key (ROLE_ID) references GST_DOMAIN_ROLE;
alter table GST_PHONE add constraint FKCF2D6F373B4F2980 foreign key (PARTY_ID) references GST_PARTY;
alter table GST_PRACTITIONER add constraint FKFD5BC11171D40D29 foreign key (ROLE_ID) references GST_PERSON_ROLE;
alter table GST_PRACTITIONER add constraint FKFD5BC1113E8CE259 foreign key (DEFAULT_TEMPLATE_ID) references GST_CONCEPT_TEMPLATE;
alter table GST_PRACTITIONER add constraint FKFD5BC11143D01D66 foreign key (DEF_NORM_OBS) references GST_COMMON_VALUE;
create index PROCEDURE_TREE_PATH_IDX on GST_PROCEDURE (TREE_PATH);
create index PROCEDURE_PARENT_VALUE_IDX on GST_PROCEDURE (PARENT_ID);
alter table GST_PROCEDURE add constraint FK8C0BA01CDC58A3E2 foreign key (NORMAL_ID) references GST_COMMON_VALUE;
alter table GST_PROCEDURE add constraint FK8C0BA01C69ED8CA5 foreign key (CPT_ID) references CPT;
alter table GST_PROCEDURE add constraint FK8C0BA01C28FF57C2 foreign key (PARENT_ID) references GST_PROCEDURE;
alter table GST_PROCEDURE_ORDER add constraint FK6C9E0D4BD0D9B560 foreign key (TREATMENT_PROCEDURE_ID) references GST_PROCEDURE;
alter table GST_PROCEDURE_ORDER add constraint FK6C9E0D4BCFAE966C foreign key (REFERRED_TO) references GST_PERSON;
alter table GST_PROCEDURE_ORDER add constraint FK6C9E0D4B69EBA068 foreign key (TREATMENT_ACTION_ID) references GST_TREATMENT_ACTION;
alter table GST_PROCEDURE_ORDER_DEF add constraint FKA91CA6F1D0D9B560 foreign key (TREATMENT_PROCEDURE_ID) references GST_PROCEDURE;
alter table GST_PROCEDURE_ORDER_DEF add constraint FKA91CA6F1CA10FE35 foreign key (TREATMENT_ITEM_DEF_ID) references GST_TREATMENT_ITEM_DEFINITION;
alter table GST_PROCEDURE_URL_LIST add constraint FK6B078251F5A40F9 foreign key (PROCEDURE_ID) references GST_PROCEDURE;
alter table GST_PROCEDURE_VALID_VALUE add constraint FKBFBF38BD0D9B560 foreign key (TREATMENT_PROCEDURE_ID) references GST_PROCEDURE;
alter table GST_PROCEDURE_VALID_VALUE add constraint FKBFBF38B89C00AEC foreign key (COMMON_VALUE_ID) references GST_COMMON_VALUE;
alter table GST_RAD_CATEGORY_DISEASES add constraint FK36E89AB7CBD3E677 foreign key (CONCEPT_ID) references GST_DISEASE;
alter table GST_RAD_CATEGORY_DISEASES add constraint FK36E89AB78742DB2C foreign key (CLINICAL_CONDITION_ID) references GST_RAD_CLINICAL_CONDITION;
alter table GST_RAD_CLINICAL_CONDITION add constraint FKE9578C90779EFFC1 foreign key (TOPOLOGY_ID) references GST_RAD_TOPOLOGY;
alter table GST_RAD_CLIN_COND_SOURCE add constraint FK4B33D2688742DB2C foreign key (CLINICAL_CONDITION_ID) references GST_RAD_CLINICAL_CONDITION;
alter table GST_RAD_CLIN_COND_SOURCE add constraint FK4B33D268433F4EB2 foreign key (RECORDED_BY) references GST_PARTY;
create index RAD_TREE_PATH_IDX on GST_RAD_CONCEPT (TREE_PATH);
alter table GST_RAD_CONCEPT add constraint FK4ECC7B27BEEBA9F1 foreign key (PARENT_ID) references GST_RAD_CONCEPT;
alter table GST_RAD_MEDICATION add constraint FKD03F21906C825DD foreign key (RAD_CONCEPT_ID) references GST_RAD_CONCEPT;
alter table GST_RAD_MODALITY add constraint FK886519E26C825DD foreign key (RAD_CONCEPT_ID) references GST_RAD_CONCEPT;
alter table GST_RAD_ORDERABLE_MEDICATION add constraint FK533D9F6711EBAE13 foreign key (RAD_ORD_ITEM_ID) references GST_RAD_ORDERABLE_ITEM;
alter table GST_RAD_ORDERABLE_MEDICATION add constraint FK533D9F676C825DD foreign key (RAD_CONCEPT_ID) references GST_RAD_CONCEPT;
alter table GST_RAD_ORDERABLE_MODALITY add constraint FK5BC7217911EBAE13 foreign key (RAD_ORD_ITEM_ID) references GST_RAD_ORDERABLE_ITEM;
alter table GST_RAD_ORDERABLE_MODALITY add constraint FK5BC721796C825DD foreign key (RAD_CONCEPT_ID) references GST_RAD_CONCEPT;
alter table GST_RAD_ORDERABLE_TOPOLOGY add constraint FK482EE10711EBAE13 foreign key (RAD_ORD_ITEM_ID) references GST_RAD_ORDERABLE_ITEM;
alter table GST_RAD_ORDERABLE_TOPOLOGY add constraint FK482EE1076C825DD foreign key (RAD_CONCEPT_ID) references GST_RAD_CONCEPT;
alter table GST_RAD_ORDERABLE_VIEW add constraint FK8FB66D3D11EBAE13 foreign key (RAD_ORD_ITEM_ID) references GST_RAD_ORDERABLE_ITEM;
alter table GST_RAD_ORDERABLE_VIEW add constraint FK8FB66D3D6C825DD foreign key (RAD_CONCEPT_ID) references GST_RAD_CONCEPT;
alter table GST_RAD_ORDERING_PROCEDURE add constraint FK691483C911EBAE13 foreign key (RAD_ORD_ITEM_ID) references GST_RAD_ORDERABLE_ITEM;
alter table GST_RAD_ORDERING_PROCEDURE add constraint FK691483C9B7E594BD foreign key (RAD_VARIANT_ID) references GST_RAD_VARIANT;
alter table GST_RAD_ORDER_ACTION add constraint FK3359CEE811EBAE13 foreign key (RAD_ORD_ITEM_ID) references GST_RAD_ORDERABLE_ITEM;
alter table GST_RAD_ORDER_ACTION add constraint FK3359CEE869EBA068 foreign key (TREATMENT_ACTION_ID) references GST_TREATMENT_ACTION;
alter table GST_RAD_ORDER_DEFINITION add constraint FK97C8D50511EBAE13 foreign key (RAD_ORD_ITEM_ID) references GST_RAD_ORDERABLE_ITEM;
alter table GST_RAD_ORDER_DEFINITION add constraint FK97C8D505CA10FE35 foreign key (TREATMENT_ITEM_DEF_ID) references GST_TREATMENT_ITEM_DEFINITION;
alter table GST_RAD_TOPOLOGY add constraint FK74CCD9706C825DD foreign key (RAD_CONCEPT_ID) references GST_RAD_CONCEPT;
alter table GST_RAD_VARIANT add constraint FK243A11448742DB2C foreign key (CLINICAL_CONDITION_ID) references GST_RAD_CLINICAL_CONDITION;
alter table GST_RAD_VIEW add constraint FKC3EB02266C825DD foreign key (RAD_CONCEPT_ID) references GST_RAD_CONCEPT;
alter table GST_RESULT_VALUE add constraint FK316CFCA67E8CD39B foreign key (PROCEDURE_ID) references GST_PROCEDURE_ORDER;
alter table GST_RESULT_VALUE add constraint FK316CFCA6454B30BC foreign key (OUTCOME_ID) references GST_TREATMENT_PLAN_OUTCOME;
alter table GST_RESULT_VALUE add constraint FK316CFCA687D1C3B8 foreign key (CODED_VALUE) references GST_COMMON_VALUE;
alter table GST_RESULT_VALUE add constraint FK316CFCA6533A5828 foreign key (DOCUMENTED_BY) references GST_PARTY;
alter table GST_RESULT_VALUE add constraint FK316CFCA689CAD46D foreign key (MED_EVENT) references GST_CLINICAL_EVENT;
alter table GST_RESULT_VALUE add constraint FK316CFCA6B9BA7C14 foreign key (OBSERVATION_ID) references GST_CLINICAL_EVENT;
alter table GST_RESULT_VALUE add constraint FK316CFCA690E11EAB foreign key (TREATMENT_ITEM_DEF_ID) references GST_PROCEDURE_ORDER_DEF;
alter table GST_RESULT_VALUE add constraint FK316CFCA6AAD236A0 foreign key (ALLERGY_EVENT_ID) references GST_CLINICAL_EVENT;
alter table GST_ROLE_RELATIONSHIP add constraint FK369D3CAB3C0EEF3 foreign key (TO_ID) references GST_DOMAIN_ROLE;
alter table GST_ROLE_RELATIONSHIP add constraint FK369D3CAFF3BF718 foreign key (ROLE_ID) references GST_DOMAIN_ROLE;
alter table GST_ROLE_RELATIONSHIP add constraint FK369D3CA89BDA364 foreign key (FROM_ID) references GST_DOMAIN_ROLE;
alter table GST_SPONSOR_SITE add constraint FK78EE8B6360EB2C87 foreign key (ROLE_ID) references GST_ORGANIZATION_ROLE;
alter table GST_TREATMENT_ACTION add constraint FK15070E74BC81E39 foreign key (PERFORMED_BY) references GST_PERSON;
alter table GST_TREATMENT_ACTION add constraint FK15070E7428B49428 foreign key (TREATMENT_STEP_ID) references GST_TREATMENT_STEP;
alter table GST_TREATMENT_ACTION_LOG add constraint FK55F0AD9798D3C35 foreign key (LOG_BY) references GST_PERSON;
alter table GST_TREATMENT_ACTION_LOG add constraint FK55F0AD9D3E20C0 foreign key (FDB_DUR_ACTION_RESULT_ID) references GST_FDB_DUR_ACTION_RESULT;
alter table GST_TREATMENT_ACTION_LOG add constraint FK55F0AD9BCC61C41 foreign key (FDB_DUR_ACTION_ID) references GST_FDB_DUR_ACTION;
alter table GST_TREATMENT_ACTION_LOG add constraint FK55F0AD98DDAB2AF foreign key (TREATMENT_ACTION_ID) references GST_MEDICATION_ORDER;
alter table GST_TREATMENT_ACTION_LOG add constraint FK55F0AD969EBA068 foreign key (TREATMENT_ACTION_ID) references GST_TREATMENT_ACTION;
alter table GST_TREATMENT_ITEM_DEFINITION add constraint FKC5CB38163FB78D5 foreign key (TREATMENT_STEP_DEF_ID) references GST_TREATMENT_STEP_DEFINITION;
alter table GST_TREATMENT_LAB_ORDER add constraint FKFCB6A4DE69EBA068 foreign key (TREATMENT_ACTION_ID) references GST_TREATMENT_ACTION;
alter table GST_TREATMENT_PLAN add constraint FKDEC016E75886F610 foreign key (PATIENT) references GST_PATIENT;
alter table GST_TREATMENT_PLAN add constraint FKDEC016E7730DC967 foreign key (VISIT_ID) references GST_CLINICAL_EVENT;
alter table GST_TREATMENT_PLAN_OUTCOME add constraint FK3F7179DA944B67D5 foreign key (GS_LOINC_CD) references GS_LOINC;
alter table GST_TREATMENT_PLAN_OUTCOME add constraint FK3F7179DA61C14F71 foreign key (PARENT_OUTCOME_ID) references GST_TREATMENT_PLAN_OUTCOME;
alter table GST_TREATMENT_PLAN_OUTCOME add constraint FK3F7179DAA0E36F63 foreign key (CONCEPT_ID) references GST_CONCEPT;
alter table GST_TREATMENT_PLAN_OUTCOME add constraint FK3F7179DA69EBA068 foreign key (TREATMENT_ACTION_ID) references GST_TREATMENT_ACTION;
alter table GST_TREATMENT_PLAN_OUTCOME add constraint FK3F7179DA433F4EB2 foreign key (RECORDED_BY) references GST_PARTY;
alter table GST_TREATMENT_PLAN_OUTCOME add constraint FK3F7179DA8307CE50 foreign key (TEST_ID) references GST_LAB_TEST;
alter table GST_TREATMENT_PLAN_OUTCOME add constraint FK3F7179DAC7B85A74 foreign key (NORMAL_RANGE_ID) references GST_NORMAL_RANGE;
alter table GST_TREATMENT_PLAN_OUTCOME add constraint FK3F7179DAE24FF80D foreign key (ACTUAL_OUTCOME_ID) references GST_TREATMENT_PLAN_OUTCOME;
alter table GST_TREATMENT_PROBLEM add constraint FKBEA73A01CBD3E677 foreign key (CONCEPT_ID) references GST_DISEASE;
alter table GST_TREATMENT_PROBLEM add constraint FKBEA73A017C205B08 foreign key (TREATMENT_PLAN_ID) references GST_TREATMENT_PLAN;
alter table GST_TREATMENT_STEP add constraint FKDEC1928A7C205B08 foreign key (TREATMENT_PLAN_ID) references GST_TREATMENT_PLAN;
alter table GST_TREATMENT_STEP_DEFINITION add constraint FKA603CA28BC90E668 foreign key (TREATMENT_TEMPLATE_ID) references GST_TREATMENT_TEMPLATE;
alter table GST_TREATMENT_TEMPLATE add constraint FK36F41385786C49D foreign key (OWNED_BY) references GST_PARTY;
alter table GST_TREATMENT_TEMPLATE add constraint FK36F4138986111F9 foreign key (MODIFIED_BY) references GST_PARTY;
alter table GST_TREATMENT_TEMPLATE add constraint FK36F41382045368F foreign key (TREATMENT_TEMPLATE_CAT_ID) references GST_TREATMENT_TEMPLATE_CAT;
alter table GST_TREATMENT_TEMPLATE_CAT add constraint FK4B28182F460F2D7A foreign key (CREATED_BY) references GST_PARTY;
alter table GST_TREATMENT_TEMPLATE_CAT add constraint FK4B28182F986111F9 foreign key (MODIFIED_BY) references GST_PARTY;
alter table GST_TREATMENT_TEMPLATE_CONCEPT add constraint FKE3A13641BC90E668 foreign key (TREATMENT_TEMPLATE_ID) references GST_TREATMENT_TEMPLATE;
alter table GST_TREATMENT_TEMPLATE_CONCEPT add constraint FKE3A13641C2E29BD6 foreign key (CONCEPT_ID) references GST_CLINICAL_CONCEPT;
alter table GST_TREATMENT_TEMPLATE_DISEASE add constraint FKE91AD55BC90E668 foreign key (TREATMENT_TEMPLATE_ID) references GST_TREATMENT_TEMPLATE;
alter table GST_TREATMENT_TEMPLATE_DISEASE add constraint FKE91AD55B10526E3 foreign key (DISEASE_ID) references GST_DISEASE;
alter table GST_TREATMENT_TEMPLATE_SOURCE add constraint FK2AEAC902BC90E668 foreign key (TREATMENT_TEMPLATE_ID) references GST_TREATMENT_TEMPLATE;
alter table GST_TREATMENT_TEMPLATE_SOURCE add constraint FK2AEAC902433F4EB2 foreign key (RECORDED_BY) references GST_PARTY;
alter table GST_TRIGGER_CONCEPT_COLLECTION add constraint FKF54D0CB3D97770EB foreign key (COLLECTION_ID) references GST_FINDING_COLLECTION;
alter table GST_TRIGGER_CONCEPT_COLLECTION add constraint FKF54D0CB3730DC967 foreign key (VISIT_ID) references GST_CLINICAL_EVENT;
create index username_party_idx on GST_USERNAME (PERSON_PARTY_ID);
alter table GST_USERNAME add constraint FKB4B89A4D71D40D29 foreign key (ROLE_ID) references GST_PERSON_ROLE;
alter table GST_VALID_VALUE add constraint FKA7CC965789C00AEC foreign key (COMMON_VALUE_ID) references GST_COMMON_VALUE;
alter table GST_VALID_VALUE add constraint FKA7CC9657C2E29BD6 foreign key (CONCEPT_ID) references GST_CLINICAL_CONCEPT;
alter table HCPCS_CATEGORY add constraint FKBCE76A18E3F341B5 foreign key (PARENT_ID) references HCPCS_CATEGORY;
alter table HCPCS_CODE add constraint FK642D0007EB4848D6 foreign key (BE_TOS) references HCPCS_BE_TOS;
alter table HCPCS_CODE add constraint FK642D0007BA114E40 foreign key (COVERAGE_CODE) references HCPCS_COVERAGE_CODE;
alter table HCPCS_CODE add constraint FK642D0007F71C65C0 foreign key (ACTION_CODE) references HCPCS_ACTION_CODE;
alter table HCPCS_CODE add constraint FK642D0007421AF5AD foreign key (MOG_PMT_GRP_CODE) references HCPCS_MOG_PMT_GRP_CODE;
alter table HCPCS_CODE add constraint FK642D0007BF1F925A foreign key (MOG_PMT_POLICY_IND_CODE) references HCPCS_MOG_PMT_POLICY_IND_CODE;
alter table HCPCS_CODE add constraint FK642D0007184D6D7 foreign key (HCPCS_MULTI_PIC) references HCPCS_MULTI_PIC;
alter table HCPCS_CODE_CIM_REF add constraint FKDAD874A36EE7FDC7 foreign key (HCPCS_CODE_ID) references HCPCS_CODE;
alter table HCPCS_CODE_CMS_TOS add constraint FKE2006CEA6EE7FDC7 foreign key (HCPCS_CODE_ID) references HCPCS_CODE;
alter table HCPCS_CODE_CMS_TOS add constraint FKE2006CEA336E0874 foreign key (HCPCS_CMS_TOS_ID) references HCPCS_CMS_TOS;
alter table HCPCS_CODE_LABCERT add constraint FKA8A1D8D96EE7FDC7 foreign key (HCPCS_CODE_ID) references HCPCS_CODE;
alter table HCPCS_CODE_LABCERT add constraint FKA8A1D8D961C46395 foreign key (HCPCS_LAB_CERT_CODE_ID) references HCPCS_LAB_CERT_CODE;
alter table HCPCS_CODE_MCM_REF add constraint FKE199B1736EE7FDC7 foreign key (HCPCS_CODE_ID) references HCPCS_CODE;
alter table HCPCS_CODE_PIC add constraint FK863C09326E200F47 foreign key (HCPCS_PIC_ID) references HCPCS_PIC;
alter table HCPCS_CODE_PIC add constraint FK863C09326EE7FDC7 foreign key (HCPCS_CODE_ID) references HCPCS_CODE;
alter table HCPCS_CODE_XREF add constraint FK4148E2536EE7FDC7 foreign key (HCPCS_CODE_ID) references HCPCS_CODE;
alter table HCPCS_LAB_CERT_CODE add constraint FK9D0FF1FC97E22267 foreign key (PARENT_ID) references HCPCS_LAB_CERT_CODE;
alter table HCPCS_MODIFIER_CIM_REF add constraint FK634E9A8DFEACFC0A foreign key (HCPCS_MODIFIER_CODE_ID) references HCPCS_MODIFIER_CODE;
alter table HCPCS_MODIFIER_CODE add constraint FKCBFAFD7BBA114E40 foreign key (COVERAGE_CODE) references HCPCS_COVERAGE_CODE;
alter table HCPCS_MODIFIER_CODE add constraint FKCBFAFD7BF71C65C0 foreign key (ACTION_CODE) references HCPCS_ACTION_CODE;
alter table HCPCS_MODIFIER_MCM_REF add constraint FK6A0FD75DFEACFC0A foreign key (HCPCS_MODIFIER_CODE_ID) references HCPCS_MODIFIER_CODE;
alter table HCPCS_MODIFIER_XREF add constraint FKCC0494A9FEACFC0A foreign key (HCPCS_MODIFIER_CODE_ID) references HCPCS_MODIFIER_CODE;
alter table HCPCS_MOG_PMT_GRP_CODE add constraint FK69B91CA3D052C0E0 foreign key (HCPCS_BODY_SYSTEM_ID) references HCPCS_BODY_SYSTEM;
alter table HCPCS_TREE add constraint FK6434C5B8D994B13B foreign key (HCPCS_CODE) references HCPCS_CODE;
alter table HCPCS_TREE add constraint FK6434C5B8F8303D5 foreign key (PARENT_ID) references HCPCS_TREE;
alter table HCPCS_TREE add constraint FK6434C5B86B8F4DE3 foreign key (CATEGORY) references HCPCS_CATEGORY;
alter table INTERIM_REPORT add constraint FKB32C9373B7767F8D foreign key (INTERIM_NAME) references TEXT_LINE;
alter table INTERIM_REPORT add constraint FKB32C93737D85D6E8 foreign key (INTERIM_NAME) references SPECIMEN_LINE;
alter table INTERIM_REPORT add constraint FKB32C9373D4616C69 foreign key (INTERIM_NAME) references BATTERY_LINE;
alter table INTERIM_REPORT add constraint FKB32C93738B66506E foreign key (INTERIM_NAME) references ANALYTE_LINE;
alter table ORDER_REASON_LIST add constraint FKDF0BBE28401C0D9D foreign key (REASON_CD) references icd9;
alter table REQ_REPORT_FORM add constraint FK6ECEE2AE27AC0ED0 foreign key (INTERIM_NAME) references INTERIM_REPORT;
alter table icd9 add constraint FK313AEFD5E11D89 foreign key (CLASS_NAME) references icd9_class;
alter table icd9_class add constraint FK8B911828F2573C3E foreign key (PARENT_CLASS_NAME) references icd9_class;
create sequence null;
