package myorg.bouncycastle.jce.provider.asymmetric;

import java.util.HashMap;
import myorg.bouncycastle.asn1.DERObjectIdentifier;
import myorg.bouncycastle.asn1.cryptopro.CryptoProObjectIdentifiers;
import myorg.bouncycastle.asn1.eac.EACObjectIdentifiers;
import myorg.bouncycastle.asn1.teletrust.TeleTrusTObjectIdentifiers;
import myorg.bouncycastle.asn1.x9.X9ObjectIdentifiers;

public class ECMappings extends HashMap {

   public ECMappings() {
      Object var1 = this.put("KeyAgreement.ECDH", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyAgreement$DH");
      Object var2 = this.put("KeyAgreement.ECDHC", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyAgreement$DHC");
      Object var3 = this.put("KeyAgreement.ECMQV", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyAgreement$MQV");
      StringBuilder var4 = (new StringBuilder()).append("KeyAgreement.");
      DERObjectIdentifier var5 = X9ObjectIdentifiers.dhSinglePass_stdDH_sha1kdf_scheme;
      String var6 = var4.append(var5).toString();
      this.put(var6, "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyAgreement$DHwithSHA1KDF");
      StringBuilder var8 = (new StringBuilder()).append("KeyAgreement.");
      DERObjectIdentifier var9 = X9ObjectIdentifiers.mqvSinglePass_sha1kdf_scheme;
      String var10 = var8.append(var9).toString();
      this.put(var10, "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyAgreement$MQVwithSHA1KDF");
      Object var12 = this.put("KeyFactory.EC", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyFactory$EC");
      Object var13 = this.put("KeyFactory.ECDSA", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyFactory$ECDSA");
      Object var14 = this.put("KeyFactory.ECDH", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyFactory$ECDH");
      Object var15 = this.put("KeyFactory.ECDHC", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyFactory$ECDHC");
      Object var16 = this.put("KeyFactory.ECMQV", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyFactory$ECMQV");
      StringBuilder var17 = (new StringBuilder()).append("Alg.Alias.KeyFactory.");
      DERObjectIdentifier var18 = X9ObjectIdentifiers.id_ecPublicKey;
      String var19 = var17.append(var18).toString();
      this.put(var19, "EC");
      StringBuilder var21 = (new StringBuilder()).append("Alg.Alias.KeyFactory.");
      DERObjectIdentifier var22 = X9ObjectIdentifiers.dhSinglePass_stdDH_sha1kdf_scheme;
      String var23 = var21.append(var22).toString();
      this.put(var23, "EC");
      StringBuilder var25 = (new StringBuilder()).append("Alg.Alias.KeyFactory.");
      DERObjectIdentifier var26 = X9ObjectIdentifiers.mqvSinglePass_sha1kdf_scheme;
      String var27 = var25.append(var26).toString();
      this.put(var27, "ECMQV");
      Object var29 = this.put("KeyFactory.ECGOST3410", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyFactory$ECGOST3410");
      Object var30 = this.put("Alg.Alias.KeyFactory.GOST-3410-2001", "ECGOST3410");
      Object var31 = this.put("Alg.Alias.KeyFactory.ECGOST-3410", "ECGOST3410");
      StringBuilder var32 = (new StringBuilder()).append("Alg.Alias.KeyFactory.");
      DERObjectIdentifier var33 = CryptoProObjectIdentifiers.gostR3410_2001;
      String var34 = var32.append(var33).toString();
      this.put(var34, "ECGOST3410");
      Object var36 = this.put("KeyPairGenerator.EC", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyPairGenerator$EC");
      Object var37 = this.put("KeyPairGenerator.ECDSA", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyPairGenerator$ECDSA");
      Object var38 = this.put("KeyPairGenerator.ECDH", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyPairGenerator$ECDH");
      Object var39 = this.put("KeyPairGenerator.ECDHC", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyPairGenerator$ECDHC");
      Object var40 = this.put("KeyPairGenerator.ECIES", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyPairGenerator$ECDH");
      Object var41 = this.put("KeyPairGenerator.ECMQV", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyPairGenerator$ECMQV");
      StringBuilder var42 = (new StringBuilder()).append("Alg.Alias.KeyPairGenerator.");
      DERObjectIdentifier var43 = X9ObjectIdentifiers.dhSinglePass_stdDH_sha1kdf_scheme;
      String var44 = var42.append(var43).toString();
      this.put(var44, "EC");
      StringBuilder var46 = (new StringBuilder()).append("Alg.Alias.KeyPairGenerator.");
      DERObjectIdentifier var47 = X9ObjectIdentifiers.mqvSinglePass_sha1kdf_scheme;
      String var48 = var46.append(var47).toString();
      this.put(var48, "ECMQV");
      Object var50 = this.put("KeyPairGenerator.ECGOST3410", "myorg.bouncycastle.jce.provider.asymmetric.ec.KeyPairGenerator$ECGOST3410");
      Object var51 = this.put("Alg.Alias.KeyPairGenerator.ECGOST-3410", "ECGOST3410");
      Object var52 = this.put("Alg.Alias.KeyPairGenerator.GOST-3410-2001", "ECGOST3410");
      Object var53 = this.put("Signature.ECDSA", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecDSA");
      Object var54 = this.put("Signature.NONEwithECDSA", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecDSAnone");
      Object var55 = this.put("Alg.Alias.Signature.SHA1withECDSA", "ECDSA");
      Object var56 = this.put("Alg.Alias.Signature.ECDSAwithSHA1", "ECDSA");
      Object var57 = this.put("Alg.Alias.Signature.SHA1WITHECDSA", "ECDSA");
      Object var58 = this.put("Alg.Alias.Signature.ECDSAWITHSHA1", "ECDSA");
      Object var59 = this.put("Alg.Alias.Signature.SHA1WithECDSA", "ECDSA");
      Object var60 = this.put("Alg.Alias.Signature.ECDSAWithSHA1", "ECDSA");
      Object var61 = this.put("Alg.Alias.Signature.1.2.840.10045.4.1", "ECDSA");
      StringBuilder var62 = (new StringBuilder()).append("Alg.Alias.Signature.");
      DERObjectIdentifier var63 = TeleTrusTObjectIdentifiers.ecSignWithSha1;
      String var64 = var62.append(var63).toString();
      this.put(var64, "ECDSA");
      DERObjectIdentifier var66 = X9ObjectIdentifiers.ecdsa_with_SHA224;
      this.addSignatureAlgorithm("SHA224", "ECDSA", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecDSA224", var66);
      DERObjectIdentifier var67 = X9ObjectIdentifiers.ecdsa_with_SHA256;
      this.addSignatureAlgorithm("SHA256", "ECDSA", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecDSA256", var67);
      DERObjectIdentifier var68 = X9ObjectIdentifiers.ecdsa_with_SHA384;
      this.addSignatureAlgorithm("SHA384", "ECDSA", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecDSA384", var68);
      DERObjectIdentifier var69 = X9ObjectIdentifiers.ecdsa_with_SHA512;
      this.addSignatureAlgorithm("SHA512", "ECDSA", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecDSA512", var69);
      DERObjectIdentifier var70 = TeleTrusTObjectIdentifiers.ecSignWithRipemd160;
      this.addSignatureAlgorithm("RIPEMD160", "ECDSA", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecDSARipeMD160", var70);
      Object var71 = this.put("Signature.SHA1WITHECNR", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecNR");
      Object var72 = this.put("Signature.SHA224WITHECNR", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecNR224");
      Object var73 = this.put("Signature.SHA256WITHECNR", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecNR256");
      Object var74 = this.put("Signature.SHA384WITHECNR", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecNR384");
      Object var75 = this.put("Signature.SHA512WITHECNR", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecNR512");
      DERObjectIdentifier var76 = EACObjectIdentifiers.id_TA_ECDSA_SHA_1;
      this.addSignatureAlgorithm("SHA1", "CVC-ECDSA", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecCVCDSA", var76);
      DERObjectIdentifier var77 = EACObjectIdentifiers.id_TA_ECDSA_SHA_224;
      this.addSignatureAlgorithm("SHA224", "CVC-ECDSA", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecCVCDSA224", var77);
      DERObjectIdentifier var78 = EACObjectIdentifiers.id_TA_ECDSA_SHA_256;
      this.addSignatureAlgorithm("SHA256", "CVC-ECDSA", "myorg.bouncycastle.jce.provider.asymmetric.ec.Signature$ecCVCDSA256", var78);
   }

   private void addSignatureAlgorithm(String var1, String var2, String var3, DERObjectIdentifier var4) {
      String var5 = var1 + "WITH" + var2;
      String var6 = var1 + "with" + var2;
      String var7 = var1 + "With" + var2;
      String var8 = var1 + "/" + var2;
      String var9 = "Signature." + var5;
      this.put(var9, var3);
      String var11 = "Alg.Alias.Signature." + var6;
      this.put(var11, var5);
      String var13 = "Alg.Alias.Signature." + var7;
      this.put(var13, var5);
      String var15 = "Alg.Alias.Signature." + var8;
      this.put(var15, var5);
      String var17 = "Alg.Alias.Signature." + var4;
      this.put(var17, var5);
      String var19 = "Alg.Alias.Signature.OID." + var4;
      this.put(var19, var5);
   }
}
