package myorg.bouncycastle.jce.provider.symmetric;

import java.util.HashMap;
import myorg.bouncycastle.asn1.DERObjectIdentifier;
import myorg.bouncycastle.asn1.nist.NISTObjectIdentifiers;

public class AESMappings extends HashMap {

   private static final String wrongAES128 = "2.16.840.1.101.3.4.2";
   private static final String wrongAES192 = "2.16.840.1.101.3.4.22";
   private static final String wrongAES256 = "2.16.840.1.101.3.4.42";


   public AESMappings() {
      Object var1 = this.put("AlgorithmParameters.AES", "myorg.bouncycastle.jce.provider.symmetric.AES$AlgParams");
      Object var2 = this.put("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.2", "AES");
      Object var3 = this.put("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.22", "AES");
      Object var4 = this.put("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.42", "AES");
      StringBuilder var5 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      DERObjectIdentifier var6 = NISTObjectIdentifiers.id_aes128_CBC;
      String var7 = var5.append(var6).toString();
      this.put(var7, "AES");
      StringBuilder var9 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      DERObjectIdentifier var10 = NISTObjectIdentifiers.id_aes192_CBC;
      String var11 = var9.append(var10).toString();
      this.put(var11, "AES");
      StringBuilder var13 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      DERObjectIdentifier var14 = NISTObjectIdentifiers.id_aes256_CBC;
      String var15 = var13.append(var14).toString();
      this.put(var15, "AES");
      Object var17 = this.put("AlgorithmParameterGenerator.AES", "myorg.bouncycastle.jce.provider.symmetric.AES$AlgParamGen");
      Object var18 = this.put("Alg.Alias.AlgorithmParameterGenerator.2.16.840.1.101.3.4.2", "AES");
      Object var19 = this.put("Alg.Alias.AlgorithmParameterGenerator.2.16.840.1.101.3.4.22", "AES");
      Object var20 = this.put("Alg.Alias.AlgorithmParameterGenerator.2.16.840.1.101.3.4.42", "AES");
      StringBuilder var21 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameterGenerator.");
      DERObjectIdentifier var22 = NISTObjectIdentifiers.id_aes128_CBC;
      String var23 = var21.append(var22).toString();
      this.put(var23, "AES");
      StringBuilder var25 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameterGenerator.");
      DERObjectIdentifier var26 = NISTObjectIdentifiers.id_aes192_CBC;
      String var27 = var25.append(var26).toString();
      this.put(var27, "AES");
      StringBuilder var29 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameterGenerator.");
      DERObjectIdentifier var30 = NISTObjectIdentifiers.id_aes256_CBC;
      String var31 = var29.append(var30).toString();
      this.put(var31, "AES");
      Object var33 = this.put("Cipher.AES", "myorg.bouncycastle.jce.provider.symmetric.AES$ECB");
      Object var34 = this.put("Alg.Alias.Cipher.2.16.840.1.101.3.4.2", "AES");
      Object var35 = this.put("Alg.Alias.Cipher.2.16.840.1.101.3.4.22", "AES");
      Object var36 = this.put("Alg.Alias.Cipher.2.16.840.1.101.3.4.42", "AES");
      StringBuilder var37 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var38 = NISTObjectIdentifiers.id_aes128_ECB;
      String var39 = var37.append(var38).toString();
      this.put(var39, "myorg.bouncycastle.jce.provider.symmetric.AES$ECB");
      StringBuilder var41 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var42 = NISTObjectIdentifiers.id_aes192_ECB;
      String var43 = var41.append(var42).toString();
      this.put(var43, "myorg.bouncycastle.jce.provider.symmetric.AES$ECB");
      StringBuilder var45 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var46 = NISTObjectIdentifiers.id_aes256_ECB;
      String var47 = var45.append(var46).toString();
      this.put(var47, "myorg.bouncycastle.jce.provider.symmetric.AES$ECB");
      StringBuilder var49 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var50 = NISTObjectIdentifiers.id_aes128_CBC;
      String var51 = var49.append(var50).toString();
      this.put(var51, "myorg.bouncycastle.jce.provider.symmetric.AES$CBC");
      StringBuilder var53 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var54 = NISTObjectIdentifiers.id_aes192_CBC;
      String var55 = var53.append(var54).toString();
      this.put(var55, "myorg.bouncycastle.jce.provider.symmetric.AES$CBC");
      StringBuilder var57 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var58 = NISTObjectIdentifiers.id_aes256_CBC;
      String var59 = var57.append(var58).toString();
      this.put(var59, "myorg.bouncycastle.jce.provider.symmetric.AES$CBC");
      StringBuilder var61 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var62 = NISTObjectIdentifiers.id_aes128_OFB;
      String var63 = var61.append(var62).toString();
      this.put(var63, "myorg.bouncycastle.jce.provider.symmetric.AES$OFB");
      StringBuilder var65 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var66 = NISTObjectIdentifiers.id_aes192_OFB;
      String var67 = var65.append(var66).toString();
      this.put(var67, "myorg.bouncycastle.jce.provider.symmetric.AES$OFB");
      StringBuilder var69 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var70 = NISTObjectIdentifiers.id_aes256_OFB;
      String var71 = var69.append(var70).toString();
      this.put(var71, "myorg.bouncycastle.jce.provider.symmetric.AES$OFB");
      StringBuilder var73 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var74 = NISTObjectIdentifiers.id_aes128_CFB;
      String var75 = var73.append(var74).toString();
      this.put(var75, "myorg.bouncycastle.jce.provider.symmetric.AES$CFB");
      StringBuilder var77 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var78 = NISTObjectIdentifiers.id_aes192_CFB;
      String var79 = var77.append(var78).toString();
      this.put(var79, "myorg.bouncycastle.jce.provider.symmetric.AES$CFB");
      StringBuilder var81 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var82 = NISTObjectIdentifiers.id_aes256_CFB;
      String var83 = var81.append(var82).toString();
      this.put(var83, "myorg.bouncycastle.jce.provider.symmetric.AES$CFB");
      Object var85 = this.put("Cipher.AESWRAP", "myorg.bouncycastle.jce.provider.symmetric.AES$Wrap");
      StringBuilder var86 = (new StringBuilder()).append("Alg.Alias.Cipher.");
      DERObjectIdentifier var87 = NISTObjectIdentifiers.id_aes128_wrap;
      String var88 = var86.append(var87).toString();
      this.put(var88, "AESWRAP");
      StringBuilder var90 = (new StringBuilder()).append("Alg.Alias.Cipher.");
      DERObjectIdentifier var91 = NISTObjectIdentifiers.id_aes192_wrap;
      String var92 = var90.append(var91).toString();
      this.put(var92, "AESWRAP");
      StringBuilder var94 = (new StringBuilder()).append("Alg.Alias.Cipher.");
      DERObjectIdentifier var95 = NISTObjectIdentifiers.id_aes256_wrap;
      String var96 = var94.append(var95).toString();
      this.put(var96, "AESWRAP");
      Object var98 = this.put("Cipher.AESRFC3211WRAP", "myorg.bouncycastle.jce.provider.symmetric.AES$RFC3211Wrap");
      Object var99 = this.put("KeyGenerator.AES", "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen");
      Object var100 = this.put("KeyGenerator.2.16.840.1.101.3.4.2", "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen128");
      Object var101 = this.put("KeyGenerator.2.16.840.1.101.3.4.22", "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen192");
      Object var102 = this.put("KeyGenerator.2.16.840.1.101.3.4.42", "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen256");
      StringBuilder var103 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var104 = NISTObjectIdentifiers.id_aes128_ECB;
      String var105 = var103.append(var104).toString();
      this.put(var105, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen128");
      StringBuilder var107 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var108 = NISTObjectIdentifiers.id_aes128_CBC;
      String var109 = var107.append(var108).toString();
      this.put(var109, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen128");
      StringBuilder var111 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var112 = NISTObjectIdentifiers.id_aes128_OFB;
      String var113 = var111.append(var112).toString();
      this.put(var113, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen128");
      StringBuilder var115 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var116 = NISTObjectIdentifiers.id_aes128_CFB;
      String var117 = var115.append(var116).toString();
      this.put(var117, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen128");
      StringBuilder var119 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var120 = NISTObjectIdentifiers.id_aes192_ECB;
      String var121 = var119.append(var120).toString();
      this.put(var121, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen192");
      StringBuilder var123 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var124 = NISTObjectIdentifiers.id_aes192_CBC;
      String var125 = var123.append(var124).toString();
      this.put(var125, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen192");
      StringBuilder var127 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var128 = NISTObjectIdentifiers.id_aes192_OFB;
      String var129 = var127.append(var128).toString();
      this.put(var129, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen192");
      StringBuilder var131 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var132 = NISTObjectIdentifiers.id_aes192_CFB;
      String var133 = var131.append(var132).toString();
      this.put(var133, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen192");
      StringBuilder var135 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var136 = NISTObjectIdentifiers.id_aes256_ECB;
      String var137 = var135.append(var136).toString();
      this.put(var137, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen256");
      StringBuilder var139 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var140 = NISTObjectIdentifiers.id_aes256_CBC;
      String var141 = var139.append(var140).toString();
      this.put(var141, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen256");
      StringBuilder var143 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var144 = NISTObjectIdentifiers.id_aes256_OFB;
      String var145 = var143.append(var144).toString();
      this.put(var145, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen256");
      StringBuilder var147 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var148 = NISTObjectIdentifiers.id_aes256_CFB;
      String var149 = var147.append(var148).toString();
      this.put(var149, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen256");
      Object var151 = this.put("KeyGenerator.AESWRAP", "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen");
      StringBuilder var152 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var153 = NISTObjectIdentifiers.id_aes128_wrap;
      String var154 = var152.append(var153).toString();
      this.put(var154, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen128");
      StringBuilder var156 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var157 = NISTObjectIdentifiers.id_aes192_wrap;
      String var158 = var156.append(var157).toString();
      this.put(var158, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen192");
      StringBuilder var160 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var161 = NISTObjectIdentifiers.id_aes256_wrap;
      String var162 = var160.append(var161).toString();
      this.put(var162, "myorg.bouncycastle.jce.provider.symmetric.AES$KeyGen256");
   }
}
