package myorg.bouncycastle.jce.provider.symmetric;

import java.util.HashMap;
import myorg.bouncycastle.asn1.DERObjectIdentifier;
import myorg.bouncycastle.asn1.ntt.NTTObjectIdentifiers;

public class CamelliaMappings extends HashMap {

   public CamelliaMappings() {
      Object var1 = this.put("AlgorithmParameters.CAMELLIA", "myorg.bouncycastle.jce.provider.symmetric.Camellia$AlgParams");
      StringBuilder var2 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      DERObjectIdentifier var3 = NTTObjectIdentifiers.id_camellia128_cbc;
      String var4 = var2.append(var3).toString();
      this.put(var4, "CAMELLIA");
      StringBuilder var6 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      DERObjectIdentifier var7 = NTTObjectIdentifiers.id_camellia192_cbc;
      String var8 = var6.append(var7).toString();
      this.put(var8, "CAMELLIA");
      StringBuilder var10 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameters.");
      DERObjectIdentifier var11 = NTTObjectIdentifiers.id_camellia256_cbc;
      String var12 = var10.append(var11).toString();
      this.put(var12, "CAMELLIA");
      Object var14 = this.put("AlgorithmParameterGenerator.CAMELLIA", "myorg.bouncycastle.jce.provider.symmetric.Camellia$AlgParamGen");
      StringBuilder var15 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameterGenerator.");
      DERObjectIdentifier var16 = NTTObjectIdentifiers.id_camellia128_cbc;
      String var17 = var15.append(var16).toString();
      this.put(var17, "CAMELLIA");
      StringBuilder var19 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameterGenerator.");
      DERObjectIdentifier var20 = NTTObjectIdentifiers.id_camellia192_cbc;
      String var21 = var19.append(var20).toString();
      this.put(var21, "CAMELLIA");
      StringBuilder var23 = (new StringBuilder()).append("Alg.Alias.AlgorithmParameterGenerator.");
      DERObjectIdentifier var24 = NTTObjectIdentifiers.id_camellia256_cbc;
      String var25 = var23.append(var24).toString();
      this.put(var25, "CAMELLIA");
      Object var27 = this.put("Cipher.CAMELLIA", "myorg.bouncycastle.jce.provider.symmetric.Camellia$ECB");
      StringBuilder var28 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var29 = NTTObjectIdentifiers.id_camellia128_cbc;
      String var30 = var28.append(var29).toString();
      this.put(var30, "myorg.bouncycastle.jce.provider.symmetric.Camellia$CBC");
      StringBuilder var32 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var33 = NTTObjectIdentifiers.id_camellia192_cbc;
      String var34 = var32.append(var33).toString();
      this.put(var34, "myorg.bouncycastle.jce.provider.symmetric.Camellia$CBC");
      StringBuilder var36 = (new StringBuilder()).append("Cipher.");
      DERObjectIdentifier var37 = NTTObjectIdentifiers.id_camellia256_cbc;
      String var38 = var36.append(var37).toString();
      this.put(var38, "myorg.bouncycastle.jce.provider.symmetric.Camellia$CBC");
      Object var40 = this.put("Cipher.CAMELLIARFC3211WRAP", "myorg.bouncycastle.jce.provider.symmetric.Camellia$RFC3211Wrap");
      Object var41 = this.put("Cipher.CAMELLIAWRAP", "myorg.bouncycastle.jce.provider.symmetric.Camellia$Wrap");
      StringBuilder var42 = (new StringBuilder()).append("Alg.Alias.Cipher.");
      DERObjectIdentifier var43 = NTTObjectIdentifiers.id_camellia128_wrap;
      String var44 = var42.append(var43).toString();
      this.put(var44, "CAMELLIAWRAP");
      StringBuilder var46 = (new StringBuilder()).append("Alg.Alias.Cipher.");
      DERObjectIdentifier var47 = NTTObjectIdentifiers.id_camellia192_wrap;
      String var48 = var46.append(var47).toString();
      this.put(var48, "CAMELLIAWRAP");
      StringBuilder var50 = (new StringBuilder()).append("Alg.Alias.Cipher.");
      DERObjectIdentifier var51 = NTTObjectIdentifiers.id_camellia256_wrap;
      String var52 = var50.append(var51).toString();
      this.put(var52, "CAMELLIAWRAP");
      Object var54 = this.put("KeyGenerator.CAMELLIA", "myorg.bouncycastle.jce.provider.symmetric.Camellia$KeyGen");
      StringBuilder var55 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var56 = NTTObjectIdentifiers.id_camellia128_wrap;
      String var57 = var55.append(var56).toString();
      this.put(var57, "myorg.bouncycastle.jce.provider.symmetric.Camellia$KeyGen128");
      StringBuilder var59 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var60 = NTTObjectIdentifiers.id_camellia192_wrap;
      String var61 = var59.append(var60).toString();
      this.put(var61, "myorg.bouncycastle.jce.provider.symmetric.Camellia$KeyGen192");
      StringBuilder var63 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var64 = NTTObjectIdentifiers.id_camellia256_wrap;
      String var65 = var63.append(var64).toString();
      this.put(var65, "myorg.bouncycastle.jce.provider.symmetric.Camellia$KeyGen256");
      StringBuilder var67 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var68 = NTTObjectIdentifiers.id_camellia128_cbc;
      String var69 = var67.append(var68).toString();
      this.put(var69, "myorg.bouncycastle.jce.provider.symmetric.Camellia$KeyGen128");
      StringBuilder var71 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var72 = NTTObjectIdentifiers.id_camellia192_cbc;
      String var73 = var71.append(var72).toString();
      this.put(var73, "myorg.bouncycastle.jce.provider.symmetric.Camellia$KeyGen192");
      StringBuilder var75 = (new StringBuilder()).append("KeyGenerator.");
      DERObjectIdentifier var76 = NTTObjectIdentifiers.id_camellia256_cbc;
      String var77 = var75.append(var76).toString();
      this.put(var77, "myorg.bouncycastle.jce.provider.symmetric.Camellia$KeyGen256");
   }
}
