package myorg.bouncycastle.asn1.teletrust;

import myorg.bouncycastle.asn1.DERObjectIdentifier;

public interface TeleTrusTObjectIdentifiers {

   DERObjectIdentifier brainpoolP160r1;
   DERObjectIdentifier brainpoolP160t1;
   DERObjectIdentifier brainpoolP192r1;
   DERObjectIdentifier brainpoolP192t1;
   DERObjectIdentifier brainpoolP224r1;
   DERObjectIdentifier brainpoolP224t1;
   DERObjectIdentifier brainpoolP256r1;
   DERObjectIdentifier brainpoolP256t1;
   DERObjectIdentifier brainpoolP320r1;
   DERObjectIdentifier brainpoolP320t1;
   DERObjectIdentifier brainpoolP384r1;
   DERObjectIdentifier brainpoolP384t1;
   DERObjectIdentifier brainpoolP512r1;
   DERObjectIdentifier brainpoolP512t1;
   DERObjectIdentifier ecSign = new DERObjectIdentifier("1.3.36.3.3.2");
   DERObjectIdentifier ecSignWithRipemd160;
   DERObjectIdentifier ecSignWithSha1;
   DERObjectIdentifier ecc_brainpool;
   DERObjectIdentifier ellipticCurve;
   DERObjectIdentifier ripemd128 = new DERObjectIdentifier("1.3.36.3.2.2");
   DERObjectIdentifier ripemd160 = new DERObjectIdentifier("1.3.36.3.2.1");
   DERObjectIdentifier ripemd256 = new DERObjectIdentifier("1.3.36.3.2.3");
   DERObjectIdentifier rsaSignatureWithripemd128 = new DERObjectIdentifier("1.3.36.3.3.1.3");
   DERObjectIdentifier rsaSignatureWithripemd160 = new DERObjectIdentifier("1.3.36.3.3.1.2");
   DERObjectIdentifier rsaSignatureWithripemd256 = new DERObjectIdentifier("1.3.36.3.3.1.4");
   String teleTrusTAlgorithm = "1.3.36.3";
   String teleTrusTRSAsignatureAlgorithm = "1.3.36.3.3.1";
   DERObjectIdentifier versionOne;


   static {
      StringBuilder var0 = new StringBuilder();
      DERObjectIdentifier var1 = ecSign;
      String var2 = var0.append(var1).append(".1").toString();
      ecSignWithSha1 = new DERObjectIdentifier(var2);
      StringBuilder var3 = new StringBuilder();
      DERObjectIdentifier var4 = ecSign;
      String var5 = var3.append(var4).append(".2").toString();
      ecSignWithRipemd160 = new DERObjectIdentifier(var5);
      ecc_brainpool = new DERObjectIdentifier("1.3.36.3.3.2.8");
      StringBuilder var6 = new StringBuilder();
      DERObjectIdentifier var7 = ecc_brainpool;
      String var8 = var6.append(var7).append(".1").toString();
      ellipticCurve = new DERObjectIdentifier(var8);
      StringBuilder var9 = new StringBuilder();
      DERObjectIdentifier var10 = ellipticCurve;
      String var11 = var9.append(var10).append(".1").toString();
      versionOne = new DERObjectIdentifier(var11);
      StringBuilder var12 = new StringBuilder();
      DERObjectIdentifier var13 = versionOne;
      String var14 = var12.append(var13).append(".1").toString();
      brainpoolP160r1 = new DERObjectIdentifier(var14);
      StringBuilder var15 = new StringBuilder();
      DERObjectIdentifier var16 = versionOne;
      String var17 = var15.append(var16).append(".2").toString();
      brainpoolP160t1 = new DERObjectIdentifier(var17);
      StringBuilder var18 = new StringBuilder();
      DERObjectIdentifier var19 = versionOne;
      String var20 = var18.append(var19).append(".3").toString();
      brainpoolP192r1 = new DERObjectIdentifier(var20);
      StringBuilder var21 = new StringBuilder();
      DERObjectIdentifier var22 = versionOne;
      String var23 = var21.append(var22).append(".4").toString();
      brainpoolP192t1 = new DERObjectIdentifier(var23);
      StringBuilder var24 = new StringBuilder();
      DERObjectIdentifier var25 = versionOne;
      String var26 = var24.append(var25).append(".5").toString();
      brainpoolP224r1 = new DERObjectIdentifier(var26);
      StringBuilder var27 = new StringBuilder();
      DERObjectIdentifier var28 = versionOne;
      String var29 = var27.append(var28).append(".6").toString();
      brainpoolP224t1 = new DERObjectIdentifier(var29);
      StringBuilder var30 = new StringBuilder();
      DERObjectIdentifier var31 = versionOne;
      String var32 = var30.append(var31).append(".7").toString();
      brainpoolP256r1 = new DERObjectIdentifier(var32);
      StringBuilder var33 = new StringBuilder();
      DERObjectIdentifier var34 = versionOne;
      String var35 = var33.append(var34).append(".8").toString();
      brainpoolP256t1 = new DERObjectIdentifier(var35);
      StringBuilder var36 = new StringBuilder();
      DERObjectIdentifier var37 = versionOne;
      String var38 = var36.append(var37).append(".9").toString();
      brainpoolP320r1 = new DERObjectIdentifier(var38);
      StringBuilder var39 = new StringBuilder();
      DERObjectIdentifier var40 = versionOne;
      String var41 = var39.append(var40).append(".10").toString();
      brainpoolP320t1 = new DERObjectIdentifier(var41);
      StringBuilder var42 = new StringBuilder();
      DERObjectIdentifier var43 = versionOne;
      String var44 = var42.append(var43).append(".11").toString();
      brainpoolP384r1 = new DERObjectIdentifier(var44);
      StringBuilder var45 = new StringBuilder();
      DERObjectIdentifier var46 = versionOne;
      String var47 = var45.append(var46).append(".12").toString();
      brainpoolP384t1 = new DERObjectIdentifier(var47);
      StringBuilder var48 = new StringBuilder();
      DERObjectIdentifier var49 = versionOne;
      String var50 = var48.append(var49).append(".13").toString();
      brainpoolP512r1 = new DERObjectIdentifier(var50);
      StringBuilder var51 = new StringBuilder();
      DERObjectIdentifier var52 = versionOne;
      String var53 = var51.append(var52).append(".14").toString();
      brainpoolP512t1 = new DERObjectIdentifier(var53);
   }
}
